opentofu/opentofu

- README.md
The announcement includes a lot of important context about the current state of the fork, so I've added it to the README. Feedback on where to put it and how to phrase it is very welcome.
Fixes #
1.5.x
-
> Add fork announcement links to README

- .github/pull_request_template.md
Update the template description
Fixes #294
1.6.0
-
> Update pull request template's `Target Release` version

- README.md
Resolves #
Remove duplicate word in README
1.6.0
-
> Remove duplicate in readme

- .github/pull_request_template.md
- .github/workflows/pr-lint.yml
Resolves #325
Related to this PR https://github.com/opentfoundation/opentf/pulls/326
Fix the comment made by @RLRabinowitz https://github.com/opentffoundation/opentf/pull/326#discussion_r1318527292
And added a gh comment for when ci fail
1.6.0
-
> add comment on pr validation error

- .goreleaser.yaml
Resolves #160 
1.6.0
- Packages for deb, rpm and apk are built in the release process and published as release artifacts with goreleaser
> feat: add apk, deb and rpm package build to goreleaser

- .github/workflows/checks.yml
- .licensei.toml
- CONTRIBUTING.md
- Makefile
- go.mod
- go.sum
Resolves https://github.com/opentffoundation/opentf/issues/305
Submitted as draft as it is still WIP.
> feat: add license checks on dependencies

- CONTRIBUTING.md
> Update contributing guidelines to mention the accepted label in issues.

- .github/workflows/checks.yml
> fix(ci): disable licensei check as it currently hits GitHub API rate limits

- .github/workflows/pr-lint.yml
Resolves https://github.com/opentffoundation/opentf/issues/409
Resolves #409
1.6.0
-
> Fix pr linting fail when pasting issue url

- website/docs/cli/commands/apply.mdx
- website/docs/cli/commands/plan.mdx
- website/docs/language/expressions/types.mdx
- website/docs/language/syntax/json.mdx
part of https://github.com/opentffoundation/opentf/issues/434
1.6.0
-
> fix /opentf links

- .goreleaser.yaml
Resolves  #437
I forked the repo and ran the publish action, what was missing in order to generate the artifacts and link them was altering the `draft: true`
1.6.0
-
> fix the release process

- internal/states/statefile/read.go
- internal/states/statefile/version3_upgrade.go
- internal/states/statefile/version4.go
> Update `internal/states` folder to OpenTofu

- internal/backend/remote-state/azure/arm_client.go
- internal/backend/remote-state/gcs/backend.go
- internal/backend/remote-state/gcs/backend_test.go
- internal/backend/remote-state/kubernetes/backend.go
- internal/backend/remote-state/oss/backend.go
- internal/backend/remote/testing.go
- internal/cloud/testing.go
- internal/command/login_test.go
- internal/httpclient/client.go
- internal/httpclient/client_test.go
- internal/httpclient/useragent.go
- internal/httpclient/useragent_test.go
- internal/registry/client.go
- internal/registry/client_test.go
- internal/registry/test/mock_registry.go
- main.go
> Update `internal/httpclient` folder to OpenTofu

- internal/builtin/providers/tf/resource_data.go
- internal/dag/marshal.go
- internal/experiments/experiment.go
- internal/instances/expander.go
- internal/ipaddr/README.md
- internal/logging/panic.go
- internal/refactoring/move_validate.go
Resolves #475
Resolves #474
Resolves #472
Resolves #471
Resolves #470
Resolves #469
Resolves #469
1.6.0
-
> OpenTofu rename - packages with tiny renames

- internal/command/init_test.go
- internal/providercache/installer.go
- internal/providercache/installer_test.go
- internal/refactoring/move_validate.go
Resolves #478 
Resolves #477 
1.6.0
> Rename internal/providercache + internal/refactoring to OpenTofu

- .gitignore
> fix: add opentofu to .gitignore

- internal/initwd/module_install.go
- scripts/build.sh
- scripts/debug-opentofu
- scripts/staticcheck.sh
> Update scripts directory to OpenTofu

- README.md
Resolves #457 
Waiting for https://github.com/opentofu/brand-artifacts/pull/2
1.6.0
-
> Update relevant logo for each theme

- internal/plugin/discovery/meta_set.go
> rename opentf in internal/plugin

- main.go
> Renaming to OpenTofu leftover in `main.go`

- .goreleaser.yaml
- CONTRIBUTING.md
Resolves #527 
Part of #451 
1.6.0
-
> update maintainer and contirbuting to OpenTofu

- .github/workflows/build.yml
Resolves #635
Reference https://github.com/opentofu/tofu-exec/pull/1
Working build - https://github.com/opentofu/opentofu/actions/runs/6391164405/job/17346396689
1.6.0
-
> Use `opentofu/tofu-exec` fork to fix build workflow

- WEEKLY_UPDATES.md
> Switch weekly update date format.

- CHANGELOG.md
> Updated changlog with missing information

- go.mod
- go.sum
Fix https://github.com/opentofu/opentofu/issues/655
> Fix unknown conditional with sensitive branches erroring.

- CHANGELOG.md
Apologies, forgot it in the original PR.
> Add changelog entry about the fix to conditionals with an unknown condition and sensitive branch.

- internal/backend/remote-state/s3/backend.go
- internal/command/e2etest/automation_test.go
- internal/command/import.go
- internal/command/init.go
- internal/command/meta_backend_migrate.go
- internal/legacy/tofu/resource_address.go
- internal/providercache/installer_test.go
- internal/providercache/package_install.go
- website/docs/cli/commands/version.mdx
- website/docs/cli/config/config-file.mdx
- website/docs/language/checks/index.mdx
- website/docs/language/expressions/custom-conditions.mdx
- website/docs/language/functions/plantimestamp.mdx
- website/docs/language/functions/uuidv5.mdx
Part of #165
Updated docs and example
1.6.0
-
> Update placeholderplaceholderplaceholder occurrences to our doc site

- website/docs/cli/install/apt.mdx
- website/docs/cli/install/yum.mdx
- website/docs/intro/install.mdx
> Add installation instructions.

- website/docs/intro/install.mdx
> Update to be more consistent across operating systems.

- CODE_OF_CONDUCT.md
- Dockerfile
> Update core team email.

- .gitignore
- CONTRIBUTING.md
- DEBUGGING.md
- scripts/debug-opentofu
resolves #710.
I'd be glad if you can add a hacktoberfest-accepted tag to this PR, please.
A note to the reviewers, English is not my native language, so pardon me for any grammatical mistakes, and please don't hesitate to suggest a clearer version of the sentences.  
I'm not familiar with Goland IDE, so maybe @kislerdm might be interested in contributing to this guide if necessary for including Goland IDE debugging information. :)
Please review.
1.6.0
-
> Add DEBUGGING.md

- CHANGELOG.md
Pulls in the changelog that I forgot to add in #830
> Add changelog that was missed in PR #830

- README.md
Resolves #654
1.6.0
-  Updates main readme.md with installation guide
-  Minor syntax cleanup on other bullets existing.
> add installation guide to readme

- CHANGELOG.md
related to #855
Updates the changelogafter #855 was merged
1.6.0
> Updated changelog to reflect consistent spelling of the word initialization

- CHANGELOG.md
> Add GPG Expiration entry in the CHANGELOG

- Makefile
Resolves #912 
1.6.0
- Added the makefile rule to trigger the integration test with kubernetes
- To ensure the OpenTofu stability with various backends
> Add dependencies for integration tests with Kubernetes as backend

- website/docs/index.mdx
This PR fixes the docs page broken in #890
> Fixing broken docs page symlink

- Makefile
> Add gcs end-to-end tests to the makefile.

- website/docs/intro/install/test-install-instructions.sh
This PR improves the install instructions test to emit a GitHub actions compatible format. (Related to #937)
N/A
> website: Better install instructions (GitHub actions compatible output)

- website/docs/intro/install/homebrew.mdx
- website/docs/intro/install/index.mdx
Homebrew instructions work on Linux too.
Resolves #
1.6.0
> Update brew install for Linux

- .github/workflows/release.yml
- .goreleaser.yaml
This PR fixes the issues highlighted in #1000 after the merge.
1.6.0
> GPG build fixes

- .github/workflows/release.yml
This PR adds the tag parameter to allow for running from the main branch.
1.6.0
> Parametrized release

- .github/workflows/release.yml
This PR fixes the fix for the fix of the GPG signing. No, really. :)
1.6.0
> Fixed fix for fix of GPG

- website/docs/intro/migration.mdx
This PR adds the migration guide.
Resolves #908
1.6.0
> Fixes #908: Migration guide

- .github/pull_request_template.md
> Update the PR tempate to the next major version

- website/data/language-nav-data.json
Small fix related to #800
1.7.0
> Fix alpha ordering of functions

- CHANGELOG.md
> Add changelog from #579 and expand upon it

- CHANGELOG.md
> Update CHANGELOG for #632

- .goreleaser.yaml
> Backport #1064 to 1.6

- website/docs/intro/migration.mdx
Does what it says on the tin.
1.6.1
1.7.0
> Fix broken link on migration page to the CLI install page.

- website/docs/intro/install/alpine-convenience.sh
- website/docs/intro/install/deb-convenience.sh
- website/docs/intro/install/rpm-convenience.sh
- website/docs/intro/install/standalone-install.sh
Signed-off-by: Patrick Decat <pdecat@gmail.com>
> docs: fix wget https://get.opentofu.org command

- website/docs/intro/install/alpine-convenience.sh
- website/docs/intro/install/deb-convenience.sh
- website/docs/intro/install/rpm-convenience.sh
- website/docs/intro/install/standalone-install.sh
> docs: fix wget https://get.opentofu.org command (#1095)

- website/docs/cli/commands/test/examples/test.sh
- website/docs/cli/commands/version.mdx
Updates references to versions over to 1.6.0
Resolves #1081
1.6.0
> Update references of tofu version to 1.6.0 ready for release

- website/docs/cli/commands/test/index.mdx
This is a backport of #1110 
1.6.0
> Backporting #1110

- CHANGELOG.md
- internal/tofu/context_plan2_test.go
- internal/tofu/eval_import.go
- internal/tofu/node_resource_abstract.go
- internal/tofu/testdata/import-id-reference/main.tf
- internal/tofu/testdata/import-id-reference/mod/mod.tf
- internal/tofu/transform_reference.go
> Allow known references in import blocks (#1105)

- CHANGELOG.md
- internal/command/meta_vars.go
- internal/command/test.go
- internal/command/test_test.go
- internal/command/testdata/test/variables_reference/main.tftest.hcl
- internal/command/testdata/test/variables_reference/setup/main.tf
> #1129 backport

- CHANGELOG.md
Add changelog entry for Global Schema Cache fix in provider acceptance tests - https://github.com/opentofu/opentofu/pull/1054
Related to https://github.com/opentofu/opentofu/issues/1044
1.6.1
> Add Global Schema Cache fix to CHANGELOG.md

- internal/command/show.go
- internal/command/state_show.go
- internal/tofumigrate/tofumigrate.go
- internal/tofumigrate/tofumigrate_test.go
Migrates the schema in-memory prior to running the aforementioned commands.
Resolves #1139 
1.6.1
1.7.0
> Fix running `tofu show` and `tofu state show` with state files that reference Terraform registry providers.

- CHANGELOG.md
> Add changelog entry for #1141

- website/docs/cli/plugins/signing.mdx
Pulled the relevant pieces from the docs and reworded slightly to fit the website layout.
Resolves #967
1.6.1, 1.7.0
> Add Environment Variables to plugin signing page

- website/docs/cli/plugins/signing.mdx
> Backport: Add Environment Variables to plugin signing page (#1159)

- CHANGELOG.md
- internal/legacy/helper/hashcode/hashcode.go
- internal/legacy/helper/schema/field_reader_config_test.go
- internal/legacy/helper/schema/resource_data_test.go
- internal/legacy/helper/schema/resource_diff_test.go
- internal/legacy/tofu/state_upgrade_v2_to_v3.go
> Backport #1154 to 1.6 (#1154)

- TSC_SUMMARY.md
> Fix typo in TSC_SUMMARY.md

- go.mod
- go.sum
- internal/lang/funcs/filesystem.go
Change to github.com/bmatcuk/doublestar/v4 as v1 is not being updated since 2020.
Resolves #1193 
1.7.0
> Update to latest github.com/bmatcuk/doublestar

- internal/backend/remote-state/s3/backend.go
- internal/command/jsonplan/plan_test.go
> Backport of Resolve more inconsistencies in 32-bit systems (#1214)

- TSC_SUMMARY.md
Please see notes for two TSC sessions:
- 2024-01-22 (async);
- 2024-01-30 (sync)
Resolves #
> Update TSC notes

- .github/workflows/checks.yml
- internal/httpclient/client_test.go
- internal/httpclient/useragent_test.go
> issue 966: different user agent for unit tests

- CHANGELOG.md
- internal/command/meta_vars.go
- internal/command/test.go
- internal/command/test_test.go
- internal/command/testdata/test/pass_with_local_variable/main.tf
- internal/command/testdata/test/pass_with_local_variable/tests/test.tftest.hcl
- internal/command/testdata/test/pass_with_local_variable/tests/testmodule/main.tf
Resolves #1212 
Backporting #1254 
1.6.2
> Backports: Problem referencing output from test run in local variables block (#1254)

- internal/lang/funcs/descriptions.go
- internal/lang/funcs/encoding.go
- internal/lang/funcs/encoding_test.go
- internal/lang/functions.go
- internal/lang/functions_test.go
- website/data/language-nav-data.json
- website/docs/language/functions/urldecode.mdx
> Feat: urldecode function #1234

- internal/addrs/module_source_test.go
In windows machine, some the adb path have different style
Fix abs module path and the expected data to pass tests on windows
test:
```
-> % TF_ACC=1 go test ./internal/addrs
ok      github.com/opentofu/opentofu/internal/addrs     0.665s
```
Part of https://github.com/opentofu/opentofu/issues/1201
> Fix: unit test of package internal/addr for windows #1281

- TSC_SUMMARY.md
Notes from recent TSC meeting.
> Add TSC meeting notes from 2024-02-27

- website/docs/cli/private_registry/index.mdx
> issue 1206: add documentation for private registry

- WEEKLY_UPDATES.md
> Weekly update (2024-03-07)

- internal/encryption/base.go
- internal/encryption/keyprovider.go
- internal/encryption/keyprovider/keyprovider.go
- internal/encryption/keyprovider/output.go
- internal/encryption/keyprovider/static/config.go
- internal/encryption/keyprovider/static/provider.go
- internal/encryption/keyprovider/static/provider_test.go
- internal/encryption/targets.go
- internal/varhcl/vardecode.go
Developed while working on the aws_kms provider in collaboration with @janosdebugs 
Related to #1349
1.7.0
> Update to encryption key provider interface

- CHANGELOG.md
> Added urldecode to changelog, bumped all new functions together in the changelog

- internal/builtin/provisioners/local-exec/resource_provisioner_test.go
unit test of package internal/builtin for windows
Resolves #1281
1.7.0
> fix: unit test of package internal/builtin for windows #1281

- docs/state_encryption.md
- internal/encryption/README.md
- internal/encryption/method/README.md
- internal/encryption/method/config.go
- internal/encryption/method/descriptor.go
- internal/encryption/method/method.go
- website/docs/language/state/encryption.mdx
- website/docs/language/state/examples/encryption/configuration.ps1
- website/docs/language/state/examples/encryption/configuration.sh
- website/docs/language/state/examples/encryption/configuration.tf
- website/docs/language/state/examples/encryption/enforce.tf
- website/docs/language/state/examples/encryption/fallback.tf
- website/docs/language/state/examples/encryption/fallback_from_unencrypted.tf
- website/docs/language/state/examples/encryption/fallback_to_unencrypted.tf
- website/docs/language/state/examples/encryption/terraform_remote_state.tf
This PR adds missing documentation pieces for 1.7.0-alpha1.
1.7.0
> Documentation updates for 1.7.0-alpha1 (state encryption)

- website/docs/language/state/encryption.mdx
- website/docs/language/state/examples/encryption/aws_kms.tf
> Adding AWS KMS documentation

- website/docs/language/state/encryption.mdx
> Fixed aesthetic issue for AWS KMS

- cmd/tofu/telemetry.go
> Update Service name used in experimental telemetry

- website/docs/intro/install/standalone.mdx
Syntax cleanup and fix link to email address
See: https://github.com/opentofu/opentofu/issues/1415
1.7.0
> docs: Add mailto prefix for email address

- WEEKLY_UPDATES.md
> Weekly update for 2024-03-27

- go.mod
- go.sum
> upgrade go cty to v1.14.4

- cmd/tofu/main.go
- internal/backend/local/backend_plan_test.go
- internal/checks/state.go
- internal/command/e2etest/automation_test.go
- internal/command/jsonplan/plan.go
- internal/command/meta_backend_migrate.go
- internal/registry/test/mock_registry.go
> chore: fix repetitive words

- website/docs/cli/commands/get.mdx
- website/docs/cli/commands/init.mdx
add -json flag doc for init and get command
related to #1373 
worked
1.7.0
> doc: add -json flag doc for init and get command

- internal/modsdir/manifest.go
close manifest file
Resolves #
1.7.0
> fix: close manifest file

- internal/command/e2etest/encryption_test.go
- internal/command/e2etest/testdata/encryption-flow/migratefrom.tf.disabled
- internal/command/e2etest/testdata/encryption-flow/migrateto.tf.disabled
- internal/encryption/base.go
- internal/encryption/default_registry.go
- internal/encryption/enctest/setup.go
- internal/encryption/method/unencrypted/method.go
- internal/encryption/methods.go
- internal/encryption/targets.go
- website/docs/language/state/encryption.mdx
- website/docs/language/state/examples/encryption/fallback_from_unencrypted.tf
- website/docs/language/state/examples/encryption/fallback_to_unencrypted.tf
> Add unencrypted Method for migrations

- .github/scripts/update_top_issues_ranking/go.mod
- .github/scripts/update_top_issues_ranking/go.sum
As in the title, I didn't commit the go.sum file.
> Fix issue ranking script - commit go.sum

- .github/ISSUE_TEMPLATE/1_7_0_beta1_feedback.yml
> 1.7.0 beta1 feedback form

- website/docs/language/functions/index.mdx
> Update provider functions documentation

- internal/command/e2etest/provider_functions_test.go
- internal/command/e2etest/testdata/functions-error/main.tf
- internal/command/e2etest/testdata/functions/main.tf
This implements a more direct version of #1389 
Follow up to #1439 
1.7.0
> Provider Defined Functions direct e2e test

- .github/workflows/checks.yml
Here is a run of this action in my fork: https://github.com/IgnorantSapient/opentofu/actions/runs/7673240823/job/20915441788?pr=1
Added test matrix for various OSes and Architectures on pull request
Resolves #1135
> Run unit tests on various OSes and Architectures on pull request

- website/docs/index.mdx
- website/docs/intro/install/index.mdx
- website/docs/language/syntax/json.mdx
(cherry picked from commit 59e021573580ea3b6359c951aea24eeb96d584a6)
1.7.0
> Backport: Missed links #1543

- internal/tofu/context.go
- internal/tofu/context_plugins.go
- internal/tofu/context_plugins_test.go
- internal/tofu/eval_context_builtin_test.go
- internal/tofu/graph_builder_apply_test.go
- internal/tofu/graph_builder_plan_test.go
- internal/tofu/schemas_test.go
> Cleanup ContextPlugins after function changes

- internal/command/e2etest/test_test.go
> Fix e2e test_test on darwin amd64

- website/Dockerfile
- website/docker-compose.build.yml
- website/docker-compose.yml
> Backports[v1.6] Fixing website build after versioned docs upgrade

- website/docs/language/expressions/function-calls.mdx
> [backport] Rewrite outdated doc of function call with sensitive data (#1486)

- website/docs/intro/migration/terraform-1.5-or-lower.mdx
- website/docs/intro/migration/terraform-1.6.mdx
> Backport[v1.6] Fixing missed upgrade links

- website/docs/language/functions/textdecodebase64.mdx
- website/docs/language/functions/textencodebase64.mdx
Fix function name in description for `textencodebase64`, and add a signature function for `textdecodebase64`
1.8.0
> Update textencodebase64 and textdecodebase64 documentation

- internal/command/e2etest/test_test.go
> Fix e2e test_test on darwin amd64 (#1551) - Backport to 1.7

- website/docs/language/functions/textdecodebase64.mdx
- website/docs/language/functions/textencodebase64.mdx
Backport for https://github.com/opentofu/opentofu/pull/1623
Cherry picked https://github.com/opentofu/opentofu/commit/3e568a26008d74b4795ab02a28ea15249dd8b04c
> Backport[v1.6] Update textencodebase64 and textdecodebase64 documentation

- .github/pull_request_template.md
Fixes a typo from https://github.com/opentofu/opentofu/pull/1423 (see below, Go checklist section)
1.8.0
<-- If your PR contains Go code, please make sure you check off all items on this list: -->
> fix PR template typo

- TSC_SUMMARY.md
- Added last TSC meeting summary
- Tracked through older meeting minutes that were not posted and added their summaries here - TSC members who take notes will now post these regularly
> Add Technical Steering Committee missing Summarries through 2024 May

- WEEKLY_UPDATES.md
> Weekly Update for 2024-05-17

- internal/backend/remote-state/http/backend.go
- internal/backend/remote-state/http/backend_test.go
Resolves #1656
1.8.0
- [ x ] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [ x ] I have not used an AI coding assistant to create this PR.
- [ x ] I have marked any code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from. 
- [ x ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ x ] I have run existing tests to ensure my code doesn't break anything.
- [ x ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ x ] I have only exported functions, variables and structs that should be used from other packages.
- [ x ] I have added meaningful comments to all exported …
> ensure authorization header is included for http backends

- CHANGELOG.md
> Add missing changelog for #1647

- website/docs/intro/migration/terraform-1.5-or-lower.mdx
- website/docs/intro/migration/terraform-1.6.mdx
- website/docs/intro/migration/terraform-1.7.mdx
- website/docs/intro/migration/terraform-1.8.mdx
- website/docs/intro/upgrading.mdx
> docs: fix slack broken link

- internal/configs/hcl2shim/util.go
- internal/configs/hcl2shim/util_test.go
- internal/configs/import.go
- internal/configs/resource.go
- internal/tofu/context_plan2_test.go
This is a backport of #1665.
Resolves #1652
1.7.2
> Backport[V1.7] #1665: Fix bug in import 'to' parsing in json configurations

- CHANGELOG.md
> Add 1.7.2 to the CHANGELOG.md

- CHANGELOG.md
- internal/command/e2etest/testdata/functions/main.tf
- internal/lang/eval.go
- internal/lang/references.go
- internal/tofu/eval_variable.go
- internal/tofu/node_module_variable.go
- internal/tofu/node_root_variable.go
- internal/tofu/transform_destroy_edge.go
> Provider functions in variable validations (#1689)

- website/docs/intro/install/buildkite.jsx
- website/docs/intro/migration/terraform-1.5-or-lower.mdx
- website/docs/intro/migration/terraform-1.6.mdx
- website/docs/intro/migration/terraform-1.7.mdx
- website/docs/intro/migration/terraform-1.8.mdx
- website/docs/intro/upgrading.mdx
Resolves #1563
https://github.com/opentofu/opentofu/assets/32186630/bd808402-407b-4b8c-afea-4a84b8b837af
1.8.0
> fix: slack link and `BuildKite` component

- website/docs/cli/commands/test/examples/override_module/bucket_meta/main.tf
- website/docs/cli/commands/test/examples/override_module/main.tf
- website/docs/cli/commands/test/examples/override_module/main.tftest.hcl
- website/docs/cli/commands/test/examples/override_resource/main.tf
- website/docs/cli/commands/test/examples/override_resource/main.tftest.hcl
- website/docs/cli/commands/test/index.mdx
This is part of #1499 PR and #1204 issue. It's separated just to make it easier to review the doc separately. The base branch is `override-for-testing` so it will be merged into the `main` branch later as a full-packed feature.
1.8.0
> add docs for override feature

- website/docs/intro/install/examples/verify-installation.sh
- website/docs/intro/install/homebrew.mdx
> [Documentation] Add script to verify OpenTofu installation

- internal/states/statemgr/filesystem_test.go
Helps resolve #1201  
1.8.0
- [/ ] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [/ ] I have not used an AI coding assistant to create this PR.
- [/ ] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
This test was failing with `TempDir Removeall Cleanup` error. After splitting up `WriteAndPersist` into `Write` and `Persist` separately I found that this error occured when Persisting the state. There was no obvious solution when reading the Persist state function so I looked elsewhere. I then tried this: 
1. writing the state
2. locking the filesystem
3. persisting the …
> fix internal/states unit tests Windows

- rfc/20230905-provider-gpgkey-missing.md
- rfc/20231017-homebrew-like-registry-design.md
- rfc/20231106-registry-repository-folder-structure.md
- rfc/20231107-registry-gpg-key-verification.md
- rfc/20231108-registry-automatic-version-bumping.md
- rfc/20231109-registry-response-generation.md
- rfc/20231114-client-side-state-encryption.md
- rfc/20231123-registry-submission-via-github-issues.md
This is a rough translation to capture the history of the project.  Only a slight attempt was made to translate the original RFCs into the modern format.
As this turns github issues into MPL files in the repository, it will require sign-off from:
> Backfill accepted RFCs into new location

- WEEKLY_UPDATES.md
> Weekly Update

- rfc/20240529-OpenTofu-Specific-Code-Override.md
Based on this [RFC](https://github.com/opentofu/opentofu/issues/1328) but using our new RFC process.
1.8.0
> RFC: OpenTofu Specific Code Override

- website/docs/intro/install/docker.mdx
- website/docs/intro/install/examples/docker-run.sh
Update 'Usage' topic including a tutorial to run your first 'init' command via Docker.
Resolves #1556
1.8.0
> docs: update 'Use OpenTofu as Docker Image' documentation

- CHANGELOG.md
- internal/command/e2etest/testdata/encryption-flow/broken.tf.disabled
- internal/command/meta_encryption.go
- internal/configs/module.go
- internal/configs/parser_config_dir_test.go
- internal/configs/static_evaluator.go
- internal/encryption/base.go
- internal/encryption/config/config.go
- internal/encryption/encryption.go
- internal/encryption/enctest/setup.go
- internal/encryption/example_test.go
- internal/encryption/keyprovider.go
- internal/encryption/keyprovider/static/example_test.go
- internal/encryption/plan.go
- internal/encryption/state.go
- internal/encryption/targets.go
- internal/encryption/targets_test.go
- internal/lang/eval.go
- internal/lang/eval_test.go
- website/docs/language/state/examples/encryption/fallback_from_unencrypted.tf
- website/docs/language/state/examples/encryption/sample.tf
Resolves #1538.
This PR is waiting on https://github.com/opentofu/opentofu/pull/1718 to be merged.
1.8.0
> allow static evaluations in encryption configuration

- internal/lang/eval.go
This PR refactors Scope.evalContext to simplify it and meet the required linting criteria.
Part of work in https://github.com/opentofu/opentofu/pull/1728 that resolved https://github.com/opentofu/opentofu/issues/1538. 
1.8.0
> refactor Scope.evalContext to meet linting criteria

- internal/states/statefile/version4.go
> chore: update version4.go

- internal/command/jsonprovider/function.go
- internal/command/jsonprovider/function_test.go
- internal/command/jsonprovider/provider.go
- internal/command/jsonprovider/provider_test.go
- internal/command/providers_schema_test.go
- internal/command/testdata/providers-schema/basic/output.json
- internal/command/testdata/providers-schema/required/output.json
Resolves # https://github.com/opentofu/opentofu/issues/1700
1.8.0
> Adds provider function to tofu scheme/metadata commands

- .github/workflows/release.yml
- .goreleaser.yaml
This PR backports the recent release workflow changes to the 1.6 branch.
1.6
> Backporting release workflow changes to 1.6

- internal/tofu/context_plan2_test.go
- internal/tofu/eval_provider.go
- internal/tofu/testdata/insufficient-features-blocks-aliased-provider/main.tf
- internal/tofu/testdata/insufficient-features-blocks-nested_module/main.tf
- internal/tofu/testdata/insufficient-features-blocks-nested_module/nested/main.tf
- internal/tofu/testdata/insufficient-features-blocks-no-feats/main.tf
Resolves # [1484](https://github.com/opentofu/opentofu/issues/1484)
Adds provider details to the "insufficient blocks" error to help users find the offending provider.
Adds tests for the scenarios explained in the issue
1.9.0
> Adds source context for the 'insufficient feature blocks' error

- CHANGELOG.md
> Adding changelog header for 1.6.3

- CHANGELOG.md
This PR adds a changelog section for 1.7.3
1.7.3
> Adding 1.7.3 changelog as released

- internal/command/fmt.go
- internal/command/fmt_test.go
Follow up to https://github.com/opentofu/opentofu/pull/1738
1.8.0
> Include .tofu in `tofu fmt`

- internal/command/autocomplete.go
Quick fix for an issue discovered by @RLRabinowitz.
1.8.0
> Remove encryption diags from autocomplete

- internal/command/arguments/validate.go
- internal/command/arguments/validate_test.go
- internal/command/e2etest/encryption_test.go
- internal/command/e2etest/static_plan_test.go
- internal/command/get.go
- internal/command/graph.go
- internal/command/graph_test.go
- internal/command/providers_schema.go
- internal/command/state_show.go
- internal/command/validate.go
Missed during my original PR, added explicit test case.
1.8.0
> Fix `tofu validate` with static variables

- internal/command/e2etest/static_plan_test.go
- internal/command/get.go
- internal/command/graph.go
- internal/command/init.go
- internal/command/output.go
- internal/command/providers.go
- internal/command/providers_lock.go
- internal/command/providers_mirror.go
- internal/command/providers_schema.go
- internal/command/show.go
- internal/command/state_list.go
- internal/command/state_mv.go
- internal/command/state_pull.go
- internal/command/state_push.go
- internal/command/state_replace_provider.go
- internal/command/state_rm.go
- internal/command/state_show.go
- internal/command/taint.go
- internal/command/test.go
- internal/command/unlock.go
- internal/command/untaint.go
- internal/command/validate.go
- internal/command/workspace_delete.go
- internal/command/workspace_list.go
- internal/command/workspace_new.go
- internal/command/workspace_select.go
This is a followup to the static evaluation work #1718 #1771 and  #1788
> Update help text for static variable support

- rfc/README.md
> Fix RFC template link

- .github/workflows/backport.yml
> More backport fixes

- WEEKLY_UPDATES.md
> Weekly update 2024-07-18

- website/docs/cli/auth/index.mdx
- website/docs/cli/index.mdx
- website/docs/intro/core-workflow.mdx
- website/docs/intro/tacos.mdx
- website/docs/language/checks/index.mdx
- website/docs/language/files/index.mdx
- website/docs/language/index.mdx
- website/docs/language/modules/index.mdx
- website/docs/language/modules/sources.mdx
- website/docs/language/modules/syntax.mdx
- website/docs/language/providers/index.mdx
- website/docs/language/providers/requirements.mdx
- website/docs/language/settings/backends/configuration.mdx
- website/docs/language/settings/backends/remote.mdx
- website/docs/language/state/index.mdx
- website/docs/language/state/remote.mdx
Resolves  https://github.com/opentofu/opentofu/issues/1666
1.9.0
> Adds TACOS page to docs and links to it from all mentionds of TACOS

- internal/command/providers_schema.go
- internal/command/unlock.go
- internal/command/workspace_delete.go
- internal/command/workspace_list.go
- internal/command/workspace_select.go
> Add missing [options] to help text where applicable

- website/docs/language/modules/sources.mdx
- website/docs/language/modules/syntax.mdx
> Fixes some of the links for the TACOS docs

- .github/workflows/release.yml
In #1867, I missed part of @cube2222's changes which caused some confusion during the release process.
> Fix 1.8 release workers

- website/docs/language/settings/backends/remote.mdx
It is confusing to read about the `remote` backend when other backends are often called remote state backends. Hopefully, this PR helps reader to be less confused.
1.9.0
> add clarification on remote vs remote state backends

- TSC_SUMMARY.md
> [TSC] summary for the 2024-06-04 and 2024-05-21 TSC meetings

- website/docs/cli/auth/index.mdx
- website/docs/cli/index.mdx
- website/docs/intro/core-workflow.mdx
- website/docs/intro/tacos.mdx
- website/docs/language/checks/index.mdx
- website/docs/language/files/index.mdx
- website/docs/language/index.mdx
- website/docs/language/modules/index.mdx
- website/docs/language/modules/sources.mdx
- website/docs/language/modules/syntax.mdx
- website/docs/language/providers/index.mdx
- website/docs/language/providers/requirements.mdx
- website/docs/language/settings/backends/configuration.mdx
- website/docs/language/settings/backends/remote.mdx
- website/docs/language/state/index.mdx
- website/docs/language/state/remote.mdx
Resolves #1666
Backport PR to bring docs updates to 1.8 branch
1.8.0
> 1666/tacos website docs backport to 1.8

- website/docs/intro/upgrading.mdx
Related to https://github.com/opentofu/opentofu/issues/1873
Docs don't mention that it is required to run `tofu init -reconfigure` when upgrading to OpenTofu 1.8.0, if using an S3 backend
1.9.0
> Docs: Update 1.8.0 upgrade docs, when S3 bucket is used

- CHANGELOG.md
- internal/configs/config_build.go
> Fix missing module source panic (#1888)

- internal/tfdiags/consolidate_warnings_test.go
To add some unit test to #1894
1.9.0
> add consolidate error test

- rfc/20240725-exclude-resources.md
An RFC detailing how an `-exclude` flag would work in OpenTofu, for planning and applying resources
Many thanks @jamesBalazs for your work on the PoC and RFC for this feature!
Resolves https://github.com/opentofu/opentofu/issues/426
1.9.0
> RFC: `-exclude` flag for planning and applying

- WEEKLY_UPDATES.md
The weekly update for 09.08.24
> 09.08.24 Weekly Update

- website/docs/intro/tacos.mdx
- website/docs/language/expressions/references.mdx
- website/docs/language/providers/requirements.mdx
- website/docs/language/settings/backends/oss.mdx
- website/docs/language/settings/index.mdx
> Fix Docusaurus "broken link" warnings on 1.8 branch of docs (#1884)

- website/docs/cli/cloud/migrating.mdx
- website/docs/language/settings/index.mdx
Pulled in from https://github.com/mehhhhhhhhhhhhhhh/opentofu/commit/dc4bade7a43753e1034c9e0787c3535a3653bace
Related to #1884
1.7.0
> Backport 1884 v1.7 (part 2)

- website/docs/intro/install/standalone.mdx
- website/docs/language/expressions/references.mdx
- website/docs/language/providers/requirements.mdx
- website/docs/language/settings/backends/oss.mdx
- website/docs/language/settings/backends/remote.mdx
- website/docs/language/settings/index.mdx
- website/docs/language/settings/tf-cloud.mdx
- website/docs/language/state/remote-state-data.mdx
- website/docs/language/values/variables.mdx
> Backport 1884 v1.6

- website/docs/cli/cloud/migrating.mdx
- website/docs/language/settings/index.mdx
Pulled in from https://github.com/mehhhhhhhhhhhhhhh/opentofu/commit/dc4bade7a43753e1034c9e0787c3535a3653bace
Related to https://github.com/opentofu/opentofu/pull/1884
Related to https://github.com/opentofu/opentofu/issues/1863
Duplicate of #1915 (`v1.7`)
1.7.0
> Backport 1884 v1.6 (part 2)

- TSC_SUMMARY.md
> [TSC] summaries for June and July TSC meetings

- internal/cloud/backend.go
- internal/cloud/backend_test.go
- internal/cloud/errors.go
- website/docs/cli/cloud/settings.mdx
> Cloud Backend - Fix logic that forces TF_WORKSPACE to be equal to a tag name

- README.md
- TSC_SUMMARY.md
> [TSC] summary for TSC meetings in August

- internal/encryption/keyprovider.go
- internal/encryption/targets_test.go
> Better handling of key_provider references (#1921)

- internal/configs/resource.go
In this PR I added back the previous way of referencing a provider: https://github.com/opentofu/opentofu/blob/ea558d9d4b5ef4919356aabc8f3bc3d23af1d853/internal/configs/resource.go#L719
1.9.0
> #300 fix referencing provider by its addr

- internal/configs/module_call.go
- internal/configs/resource.go
This PR makes it possible to use count.index expression when referencing a provider.
1.9.0
> #300 add support for count in provider refs

- website/docs/language/import/index.mdx
> fix typo in import docs

- internal/command/jsonconfig/config.go
- internal/configs/config.go
- internal/configs/module.go
- internal/configs/module_call.go
- internal/configs/provider_validation.go
- internal/configs/resource.go
- internal/tofu/context_input.go
- internal/tofu/evaluate_valid.go
- internal/tofu/node_resource_abstract.go
- internal/tofu/transform_provider.go
This PR is based on https://github.com/opentofu/opentofu/pull/1959 and aimed at resolving hacks from the first commits (for example, InParentTODO calls).
Some of the fixes await the latest changes from graph execution work by @Evi1Pumpkin. So it will be done in a separate PR after the merge.
1.9.0
> #300: fix some hacks from the first commits

- website/docs/index.mdx
Fixed the issue identified  in #1909
1.9.0, 1.8.0
> Update docs version message

- website/docs/index.mdx
> Update docs version message (#1990)

- website/docs/intro/migration/terraform-1.8.mdx
Resolves # 
https://github.com/opentofu/opentofu/issues/1981
1.8.3
> Fix Terraform Version in 1.8.x Migration Guide

- website/docs/intro/migration/terraform-1.8.mdx
> Fix Terraform Version in 1.8.x Migration Guide (#1987)

- internal/registry/client.go
https://gist.github.com/arunim2405/93d536ad37ad481a49c8c68a3dcc5337
Resolves #1988
1.9.0
> Fix debug logging doesn't show module name

- .golangci.yml
- internal/configs/resource.go
Reduced code duplication, separation of concerns between iteration values and alias calculation
1.9.0
> Refactor alias evaluation

- .golangci.yml
- internal/configs/config_test.go
- internal/configs/module.go
- internal/configs/module_call_test.go
- internal/configs/module_merge_test.go
- internal/configs/provider_validation.go
- internal/configs/resource.go
In this PR I aim to fix all the tests for provider iteration stuff.
1.9.0
> #300: fix tests and linting

- internal/configs/config_test.go
- internal/configs/static_evaluator_test.go
- internal/configs/testdata/provider-references/main.tf
- internal/configs/testdata/provider-references/modules.tf
- internal/configs/testdata/provider-references/resources.tf
- internal/configs/testdata/provider-references/submod/main.tf
This PR adds relevant tests for provider reference parsing in resource and module calls.
1.9.0
> add tests for provider reference parsing

- Makefile
> Add a test target in Makefile to run tests across all packages

- Makefile
- The target runs the tests and generates a coverage profile saved to coverage.out
- It uses the "go tool cover" and converts the coverage profile into an HTML report and saves it as coverage.html
Resolves # 
1.9.0
> Add the test-with-coverage makefile target.

- internal/command/get_test.go
This commit enhances the Get Command tests introducing the TestGetCommand_InvalidArgs function  to cover different scenarios of invalid arguments for the GetCommand.
The following test cases have been added:to the get_test.go file:
- TooManyArgs: Tests the behavior when too many command-line arguments are provided, expecting the error "Too many command line arguments".
- InvalidArgFormat: Tests the behavior when an invalid or unrecognized command-line argument is provided, expecting the error "flag provided but not defined".
- MixedValidAndInvalidArgs: Tests the behavior when a mix of valid and invalid command-line arguments is provided, expecting the error "flag provided but not defined".
These test cases aim to ensure that the application handles various scenarios of invalid or …
> Add test cases for GetCommand to cover invalid args scenarios

- Makefile
The command now matches the CI task
1.9.0
> Update lint make target to match CI

- CHANGELOG.md
- internal/command/meta_vars.go
- internal/command/test.go
Also fixed that the test directory is respected when loading test vars
Resolves #1386
1.9.0, 1.8.3, 1.7.4
> Make sure test vars are only processed during test commands

- TSC_SUMMARY.md
> feat: Adding 2024-10-09 TSC summary

- TSC_SUMMARY.md
> [TSC] summary for the 2024-10-15 TSC meeting

- .golangci.yml
- CHANGELOG.md
- internal/genconfig/generate_config.go
- internal/genconfig/generate_config_test.go
- internal/registry/client.go
- internal/tofu/context_validate_test.go
- internal/tofu/node_module_variable.go
- internal/tofu/transform_provider.go
Backports the following PRs:
- #2052 #1986 #2077 #2079
1.8.x
> Backport recent changes to v1.8

- CHANGELOG.md
- internal/genconfig/generate_config.go
- internal/genconfig/generate_config_test.go
- internal/registry/client.go
- internal/tofu/context_validate_test.go
- internal/tofu/node_module_variable.go
- internal/tofu/transform_provider.go
https://github.com/opentofu/opentofu/pull/2093
1.7.4
> 1.8 to 1.7 backport

- CHANGELOG.md
> add some missing changelog entries

- CHANGELOG.md
- internal/plugin/grpc_provider.go
- internal/plugin6/grpc_provider.go
- internal/providers/provider.go
> Partially unknown provider functions arguments fixed (#2127)

- CHANGELOG.md
- internal/plugin/grpc_provider.go
- internal/plugin6/grpc_provider.go
- internal/providers/provider.go
> Partially unknown provider functions arguments fixed (#2127) (#2133)

- website/docs/cli/commands/test/index.mdx
> fix documentation typo in mock provider link

- internal/tofu/node_provider.go
- internal/tofu/node_resource_abstract_instance.go
- internal/tofu/node_resource_import.go
Feedback received: https://github.com/opentofu/opentofu/issues/300#issuecomment-2462533054
Part of #300 
1.9.0
> Improve log messages for providers with keys

- internal/backend/remote-state/http/client.go
- internal/backend/remote-state/http/client_test.go
Resolves # Bug 2004 https://github.com/opentofu/opentofu/issues/2004
1.9.0, if possible back port
> "http" backend to return existing lock metadata on lock conflict, rather than new lock metadata

- website/Dockerfile
> [BACKPORT] pin node version for docusaurus build (#2177)

- internal/backend/remote-state/http/client.go
- internal/backend/remote-state/http/helper.go
- internal/backend/remote-state/http/helper_test.go
Backport of https://github.com/opentofu/opentofu/pull/2120 to fix https://github.com/opentofu/opentofu/issues/2003
> [BACKPORT] Add DEBUG-level logging to the "http" state storage backend (#2120)

- CHANGELOG.md
- internal/command/test_test.go
- internal/command/testdata/test/mock_provider_validation/main.tf
- internal/command/testdata/test/mock_provider_validation/main.tftest.hcl
- internal/tofu/provider_for_test_framework.go
Backport of https://github.com/opentofu/opentofu/pull/2140 to fix https://github.com/opentofu/opentofu/issues/2038 and https://github.com/opentofu/opentofu/issues/2139
> [BACKPORT] fix mock provider validation (#2140)

- CHANGELOG.md
- internal/configs/hcl2shim/mock_value_composer.go
- internal/configs/hcl2shim/mock_value_composer_test.go
Backport for #2144, related to #2008, #2139 and #1837
> [BACKPORT] fix mock type conversion in tofu test (#2144)

- CHANGELOG.md
> [BACKPORT] add missing changelog entry for http backend logging (#2206)

- CONTRIBUTING.RELEASE.md
This PR adds a release guide to document the steps for preparing a release.
[Preview link](https://github.com/opentofu/opentofu/blob/release-guide/CONTRIBUTING.RELEASE.md)
> Creating a release manual

- CONTRIBUTING.RELEASE.md
**[Preview link](https://github.com/opentofu/opentofu/blob/release-docs-website/CONTRIBUTING.RELEASE.md)**
N/A
> Adding website updates to the release docs

- internal/dag/walk.go
When a vertex is waiting on its dependencies, it blocks on those deps, but it also wakes up every 5 seconds in order to log what it's waiting for. Those logs are immediately discarded unless TRACE logs are enabled.
This is similar to https://github.com/opentofu/opentofu/pull/1810
I've pulled out the timer creation into a separate function which only conditionally creates the timer if debugging logs are enabled. This allows us to avoid creating/selecting on timers at all, which takes up 90% of the waitDeps on-CPU time (and puts additional pressure on the scheduler).
Grabbed some screenshots of perf difference against our (somewhat pathological) workload:
Profiling before (3.6s):
Profiling after (318ms):
1.9.0
> Only wake up from waitDeps to trace when debugging

- website/docs/intro/migration/index.mdx
This PR fixes the website build for v1.7 and the production multi-versioned build as well ([failing check on main](https://github.com/opentofu/opentofu/actions/runs/12121584839/job/33792834657)). In order to fix the check, we need to also bump sub repo in [opentofu.org](https://github.com/opentofu/opentofu.org).
> fix broken link for v1.7 docs

- CHANGELOG.md
- internal/encryption/base.go
- internal/encryption/example_test.go
- internal/encryption/plan.go
- internal/encryption/state.go
- internal/plans/planfile/planfile_test.go
- internal/states/remote/state.go
- internal/states/statefile/file.go
- internal/states/statefile/read.go
- internal/states/statefile/roundtrip_test.go
> [backport v1.7] Force state change if encryption used fallback

- CHANGELOG.md
- internal/encryption/base.go
- internal/encryption/example_test.go
- internal/encryption/plan.go
- internal/encryption/state.go
- internal/plans/planfile/planfile_test.go
- internal/states/remote/state.go
- internal/states/statefile/file.go
- internal/states/statefile/read.go
- internal/states/statefile/roundtrip_test.go
> [backport v1.8] Force state change if encryption used fallback

- website/docs/intro/migration/index.mdx
- website/docs/intro/migration/terraform-1.9.mdx
This PR changes the order of tabs and adds tf 9 button to migration page.
1.9.0
> fix tf migration buttons in docs

- CHANGELOG.md
- internal/configs/hcl2shim/mock_value_composer.go
- internal/configs/hcl2shim/mock_value_composer_test.go
Cherry pick of e5d26f9a713017d794884727bab0325f7d3b4536
1.8.7
> [BACKPORT] make tofu test generate dynamic mock values (#2245)

- CHANGELOG.md
- internal/command/test.go
- internal/command/testdata/test/default_variables/main.tf
- internal/command/testdata/test/default_variables/main.tftest.hcl
Cherry pick of 32ca523689a782e398ade512e8a6ac2c9b6bd288
1.8.7
> [BACKPORT] fix: type defaults for variables in tests (#2244)

- .github/workflows/release.yml
Specifically e2b6b46d430 and large-runners
1.7.x
> Synchronize release pipeline between v1.8 and v1.7

- CHANGELOG.md
- internal/backend/remote-state/azure/arm_client.go
- internal/backend/remote-state/azure/backend.go
- internal/backend/remote-state/azure/backend_state.go
- internal/backend/remote-state/azure/backend_test.go
- internal/backend/remote-state/azure/client.go
- internal/backend/testing.go
- website/docs/language/settings/backends/azurerm.mdx
This pull request adds a `timeout_seconds` configuration variable with a default value to the AzureRM backend. 
After reviewing the implementation, I found no explicit timeout mechanism. The previously discussed 15-minute timeout appears to be the system's default TCP timeout.
I've implemented timeouts using Go contexts. And timeouts apply only to Read type operations, such as:
- Retrieving list of keys (during client initialization)
- Fetching Blob properties
- Retrieving Blobs
The goal is to avoid interfering with state-modifying operations (Put, Delete). Since client initialization and property retrieval occur before state mutations, this approach will likely detect and timeout connection issues before any changes are started.
I've set the default timeout to 300 (5 minutes), which …
> Azurerm backend timeout

- .golangci.yml
- internal/tofu/context_apply2_test.go
- internal/tofu/node_resource_plan_destroy.go
> Fix data provider iteration destroy

- CHANGELOG.md
Forgot to add a changelog entry in #2274
1.9.0
> add missing changelog for #2274

- CHANGELOG.md
- internal/command/test.go
- internal/command/test_test.go
- internal/command/testdata/test/destroyed_mod_outputs/main.tf
- internal/command/testdata/test/destroyed_mod_outputs/main.tftest.hcl
- internal/command/testdata/test/destroyed_mod_outputs/mod/main.tf
Cherry pick of 5f8eee4708d45e7c997fb4d3f3d9ba3cf72eaa1c and an additional commit for a changelog entry.
I am only backporting this change to 1.8 version.
Part of https://github.com/opentofu/opentofu/issues/2260.
1.8.8
> [BACKPORT] add simulated state serialization between tofu test runs (#2274)

- internal/tofu/context_apply2_test.go
- internal/tofu/eval_provider.go
- internal/tofu/node_resource_abstract.go
This was untested and broken in the original implementation.  Tests were added and the corresponding module and resource bugs where fixed.
Resolves #2277
1.9.0
> Local values can now be used in provider key expressions

- internal/configs/configload/loader_snapshot.go
I profiled `tofu show` because it was surprisingly slow. Most of the slowness comes from https://github.com/opentofu/opentofu/issues/2252 but about 25% of the time was spent in filepath.Clean, which was surprising to me.
I noticed that when we call Open() on a file, we iterate over every module. Since we call Open() for every module, this ends up being quadratic in the number of modules, which probably isn't noticeable until you have a few thousand modules (mostly just me, probably).
[Before](https://profiler.firefox.com/public/vf0adrt0wn0vj1mbjzmz04bbhsh4bfak47qj6pr/flame-graph/?globalTrackOrder=0w9&hiddenGlobalTracks=1w9&hiddenLocalTracksByPid=24597-07d~24614-0wa~24615-0wc~24616-0we~24617-0we~24618-0w7~24619-0w6~24620-0w6~24624-0w7~24633-0w7&symbolServer=http%3A%2F%2F127.0.0.1%3A3000%2F0 …
> Fix quadratic buildChildModules

- internal/tofu/context_apply2_test.go
- internal/tofu/context_plan2_test.go
- internal/tofu/node_resource_abstract_instance.go
- internal/tofu/node_resource_apply_instance.go
- internal/tofu/node_resource_deposed.go
- internal/tofu/node_resource_destroy.go
- internal/tofu/node_resource_forget.go
- internal/tofu/node_resource_import.go
- internal/tofu/node_resource_plan_destroy.go
- internal/tofu/node_resource_plan_instance.go
- internal/tofu/node_resource_plan_orphan.go
Cherry-pick of 76d388b34051b2dcf7b21d2d6d15e0c4dcb48734
1.9.0
> [BACKPORT v1.9] fix: provider not initialized in some cases (mostly, deposed) (#2335)

- CONTRIBUTING.RELEASE.md
- website/docs/index.mdx
- website/docs/intro/upgrading.mdx
> 1.9.0 docs cleanup

- website/docs/index.mdx
> Docs index wording fix

- internal/plans/objchange/normalize_obj.go
This is another contribution to our complexity-lint-satisfaction project in https://github.com/opentofu/opentofu/issues/2325.
This function ends with a loop over all of the nested block types that takes different actions depending on the nesting mode.
This change makes the function conform to our complexity linting rules by factoring out the nesting-mode-specific rules into separate functions and making the caller just be a simple dispatch table over the nesting mode.
This quiets all of the lint failures from `normalize_obj.go` in this package, including one non-complexity lint complaining about an unnecessary `else` clause after an `if` statement containing an early return. Otherwise the previous code is preserved as closely as possible to minimize the risk of the change and hopefully to …
> plans/objchange: Decompose normalizeObjectFromLegacySDK a little

- internal/plugin/mock_proto/mock.go
- internal/plugin6/mock_proto/mock.go
Looks like this was missed or a conflict from some recent PRs
1.10.0
> Run make generate protobufs

- website/docs/cli/commands/console.mdx
As discussed in https://github.com/opentofu/opentofu/issues/2282, `tofu console` is not meant to be used in a non-interactive environment. This PR changes the docs to reflect that intention.
1.10.0
> update tofu console docs for non-interactive use-case

- .goreleaser.yaml
- Dockerfile.minimal
- website/docs/intro/install/docker.mdx
> Backport[1.9]: Minimal base image

- website/docs/intro/install/docker.mdx
> Backports[v1.9] #2405: Fix custom docker image instructions by adding gpg-agent package

- internal/backend/remote-state/http/client.go
- internal/backend/remote-state/http/client_test.go
> "force-unlock" support for the HTTP backend

- .github/workflows/checks.yml
See: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
v1.10
v1.9
v1.8
v1.7
> Switch to native Linux/ARM64 runners

- website/docs/language/expressions/version-constraints.mdx
> [backport v1.8] Add example on supporting both OpenTofu and Terraform versions

- website/docs/language/expressions/version-constraints.mdx
> [backport v1.9] Add example on supporting both OpenTofu and Terraform versions

- CHANGELOG.md
- internal/configs/config.go
- internal/configs/config_test.go
- internal/configs/parser_test.go
- internal/configs/testdata/provider-reqs/provider-reqs-root.tf
> [Backport v1.7] Use import provider instead of guess

- CHANGELOG.md
- internal/configs/config.go
- internal/configs/config_test.go
- internal/configs/parser_test.go
- internal/configs/testdata/provider-reqs/provider-reqs-root.tf
> [Backport v1.8] Use import provider instead of guess

- CHANGELOG.md
- internal/lang/funcs/datetime.go
- internal/lang/funcs/datetime_test.go
- internal/tofu/context_validate_test.go
- internal/tofu/testdata/plan_range_over_plan_timestamp/main.tf
> [Backport 1.8] MakeStaticTimestampFunc now returns unknown value if the given time.Time is zero

- CHANGELOG.md
- internal/lang/funcs/datetime.go
- internal/lang/funcs/datetime_test.go
- internal/tofu/context_validate_test.go
- internal/tofu/testdata/plan_range_over_plan_timestamp/main.tf
> [Backport 1.7] MakeStaticTimestampFunc now returns unknown value if the given time.Time is zero

- CHANGELOG.md
- internal/lang/funcs/datetime.go
- internal/lang/funcs/datetime_test.go
- internal/tofu/context_validate_test.go
- internal/tofu/testdata/plan_range_over_plan_timestamp/main.tf
> [Backport 1.9] MakeStaticTimestampFunc now returns unknown value if the given time.Time is zero 

- internal/configs/named_values.go
- internal/configs/parser_config_test.go
- internal/configs/testdata/invalid-files/variable-complex-bad-default-inner-obj.tf
> Fix error message when default value of variable is of wrong type

- CHANGELOG.md
> Add changelog entry for 2394

- CHANGELOG.md
- internal/configs/named_values.go
- internal/configs/parser_config_test.go
- internal/configs/testdata/invalid-files/variable-complex-bad-default-inner-obj.tf
Backport #2444 
Resolves #2394
> [Backport 1.7] Fix error message when default value of variable is of wrong type

- CHANGELOG.md
- internal/configs/named_values.go
- internal/configs/parser_config_test.go
- internal/configs/testdata/invalid-files/variable-complex-bad-default-inner-obj.tf
> [Backport 1.8] Fix error message when default value of variable is of wrong type

- CHANGELOG.md
- internal/configs/named_values.go
- internal/configs/parser_config_test.go
- internal/configs/testdata/invalid-files/variable-complex-bad-default-inner-obj.tf
> [Backport 1.9] Fix error message when default value of variable is of wrong type

- internal/backend/remote-state/s3/client.go
- internal/backend/remote-state/s3/client_test.go
> Improved error messages for lock-related problems in the `s3` backend

- CHANGELOG.md
- internal/addrs/module_source_test.go
- internal/getmodules/getter.go
> Add a new go-getter detector wrapper that can remove the query params before giving the src to the actual detector

- internal/encryption/default_registry.go
- internal/encryption/keyprovider/external/protocol.go
- internal/encryption/keyprovider/external/testprovider/data/testprovider.py
- internal/encryption/keyprovider/external/testprovider/testprovider.go
- internal/encryption/method/compliancetest/compliance.go
- internal/encryption/method/errors.go
- internal/encryption/method/external/README.md
- internal/encryption/method/external/command.go
- internal/encryption/method/external/compliance_test.go
- internal/encryption/method/external/config.go
- internal/encryption/method/external/descriptor.go
- internal/encryption/method/external/protocol.go
- internal/encryption/method/external/protocol/header.schema.json
- internal/encryption/method/external/protocol/input.schema.json
- internal/encryption/method/external/protocol/output.schema.json
- internal/encryption/method/external/testmethod/data/testmethod.go
- internal/encryption/method/external/testmethod/data/testmethod.py
- internal/encryption/method/external/testmethod/testmethod.go
- website/docs/language/state/encryption.mdx
- website/docs/language/state/examples/encryption/external-method/method-external-header.json
- website/docs/language/state/examples/encryption/external-method/method-external-input.json
- website/docs/language/state/examples/encryption/external-method/method-external-method.go
- website/docs/language/state/examples/encryption/external-method/method-external-method.py
- website/docs/language/state/examples/encryption/external-method/method-external-output.json
- website/docs/language/state/examples/encryption/external-method/method-external.tofu
- website/docs/language/state/examples/encryption/keyprovider-external-provider.py
> Fixes #2337: External encryption method

- CHANGELOG.md
- internal/configs/configschema/filter.go
- internal/configs/configschema/filter_test.go
> Dereference attributes during filtering to avoid schema cache altering

- .github/workflows/build-opentofu-oss.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
Half of the checks on main branch are failing because of the [deprecated GitHub actions: upload-artifact and download-artifact](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). This PR updates their versions.
1.10.0
> update upload and download artifacts gha

- .github/workflows/build-opentofu-oss.yml
One more update with the same goal as https://github.com/opentofu/opentofu/pull/2471
1.10.0
> update actions-packaging-linux gha

- .github/workflows/build-opentofu-oss.yml
This PR updates all the github actions used in build_opentofu workflow.
1.10.0
> update all build-opentofu-oss gha

- .github/workflows/build-opentofu-oss.yml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/compare-snapshots.yml
- .github/workflows/pr-opened.yml
- .github/workflows/release.yml
- .github/workflows/update-top-issues-ranking.yml
- .github/workflows/website.yml
Cherry pick of 210c0f68b0459e836dfdb2ee213df42c92d5d044 9b9ae4a25eb15f94c8adcbc0ef0823df68f451fa ad683285826b2aa93c2d449860dcf70ec922aa5a b8c24e935dc907b476e3088ca947ce756d2fee10
N/A
> [BACKPORT v1.7] update github actions

- .github/workflows/backport.yml
- .github/workflows/build-opentofu-oss.yml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/compare-snapshots.yml
- .github/workflows/pr-opened.yml
- .github/workflows/release.yml
- .github/workflows/update-top-issues-ranking.yml
- .github/workflows/website.yml
Cherry pick of 210c0f68b0459e836dfdb2ee213df42c92d5d044 9b9ae4a25eb15f94c8adcbc0ef0823df68f451fa ad683285826b2aa93c2d449860dcf70ec922aa5a b8c24e935dc907b476e3088ca947ce756d2fee10
N/A
> [BACKPORT v1.8] update github actions

- .github/workflows/backport.yml
- .github/workflows/build-opentofu-oss.yml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/compare-snapshots.yml
- .github/workflows/pr-opened.yml
- .github/workflows/release.yml
- .github/workflows/update-top-issues-ranking.yml
- .github/workflows/website.yml
Cherry pick of 210c0f68b0459e836dfdb2ee213df42c92d5d044 9b9ae4a25eb15f94c8adcbc0ef0823df68f451fa ad683285826b2aa93c2d449860dcf70ec922aa5a b8c24e935dc907b476e3088ca947ce756d2fee10
N/A
> [BACKPORT v1.9] update github actions

- CHANGELOG.md
- internal/builtin/providers/tf/provider.go
- internal/builtin/providers/tf/resource_data.go
- internal/builtin/providers/tf/resource_data_test.go
- website/docs/intro/whats-new.mdx
- website/docs/language/resources/tf-data.mdx
Adds support to the built-in provider.
The `moved` block can be used to migrate from the `null_resource` to the `terraform_data` resource.
Resolves #2272 
1.10.0
> Migration of null resource to terraform data

- CHANGELOG.md
- internal/genconfig/generate_config.go
- internal/lang/funcs/collection.go
- internal/lang/funcs/encoding.go
- internal/lang/funcs/encoding_test.go
- internal/lang/funcs/redact.go
- internal/lang/funcs/sensitive.go
- internal/lang/funcs/sensitive_test.go
- internal/states/instance_object.go
- internal/states/instance_object_test.go
- internal/tofu/node_output.go
- internal/tofu/node_output_test.go
This PR is a part of #1005.
In this PR I reviewed marks usage across the OpenTofu codebase so we can safely proceed with the introduction of new marks. Namely, this PR is the first one required to implement changes described in the [[RFC] Deprecation of module variables and outputs](https://github.com/opentofu/opentofu/pull/2180). The RFC is still in review so we can block this PR until the RFC is merged. I prepared it as an exercise to also learn more about the marks and extend the RFC properly.
While reviewing the usage of the marks, I also spotted a bug in `base64gunzip` function, which could expose sensitive values. To recreate the bug, you can use the following configuration:
```hcl
output "is_sensitive_base64gziped" {
value = base64gunzip(sensitive("hello!"))
}
```
In this case, the …
> refactor sensitive marks usage

- website/docs/language/settings/backends/s3.mdx
> Backport[1.9] fix(docs): correct custom example typo (#2485)

- website/docs/language/settings/backends/s3.mdx
> Backport[1.8] fix(docs): correct custom example typo (#2485)

- website/docs/language/settings/backends/s3.mdx
> Backport[1.7] fix(docs): correct custom example typo (#2485)

- TSC_SUMMARY.md
> January TSC meetings

- rfc/20250211-s3-locking-with-conditional-writes.md
Part of #599 
[Rendered version](https://github.com/opentofu/opentofu/blob/s3-locking-rfc/rfc/20250211-s3-locking-with-conditional-writes.md)
1.10.0
> RFC: s3 locking based on conditional writes

- CHANGELOG.md
- internal/backend/remote-state/http/client.go
- internal/backend/remote-state/s3/backend.go
- internal/backend/remote-state/s3/backend_state.go
- internal/backend/remote-state/s3/backend_test.go
- internal/backend/remote-state/s3/client.go
- internal/backend/remote-state/s3/client_test.go
- internal/states/statemgr/locker.go
- website/docs/language/settings/backends/s3.mdx
Resolves #599
[RFC](https://github.com/opentofu/opentofu/blob/s3-locking-implementation/rfc/20250211-s3-locking-with-conditional-writes.md)
1.10.0
> Add the initial implementation for s3 locking

- CHANGELOG.md
- CONTRIBUTING.md
- internal/command/apply.go
- internal/command/apply_test.go
- internal/command/import.go
- internal/command/plan.go
- internal/command/plan_test.go
- internal/command/refresh.go
- internal/command/views/apply.go
- internal/command/views/hook_ui.go
- internal/command/views/hook_ui_test.go
- internal/command/views/plan.go
- internal/command/views/refresh.go
- website/docs/cli/commands/apply.mdx
- website/docs/cli/commands/plan.mdx
Remove UiHooks when using `-concise` option from the following commands:
- apply
- plan
- refresh
Resolves #2409
1.10.0
> feat: remove progress messages from commands using -concise argument

- TSC_SUMMARY.md
> 2025 feb updates

- internal/encryption/base.go
- internal/encryption/config/config_load.go
- internal/encryption/config/config_parse.go
- internal/encryption/encryption.go
- internal/encryption/keyprovider.go
- internal/encryption/method/unencrypted/method.go
- internal/encryption/methods.go
- internal/encryption/targets.go
- internal/encryption/targets_test.go
The encryption package went through a wild ride of design decisions when it was original built.  This PR takes a more idiomatic approach to processing the configured targets, methods, and key_providers to fix a few bugs.  It also makes the individual components easier to test, as well as work on.
Resolves #1604 by only loading the methods and key_providers required in a particular target, and in isolation.  Previously, all methods and key_providers were fully configured and initialized, regardless of the operation and target specified.  This led to some interesting bugs, particularly when it came to conflicting key_provider names between projects used together with `terraform_remote_data`.  Key providers which were not referenced would still be initialized and attempt to understand …
> Improve encryption internals and fix a few bugs therein

- CHANGELOG.md
> Update changelog for Untangle Encryption Evaluation #2551

- TSC_SUMMARY.md
> Fix TSC_SUMMARY year

- internal/command/apply.go
- internal/command/console.go
- internal/command/import.go
- internal/command/init.go
- internal/command/meta.go
- internal/command/plan.go
- internal/command/refresh.go
- internal/command/test.go
- internal/command/validate.go
> Typo: consolodation -> consolidation

- internal/backend/remote-state/s3/client.go
- internal/backend/remote-state/s3/client_test.go
Resolves #2605
Tested against the setup provided in the submitted issue.
1.10.0
> Lock object writing is configured the same with the state object writing

- website/docs/intro/migration/terraform-1.6.mdx
- website/docs/intro/migration/terraform-1.7.mdx
- website/docs/intro/migration/terraform-1.8.mdx
- website/docs/intro/migration/terraform-1.9.mdx
Resolves #2570
These changes are attempting to bring more clarity to the users when it comes to the `skip_s3_checksum` suggestion for being removed.
Ever since #840, indeed, OpenTofu does not need that argument in most of the cases, but there are still S3 compatible providers that still does not yet accept the `X-Amz-Checksum-Sha256` header. Therefore, the new wording is trying to signal to the user to check before taking a decision on removing it or not.
> [!NOTE]
>  #840 added explicit calculation of the checksum, blocking aws-sdk from doing it, which rendered `skip_s3_checksum` argument mostly unneeded. Details on how the changes from #840 did this, can be found in [aws-sdk-go-v2#1689](https://github.com/aws/aws-sdk-go-v2/issues/1689).
1.10.0
> Reword skip_s3_checksum mentions in the migration guides

- CHANGELOG.md
Resolves #2596, #2606
Adding changelog entries for the aforementioned issues.
1.10.0
> Adding missing CHANGELOG entries

- go.mod
- go.sum
Resolves https://github.com/opentofu/opentofu/security/dependabot/35
Details: https://vulners.com/cve/CVE-2025-30204
This is a false-positive report from Dependabot. This PR is fixing the dependency only to remove the noise that scanners could produce for the users of OpenTofu's future version.
As seen in [golang-jwt/jwt security report](https://github.com/golang-jwt/jwt/security/advisories/GHSA-mh63-6h87-95cp), this issue is present in `jwt.ParseUnverified` (PR for the fix [here](https://github.com/golang-jwt/jwt/commit/0951d184286dece21f73c85673fd308786ffe9c3)).
Checking this with `go mod why github.com/golang-jwt/jwt/v4`, the affected version is used by `github.com/Azure/go-autorest/autorest/adal` but that library is not using `ParseUnverified` at all.
1.10.0
> Fix CVE-2025-30204

- go.mod
This is disabling a new key-exchange mechanism introduced in go1.23.
The new feature is enabled by default starting with go1.23 and a lot of systems are not yet prepared for it, including AWS, GCP, Datadog, etc, as seen in [go#67061](https://github.com/golang/go/issues/67061).
We are having no issues reported yet with this, but as a cautionary action, we disable this and will monitor the development on the Go issue linked above.
Gave it just a rough testing with an S3 bucket backend and some resources created in AWS. All passed.
1.10.0
> Disabling post-quantum key exchange mechanism X25519MLKEM768

- CHANGELOG.md
> Added changelog entry for gpg key expiration warning change

- internal/getproviders/oci_registry_mirror_source.go
- internal/getproviders/oci_registry_mirror_source_test.go
This is for https://github.com/opentofu/opentofu/issues/2540. It addresses a minor bug in the initial implementation which I found when testing what became our alpha release.
We left this unfixed at the time because it's not on the critical path for early testing, but fixing this will make the `oci_mirror` source easier to use in practice when combined with other source types in the same CLI Configuration.
Intentionally no CHANGELOG entry here because the affected functionality hasn't been included in any stable release yet, and so this falls under the existing entry about OCI provider mirrors.
---
Because the CLI Configuration allows specifying multiple provider installation methods, we use `getproviders.MultiSource` to aggregate together all of their results for a particular provider …
> getproviders: OCIRegistryMirrorSource better handle missing provider

- website/docs/cli/commands/test/index.mdx
> Reflecting the current state of module source on tofu test docs

- website/docs/cli/commands/test/index.mdx
Backport of https://github.com/opentofu/opentofu/pull/2666
Resolves https://github.com/opentofu/opentofu/issues/2418
1.7.0
> Backport [1.7] Reflecting the current state of module source on tofu test docs (#2666)

- website/docs/cli/commands/test/index.mdx
Backport #2666 
Resolves https://github.com/opentofu/opentofu/issues/2418
1.8
> Backport [1.8] Reflecting the current state of module source on tofu test docs (#2666)

- website/docs/cli/commands/test/index.mdx
Backport #2666
Resolves https://github.com/opentofu/opentofu/issues/2418
1.9
> Backport [1.9] Reflecting the current state of module source on tofu test docs (#2666)

- CHANGELOG.md
- internal/backend/remote-state/oss/backend.go
- internal/backend/remote-state/oss/backend_test.go
Resolves #2663 
The OSS backend now uses the standard httpproxy.FromEnvironment() to parse proxy
configurations, which properly honors NO_PROXY settings while retaining
environment variable-based proxy detection for HTTP/HTTPS_PROXY variables. This
ensures the OSS client respects exclusion rules without breaking existing proxy
behavior.
1.10.0
> Fix #2663: Resolve NO_PROXY recognition issue in oss remote backend

- internal/lang/evalchecks/eval_for_each.go
- internal/lang/evalchecks/eval_for_each_test.go
- internal/tofu/context_plan2_test.go
Resolves #2532
The refactoring involves a few decisions:
- When returning invalid values, we return the original value wrapped on NullVal. Before we were just returning ` cty.NullVal(cty.Map(cty.DynamicPseudoType))` for everything.
- When returning unknown values, we wrap it on UnknownVal. Previously we had a lot of different behaviors depending on the code path.
I decided to do that so we maintain a context of the types, without losing them when returning it to something that doesn't mean anything.
1.10.0
> refactor: eval_for_each checks

- website/docs/language/state/remote-state-data.mdx
Documentation for current state of #2684 
1.10.0
> Add warning for sensitive state outputs in terraform_remote_state

- rfc/20250129-Tracing-For-Extra-Context.md
Please see the rendered view of this RFC [here](https://github.com/opentofu/opentofu/blob/rfc-opentelemetry-end-user-tracing/rfc/20250129-Tracing-For-Extra-Context.md):
> [RFC] OpenTelemetry (OTEL) Tracing for providing end users more context

- internal/backend/local/backend_plan_test.go
- internal/backend/remote-state/http/server_test.go
- internal/builtin/providers/tf/data_source_state_test.go
- internal/builtin/providers/tf/testdata/deprecation_warnings.tfstate
- internal/cloud/state_test.go
- internal/command/command_test.go
- internal/command/init_test.go
- internal/command/jsonformat/state_test.go
- internal/command/jsonstate/state_test.go
- internal/command/meta_backend_test.go
- internal/command/output_test.go
- internal/command/show_test.go
- internal/command/views/json/output_test.go
- internal/command/views/output_test.go
- internal/lang/marks/marks.go
- internal/states/instance_object_test.go
- internal/states/remote/state_test.go
- internal/states/state_test.go
- internal/states/statemgr/filesystem_test.go
- internal/states/statemgr/migrate_test.go
- internal/states/statemgr/testing.go
- internal/tofu/context_apply2_test.go
- internal/tofu/context_apply_test.go
- internal/tofu/context_plan_test.go
- internal/tofu/context_refresh_test.go
- internal/tofu/evaluate_test.go
- internal/tofu/node_output_test.go
- internal/tofu/test_context_test.go
This PR is a separate one just to simplify the review process. I will merge it into https://github.com/opentofu/opentofu/pull/2679 once both are reviewed.
> fix / extend tests for deprecation warnings support for terraform_remote_state

- website/docs/intro/install/docker.mdx
Reverts opentofu/opentofu#2403
⚠️ To be merged just before or after the 1.9.1 release.
> Revert "Temporary revert minimal image docs"

- internal/tofu/context_apply2_test.go
- internal/tofu/context_plan.go
When a variable from the root module is marked as deprecated and the caller is setting values for it, write a warning message about a deprecated variable being used.
Part of #2555
1.10.0
> Add a new warning for root module deprecated variables

- CHANGELOG.md
> Add missing changelog entry for provider cache locking

- website/docs/language/modules/develop/refactoring.mdx
This PR makes it clear what commands should produce all the deprecation warnings. As per discussion in https://github.com/opentofu/opentofu/pull/2705#discussion_r2063984205
1.10.0
> add explanation of supported commands for deprecation warnings

- website/docs/language/state/examples/encryption/aes_gcm.tf
- website/docs/language/state/examples/encryption/configuration.ps1
- website/docs/language/state/examples/encryption/configuration.sh
- website/docs/language/state/examples/encryption/configuration.tf
- website/docs/language/state/examples/encryption/fallback.tf
- website/docs/language/state/examples/encryption/fallback_from_unencrypted.tf
- website/docs/language/state/examples/encryption/fallback_to_unencrypted.tf
- website/docs/language/state/examples/encryption/sample.tf
- website/docs/language/state/examples/encryption/terraform_remote_state.tf
- website/docs/language/state/examples/encryption/terraform_remote_state_full_a.tf
- website/docs/language/state/examples/encryption/terraform_remote_state_full_b.tf
This is updating some naming in the encryption docs since there was a complain about some possible confussion that those can create.
Resolves #2759
1.10.0
> Update some names in the encryption docs

- .github/workflows/checks.yml
- .golangci.yml
- Makefile
> Update golangcilint v2

- internal/addrs/module_instance_test.go
- internal/addrs/module_test.go
- internal/addrs/parse_target.go
> Address linting issues in addrs package

- internal/copy/copy_dir_test.go
> Fix lint issues in internal/copy

- internal/builtin/provisioners/file/resource_provisioner.go
- internal/builtin/provisioners/file/resource_provisioner_test.go
- internal/builtin/provisioners/local-exec/resource_provisioner_test.go
- internal/builtin/provisioners/remote-exec/resource_provisioner.go
- internal/builtin/provisioners/remote-exec/resource_provisioner_test.go
> Address linting in internal/builtin

- internal/states/remote/state_test.go
- internal/states/remote/testing.go
- internal/states/resource.go
- internal/states/statemgr/filesystem.go
- internal/states/statemgr/filesystem_test.go
> Fix lint issues in internal/states

- internal/lang/eval_test.go
- internal/lang/funcs/collection.go
- internal/lang/funcs/filesystem.go
- internal/lang/funcs/filesystem_test.go
- internal/lang/funcs/render_template.go
- internal/lang/funcs/string.go
- internal/lang/marks/marks.go
> Fix lint issues in internal/lang

- internal/providercache/installer_test.go
> Fix lint issues in internal/providercache

- internal/genconfig/generate_config.go
- internal/genconfig/generate_config_write.go
> Fix lint issues in internal/genconfig

- internal/encryption/keyprovider/aws_kms/compliance_test.go
> Fix lint issues in ./internal/encryption

- internal/tofu/context.go
- internal/tofu/context_apply2_test.go
- internal/tofu/context_apply_test.go
- internal/tofu/context_plan2_test.go
- internal/tofu/node_resource_abstract.go
- internal/tofu/node_resource_abstract_instance.go
- internal/tofu/node_resource_abstract_test.go
- internal/tofu/node_resource_validate_test.go
- internal/tofu/transform_attach_config_resource.go
- internal/tofu/transform_attach_config_resource_test.go
- internal/tofu/transform_diff.go
> Fix lint issues in internal/tofu

- internal/configs/configschema/decoder_spec_test.go
- internal/configs/hcl2shim/paths.go
- internal/configs/provider_validation.go
- internal/configs/resource.go
> Fix lint issues in internal/configs

- internal/communicator/communicator_mock.go
- internal/communicator/communicator_test.go
- internal/communicator/ssh/communicator.go
- internal/communicator/ssh/communicator_test.go
- internal/communicator/ssh/provisioner.go
- internal/communicator/winrm/communicator.go
- internal/communicator/winrm/communicator_test.go
> Fix lint issues in internal/communicator

- website/docs/cli/commands/fmt.mdx
> Add note about the diff dependency on the fmt command

- .github/scripts/govulncheck-submit-issues.sh
- .github/workflows/govulncheck.yml
- CONTRIBUTING.RELEASE.md
OpenTofu versions
Resolves #2629
As proposed in the [Security Advisory Policy for Upstream Dependencies](https://github.com/opentofu/opentofu/blob/e29bdf5b143259e441f2f06d2b941b90cadd587b/rfc/20250314-security-patch-policy.md), we are adding a new workflow that will be triggered automatically (once per week), and will scan all the branches that are holding a stable, maintained version of [OpenTofu](https://github.com/opentofu/opentofu).
ℹ️ An example of a run can be found [here](https://github.com/opentofu/opentofu/actions/runs/14105986501/job/39512621597).
1.10.0
> Add github workflow to run govoulncheck on all branches with supported OpenTofu versions

- .golangci.yml
- internal/command/apply_test.go
- internal/command/autocomplete_test.go
- internal/command/cliconfig/cliconfig.go
- internal/command/clistate/local_state.go
- internal/command/command_test.go
- internal/command/fmt.go
- internal/command/graph_test.go
- internal/command/import_test.go
- internal/command/init_test.go
- internal/command/jsonformat/computed/renderers/primitive.go
- internal/command/jsonfunction/function.go
- internal/command/jsonplan/plan.go
- internal/command/login.go
- internal/command/logout.go
- internal/command/meta_backend_migrate.go
- internal/command/meta_backend_test.go
- internal/command/meta_test.go
- internal/command/plan_test.go
- internal/command/providers_schema_test.go
- internal/command/show_test.go
- internal/command/taint_test.go
- internal/command/unlock_test.go
- internal/command/untaint_test.go
- internal/command/views/hook_count_test.go
- internal/command/views/output.go
- internal/command/views/test.go
- internal/command/views/test_test.go
- internal/command/workdir/plugin_dirs.go
- internal/command/workspace_command_test.go
> Fix linting in internal/command

- website/docs/cli/config/environment-variables.mdx
> docs: relocate sentence about .terraformignore to proper section

- cmd/tofu/registries_disco.go
This is related to https://github.com/opentofu/opentofu/issues/2664.
The `disco.Disco` API isn't yet set up to pass through `context.Context`, and so if we give it a HTTP client that has the OpenTelemetry instrumentation on it then any HTTP request causes an orphan trace span disconnected from the main trace, which causes annoying noise in some trace viewers.
As a temporary solution so we can ship v1.10 soon without making large changes to the `svchost` library, we'll prevent the HTTP client constructor function from detecting that tracing is enabled by passing it `context.TODO()` instead of the actual context. This would not be acceptable in the long run but is safe for this temporary workaround because currently `httpclient.New` doesn't use the given context for anything _except_ …
> package main: Prevent disco.Disco generating OTel traces

- rfc/20250317-ephemeral-resources.md
Part of #1996
[Rendered view](https://github.com/opentofu/opentofu/blob/ephemeral-rfc/rfc/20250317-ephemeral-resources.md)
1.11.0
> [RFC] Ephemeral resources and write-only attributes

- .github/workflows/checks.yml
- .github/workflows/compare-snapshots.yml
- .github/workflows/website.yml
GitHub recently added support for this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
Go Change:
* [Website](https://github.com/opentofu/opentofu/actions/runs/15303996208) skipped
* [Snapshot](https://github.com/opentofu/opentofu/actions/runs/15303996210) run
* [Checks](https://github.com/opentofu/opentofu/actions/runs/15303996229) run
Website Change:
* [Website](https://github.com/opentofu/opentofu/actions/runs/15304015469/job/43051901736) run
* [Snapshot](https://github.com/opentofu/opentofu/actions/runs/15304015482) skipped
* [Checks](https://github.com/opentofu/opentofu/actions/runs/15304015504) skipped
> Skip unnessary workflow checks

- docs/provider-references.md
Improves internal documentation that was missed in the provider iteration work of 1.9.  This should help with the implementation of https://github.com/opentofu/opentofu/issues/2379.
> Update provider for_each internal documentation

- CHANGELOG.md
- internal/command/arguments/show.go
- internal/command/arguments/show_test.go
- internal/command/arguments/showtargettype_string.go
- internal/command/jsonconfig/expression.go
- internal/command/show.go
- internal/command/show_test.go
- internal/command/testdata/show-config-module/child/main.tf
- internal/command/testdata/show-config-module/main.tf
- internal/command/views/show.go
- website/docs/cli/commands/show.mdx
> Config mode for tofu show

- internal/states/statefile/version3_upgrade.go
- internal/states/statefile/version4.go
- internal/tofu/eval_context_builtin.go
> Provider keyed instance refactor

- internal/backend/remote-state/s3/backend.go
> refactor: remove unused func in s3 backend

- internal/command/jsonplan/plan.go
- website/docs/internals/json-format.mdx
Resolves #2715 
Updates documentation with the structs for:
- [Plan](https://github.com/opentofu/opentofu/blob/3bdd0073a5240a4052bf0b98b072984e29164fef/internal/command/jsonplan/plan.go#L53-L69), [Plan Resources](https://github.com/opentofu/opentofu/blob/3bdd0073a5240a4052bf0b98b072984e29164fef/internal/command/jsonplan/resource.go#L15-L47), [Plan Values](https://github.com/opentofu/opentofu/blob/3bdd0073a5240a4052bf0b98b072984e29164fef/internal/command/jsonplan/values.go#L26-L30) and [Plan Changes](https://github.com/opentofu/opentofu/blob/3bdd0073a5240a4052bf0b98b072984e29164fef/internal/command/jsonplan/plan.go#L85-L148)
- [State, Resources, Modules, Output](https://github.com/opentofu/opentofu/blob/3bdd0073a5240a4052bf0b98b072984e29164fef/internal/command/jsonstate/state.go#L36-L115) …
> docs: update JSON Output Format page

- cmd/tofu/main.go
- internal/backend/remote-state/consul/backend_state.go
- internal/backend/remote-state/cos/transport.go
- internal/backend/remote-state/http/client.go
- internal/backend/remote-state/kubernetes/backend.go
- internal/backend/remote-state/s3/backend.go
- internal/builtin/providers/tf/data_source_state.go
- internal/cloud/backend_context.go
- internal/cloud/backend_plan.go
- internal/cloud/backend_taskStage_taskResults.go
- internal/depsfile/locks.go
- internal/refactoring/move_execute.go
The static checks which talk about deprecated structs were intentionally avoided, as these are a bit more involved to fix.
Relates to https://github.com/opentofu/opentofu/issues/2769
> refactor: implement all simple static checks

- .github/workflows/checks.yml
- Makefile
> refactor: lint without revision flag

- TSC/2025-06-10_NOTES.md
> TSC Notes June 10 2025

- .github/workflows/govulncheck.yml
> Include v1.10.0 in govulncheck

- CHANGELOG.md
Part of #2970 
In the previous PR, missed the changelog for this.
> Add changelog for 2970

- CHANGELOG.md
Adds the changelog for #2970 in v1.10.
All the other changes already backported: https://github.com/opentofu/opentofu/commits/v1.10/
> [v1.10 BACKPORT] s3 backend .tflock PutObject missing x-amz-server-side-encryption header

- internal/tofu/node_resource_abstract.go
- internal/tofu/node_resource_abstract_instance.go
- internal/tofu/node_resource_destroy.go
- internal/tofu/node_resource_validate.go
Working on the ephemerality of the connection block, realised that the connection block schema is defined in two packages. Checked the diff between the two and seen nothing different (other than a single comment).
⚠️ Please double check on your own that the one I removed is not breaking any legacy assumptions or anything that I am not aware of 🤕 
The one kept: https://github.com/opentofu/opentofu/blob/a1ba3e24aa9c52452951ff00d6b6c1c777f23532/internal/communicator/shared/shared.go#L24
The one removed: https://github.com/opentofu/opentofu/blob/a1ba3e24aa9c52452951ff00d6b6c1c777f23532/internal/tofu/node_resource_validate.go#L166
Part of no issue, just random thing found.
> Remove duplicated connection block schema

- CHANGELOG.md
- internal/command/jsonformat/collections/slice.go
- internal/command/jsonformat/computed/renderers/primitive.go
- internal/command/jsonformat/computed/renderers/renderer_test.go
- internal/command/jsonformat/differ/differ_test.go
- internal/command/jsonformat/differ/list.go
- internal/command/jsonformat/jsondiff/diff.go
- internal/command/jsonformat/jsondiff/types.go
- internal/command/jsonformat/plan_test.go
After trying several approaches that were overkill for this case, I found an existing working code path for diffing complex slice elements, specifically objects. I was able to tap into the same code with minimal changes to other parts of the code and reuse it for multiline strings.
This PR also includes small refactorings of existing flows to make it more readable and adds comments to explain why/how those specific parts work, which took me time to understand, hopefully making it easier for future contributors working on this code. 
Resolves #2887
- x ] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.
> Diffing lists containing multiline strings

- go.mod
- go.sum
Tencent cloud decided to trim down their older tags given that they had over 20k tags in a single repo.  https://github.com/TencentCloud/tencentcloud-sdk-go/issues/283
They removed two of the tags that we depend on.  We could have tried to update our sdk version to a more modern release, but do not have easily accessible setups for testing a significant change like that.
As far as I can tell, these are the most "appropriate" commits to use compared to the deleted tags we were pointing at.
https://github.com/TencentCloud/tencentcloud-sdk-go/releases/tag/v1.0.588 -> 97469a3dcd4e https://github.com/TencentCloud/tencentcloud-sdk-go/releases/tag/v1.0.233 -> 8078545fa058
Comparing with my cached versions:
```
find sts* -type f | sort | xargs md5sum
7936d0938e5a14cf5442ee4d67621bf2 …
```
> Move cos backend dependencies to git commits instead of tags

- .github/scripts/update_top_issues_ranking/main.go
- .github/scripts/update_top_issues_ranking/ranking.tmpl
This is just a few tweaks to the program that updates https://github.com/opentofu/opentofu/issues/1496 each day.
The main motivation here is that we now use pull requests rather than issues to represent RFCs that have not yet been approved, and so the ranking of issues labeled "rfc" was misleading to include. All of the issues that were labeled "rfc" that were not "RFC Tracker" issues under our newer process are also labeled as "enhancement" so they will be included under the "Top Enhancements" ranking. The "Top RFCs" section is now removed completely.
While I was tweaking this anyway I also added a short note to the top explaining how these rankings are generated and removed some of the visual clutter from the suffixes of the individual list items, which tended to get wrapped oddly for …
> Make the "Top-Ranking Issues" issue a little more concise

- internal/backend/remote-state/azure/arm_client.go
Only calls ListKeys once in the azure backend to reduce likelihood of rate limiting.
Tests on main are bork'd so this is waiting on another PR to fix those.
Resolves #3047
> Reduce calls to ListKey in azure backend

- internal/command/e2etest/primary_test.go
Part of #2834 
Missed that local-exec on windows is running `cmd`, not `/bin/sh`.
Adjusted the ephemeral workflow test to take into account that too.
> Adjust the ephemeral workflow e2e test to run correctly on windows too

- internal/command/e2etest/primary_test.go
> Make ephemeral workflow e2e test to run correctly on windows too - second attempt

- CHANGELOG.md
- internal/backend/remote-state/s3/backend.go
- internal/backend/remote-state/s3/backend_state.go
- internal/backend/remote-state/s3/backend_test.go
- internal/backend/remote-state/s3/client.go
- internal/backend/remote-state/s3/client_test.go
- website/docs/language/settings/backends/s3.mdx
> Add tag options for S3 state backend objects

- .github/workflows/nightly.yml
Fixing github actions live is a nightmare. Let's see if this works!
> Added debug logging to rclone setup, removed R2_ACL

- CHANGELOG.md
- internal/backend/remote-state/s3/client.go
Resolves #3102
Checking the issue reported above, seen that we don't print the request logs for the dynamodb requests.
This PR adds the logger to the dynamodb requests.
⚠️ In case you know a good reason on why we shouldn't do this, please block this PR merge. I am not sure that security is a concern here since those logs will be enabled only when DEBUG level is configured, which arguably will already expose other possible sensitive information.
ℹ️ Backport this to v1.10
> Add logging for dynamodb client in s3 backend

- internal/lang/funcs/collection.go
- internal/lang/funcs/conversion.go
- internal/lang/funcs/descriptions.go
- internal/lang/funcs/encoding.go
- internal/lang/funcs/filesystem.go
- internal/lang/funcs/number.go
- internal/lang/funcs/redact.go
- internal/lang/funcs/redact_test.go
> Update funcs package to properly handle ephemeral values

- internal/command/e2etest/ephemeral_test.go
- internal/tofu/eval_conditions.go
- internal/tofu/eval_variable.go
- internal/tofu/eval_variable_test.go
In hindsight, this was quite simple and could have easily been included in the original ephemeralasnull PR
> Address ephemeralasnull comments/TODOs

- internal/command/e2etest/testdata/ephemeral-workflow/main.tf
- internal/configs/static_scope.go
- internal/tofu/evaluate.go
- internal/tofu/evaluate_test.go
- website/docs/language/expressions/references.mdx
> Add `tofu.applying` (and `terraform.applying`)

- internal/command/cliconfig/cliconfig.go
- internal/command/cliconfig/cliconfig_test.go
- internal/command/cliconfig/testdata/config
- internal/command/cliconfig/testdata/config-env
> Remove unused CLI config fields

- CHANGELOG.md
- internal/backend/remote-state/azure/README.md
- internal/backend/remote-state/azure/auth/auth.go
- internal/backend/remote-state/azure/auth/cli_auth.go
- internal/backend/remote-state/azure/auth/client_cert_auth.go
- internal/backend/remote-state/azure/auth/client_secret_auth.go
- internal/backend/remote-state/azure/auth/msi_auth.go
- internal/backend/remote-state/azure/auth/oidc_auth.go
- internal/backend/remote-state/azure/auth/utility.go
- internal/backend/remote-state/azure/auth/workload_identity_auth.go
- internal/backend/remote-state/azure/backend.go
- internal/backend/remote-state/azure/backend_test.go
- internal/backend/remote-state/azure/helpers_test.go
- internal/backend/remote-state/azure/meta-test/.gitignore
- internal/backend/remote-state/azure/meta-test/README.md
- internal/backend/remote-state/azure/meta-test/aks/main.tf
- internal/backend/remote-state/azure/meta-test/aks/outputs.tf
- internal/backend/remote-state/azure/meta-test/aks/variables.tf
- internal/backend/remote-state/azure/meta-test/aks/version.tf
- internal/backend/remote-state/azure/meta-test/main.tf
- internal/backend/remote-state/azure/meta-test/outputs.tf
- internal/backend/remote-state/azure/meta-test/variables.tf
- website/docs/language/settings/backends/azurerm.mdx
Resolves #2829
This pull request adds the following configuration variables to the `azurerm` backend:
- use_aks_workload_identity
- client_id_file_path
- client_secret_file_path
- client_certificate
> Add new configuration to AzureRM Backend

- website/docs/language/state/encryption.mdx
Part of #2386 
Since we don't have enough feedback to decide if the experimental encryption blocks do work well or not, we don't want to get these out of the experimental phase.
Therefore, we want to let the users know that we are looking for any type of feedback on those.
> Add a note about the lack of feedback on the experimental encryption method and key_provider
