opentofu/opentofu

docs/architecture.md
Fixes N/A
1.5.x
-  Add missing "link" to `docs/architecture.md` which would fix parsing issue we have in an internal project
=> Fix link in architecture.md

CONTRIBUTING.md
To make sure we keep the changelog up to date and not have to fill it retroactively.
=> Update CONTRIBUTING.md to mention the need to update the CHANGELOG.md.

CHANGELOG.md, internal/states/statemgr/filesystem.go
Fix https://github.com/opentffoundation/opentf/issues/278
This handles ignored `err` variables in `internal/states/statemgr`.
I'm happy to change this to be more aggressive and return wrapped errors instead of just logging.
=> internal/states/statemgr: handle ignored errors

.gitignore
This allows to avoid committing the `go build` output by mistake.
=> chore: ignore /opentf binary

internal/command/test_test.go, internal/command/testdata/test/not_exists_output/main.tf, internal/command/testdata/test/not_exists_output/main.tftest.hcl, internal/command/testdata/test/null_output/main.tf, internal/command/testdata/test/null_output/main.tftest.hcl, internal/opentf/evaluate.go
Fixes #257
Since OpenTF does not store `nil` outputs in it's state we fail to get the value.
Added a check of `if output == nil` and if true returning `cty.NilVal` 
Added relevant tests - 
- `opentf test` does not crash for `null` outputs
- Made sure we don't some how pass undeclared outputs and set them as `null`
1.6.0-alpha
-  `opentf test` does not crash for `null` outputs
=> Fix `opentf test` crash on nil output

CHANGELOG.md, internal/backend/remote/backend.go, internal/backend/remote/backend_test.go, internal/backend/remote/testing.go, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/testing.go, internal/command/login.go, internal/command/login_test.go, internal/command/logout.go, internal/command/logout_test.go, website/docs/cli/cloud/settings.mdx, website/docs/language/settings/backends/remote.mdx
Legacy Terraform used a default value of "app.terraform.io" for:
- the `login` and `logout` commands, when the commands were called with no arguments;
- the `remote` backend when the `hostname` attribute has not been specified;
- the `cloud` backend when neither the `hostname` attribute nor the `TF_CLOUD_HOSTNAME` environment variable were set;
This could be confusing to an OpenTF user, and unfair to other vendors offering this kind of integration with the OpenTF CLI, so as of this PR, these values are explicitly required.
Note that the code contains some extra provisions for `app.terraform.io` to accommodate its quirks, and these were not removed to not change the current level of support, so that TFC customers can still use OpenTF.
Closes #269.
=> Require hostname for cloud/remote backends and login/logout

internal/backend/backend.go, internal/backend/backend_test.go, internal/backend/local/backend.go, internal/backend/remote-state/consul/backend_test.go, internal/backend/remote-state/cos/client.go, internal/backend/remote-state/cos/transport.go, internal/backend/remote-state/gcs/client.go, internal/backend/remote-state/http/client.go, internal/backend/remote-state/oss/backend.go, internal/backend/remote/backend_plan.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/backend` and its subpackages.
=> internal/backend: deprecate io/ioutil

README.md
=> Fix Slack workspace link in README

internal/builtin/provisioners/file/resource_provisioner.go, internal/builtin/provisioners/local-exec/resource_provisioner_test.go, internal/builtin/provisioners/remote-exec/resource_provisioner.go
Another in a series to deprecate `io/ioutil` project wide. I'll do one of these per directory under `internal` to prevent creating a monster merge-conflict PR.
Previous: https://github.com/opentffoundation/opentf/pull/312
=> internal/builtin: deprecate io/ioutil

internal/cloud/backend_plan.go, internal/cloud/e2e/main_test.go, internal/cloud/state_test.go, internal/cloud/tfe_client_mock.go
This removes the deprecated `io/ioutil` package from `internal/cloud` and its subpackages.
There is nothing user-facing, so a CHANGELOG entry isn't warranted.
=> internal/cloud: deprecate io/ioutil

internal/states/statefile/read.go, internal/states/statefile/roundtrip_test.go, internal/states/statemgr/filesystem.go, internal/states/statemgr/filesystem_test.go
This removes deprecated calls to `io/ioutil` from the `internal/states` package and subpackages.
There is nothing user-facing, so a CHANGELOG entry isn't warranted.
Part of issue #313
=> internal/states: deprecate io/ioutil

.github/ISSUE_TEMPLATE/bug_report.yml, .github/pull_request_template.md, BUILDING.md, CONTRIBUTING.md
- Fixed broken link to the .go-version file in the md doc files
- Fixed broken links in the issue template
Housekeeping and consistency.
Closes #324
=> Fixes broken links in md docs and bug template

internal/command/jsonplan/plan.go, testing/equivalence-tests/outputs/data_read/plan.json
Closes #321
The order in which relevant attributes are stored in the plan is non-deterministic. It's not a biggie in general, but it could be important for some tooling, like our own equivalence testing. There's no harm in sorting these during JSON marshal.
=> Marshal plan#relevant_attributes in deterministic order

internal/communicator/ssh/communicator.go, internal/communicator/ssh/communicator_test.go, internal/communicator/ssh/provisioner.go, internal/communicator/ssh/ssh_test.go
This removes all instances of the deprecated `io/ioutil` package from `internal/communicator` and its subpackages.
There is nothing user-facing that warrants a CHANGELOG entry.
=> internal/communicator: deprecate io/ioutil

internal/copy/copy_dir_test.go
This replaces all instances of the deprecated `io/ioutil` package within `internal/copy` and its subpackages.
=> internal/copy: deprecate io/ioutil

internal/configs/config_build_test.go, internal/configs/configload/copy_dir_test.go, internal/configs/configload/testing.go, internal/configs/module_call_test.go, internal/configs/parser_config_dir_test.go, internal/configs/parser_config_test.go, internal/configs/provider_test.go
This replaces all instances of the deprecated `io/ioutil` package within `internal/configs` and its subpackages.
There is nothing user-facing that warrants a CHANGELOG entry.
=> internal/configs: deprecate io/ioutil

internal/e2e/e2e.go
This replaces usage of the deprecated `io/ioutil` package in the `internal/e2e` package.
=> internal/e2e: deprecate io/ioutil

internal/getproviders/mock_source.go, internal/getproviders/registry_client.go
This replaces the deprecated `io/ioutil` package in `internal/getproviders`.
=> internal/getproviders: deprecate io/ioutil

internal/initwd/from_module.go, internal/initwd/module_install_test.go
This replaces the deprecated `io/ioutil` package in `internal/initwd`.
=> internal/initwd: deprecate io/ioutil

internal/lang/funcs/filesystem.go
This replaces the deprecated `io/ioutil` package used in `internal/lang/functions`.
=> internal/lang/funcs: deprecate io/ioutil

internal/plugin/discovery/find.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/plugin` and its subpackages.
=> internal/plugin: deprecate io/ioutil

internal/registry/client.go
This removes all usage of the deprecated `io/ioutil package` throughout `internal/registry` and its subpackages.
=>  internal/registry: deprecate io/ioutil

internal/replacefile/writefile.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/replacefile` and its subpackages.
=> Internal replacefile deprecate ioutil

internal/providercache/cached_provider.go, internal/providercache/package_install.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/providercache` and its subpackages.
=> internal/providercache: deprecate io/ioutil

internal/legacy/opentf/state.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/legacy` and its subpackages.
=> internal/legacy: deprecate io/ioutil

internal/modsdir/manifest.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/modsdir` and its subpackages.
=> internal/modsdir: deprecate io/ioutil

internal/plans/planfile/config_snapshot.go, internal/plans/planfile/reader.go, internal/plans/planfile/tfplan.go
This removes all usage of the deprecated `io/ioutil` package throughout `internal/plans` and its subpackages.
=> internal/plans: deprecate io/ioutil

.github/workflows/merged-pr.yml, .github/workflows/pr-opened.yml
Change the CHANGELOG bot to write its message on PR open.
Also, change the message to indicate that we'd like the contributor themselves to update the CHANGELOG, as part of the PR
Fixes https://github.com/opentffoundation/opentf/issues/329
1.6.0
=> Change the CHANGELOG bot to add the reminder as a comment when PR is opened

CHANGELOG.md, internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testdata/invalid-module-name/child/main.tf, internal/initwd/testdata/invalid-module-name/main.tf
Signed-off-by: Elbaz <eranelbaz97+github@gmail.com>
Resolves #356
See PR under MPL 1.5.x: https://github.com/hashicorp/terraform/pull/33769
1.6.0
-  `opentf init`: OpenTF will no longer allow downloading remote modules to invalid paths
=> Backport from 1.5.x: Require valid module name

CHANGELOG.md, internal/states/statefile/version4.go
Resolves #355
1.6.0
- prevent future possible incompatibility with states that include unknown `check` block result kinds.
=> Backport from 1.5.x: Ignore unknown check results on decode

.github/workflows/pr-lint.yml
As the `pr-opened.yml` does run for first time contributors also the `pr_lint` should, we didn't change anything regarding the settings of the repo, using this event type instead of `pull_request` should work similar to `pr-opened.yml`
related to #325
1.6.0
-
=> PR lint should use `pull_request_target`

website/docs/language/expressions/types.mdx
=> Backport of clarify types and link to Type Constraints pagedit types into v1.5

.github/workflows/release.yml, .goreleaser.yaml
Fixes #180 
Use `cosign` for OIDC-based signing of the release artifacts
- Sign the artifact checksums
- Sign the docker iamges
1.6.0
=> Sign release artifacts

CHANGELOG.md
Resolves #357 
Note: this PR only updates the Changelog per the original PR under MPL (See attached issue), as code seems to be updated already
1.6.0
=> Backport: Relocate localterraform.com aliasing to backend configurators

README.md
The documented Slack Invite link had expired.  Here's the updated link.
relates to #392 
Immediate change to docs, that does not need to be versioned.
n/a
n/a
=> Issue-392: Slack Invite link needs updated

internal/backend/remote-state/azure/arm_client.go, internal/backend/remote-state/azure/backend_state.go, internal/backend/remote-state/azure/client.go, internal/backend/remote-state/consul/client.go, internal/backend/remote-state/cos/client.go, internal/backend/remote-state/gcs/backend.go, internal/backend/remote-state/gcs/client.go, internal/backend/remote-state/http/backend.go, internal/backend/remote-state/http/client.go, internal/backend/remote-state/inmem/backend.go, internal/backend/remote-state/kubernetes/backend.go, internal/backend/remote-state/kubernetes/backend_state.go, internal/backend/remote-state/oss/backend.go, internal/backend/remote-state/oss/client.go, internal/backend/remote-state/pg/backend_state.go, internal/backend/remote-state/s3/client.go, internal/backend/remote/backend.go, internal/backend/remote/backend_common.go
This wraps formatted errors in `internal/backend` using the `%w` directive instead of `%v` or `%s`. I left the tests alone.
part of #395
=> internal/backend: wrap formatted errors

internal/command/init.go, internal/getproviders/package_authentication.go, internal/getproviders/package_authentication_test.go, internal/getproviders/registry_client.go, internal/getproviders/registry_source_test.go, internal/providercache/installer.go
RFC: #266 
Summary:
- Introduced a dedicated function `shouldEnforceGPGValidation()` to determine if GPG validation should be enforced.
- GPG validation is now prioritized if signing keys are provided, ensuring a secure-by-default approach.
- Addressed a minor typo in comments for clarity.
Details:
- The new method simplifies the logic in `AuthenticatePackage()` and can be reused if needed in other parts of the code.
- By checking for the presence of signing keys first, we ensure that validation takes precedence over environment variable configurations.
- A TODO has been added to discuss how unvalidated packages should be represented in the result, suggesting the potential use of a hardcoded "UNKNOWN" value.
Note: Further consideration is required on how best to represent unvalidated …
=> [RFC Implementation] Bypass gpg validation of packages if the registry does not provide any keys

README.md
=> Fix slack invite with a link that never expires.

internal/backend/remote-state/http/client.go, internal/backend/remote-state/http/server_test.go
This fixes the test that started failing between go1.20 and 1.21.
Changes in `tls/crypto` to conform with RFC 5246 and RFC 8446 are described:
> For TLS 1.3 connections, if the server is configured to require client authentication using [RequireAnyClientCert](https://tip.golang.org/pkg/crypto/tls/#RequireAnyClientCert) or [RequireAndVerifyClientCert](https://tip.golang.org/pkg/crypto/tls/#RequireAndVerifyClientCert), and the client does not provide any certificate, the server will now return the "certificate required" alert.
This broke an error string comparison that expected the old message that included "bad certificate."
This uses the `%w` directive to wrap the errors from `httpclient.httpRequest()` so that they can be unwrapped in `TestMTLSServer_NoCertFails()`.
This is one of the …
=> backend/remote-state/http: tests support go1.21

internal/legacy/helper/schema/backend.go, internal/legacy/helper/schema/field_reader_config.go, internal/legacy/helper/schema/field_reader_multi.go, internal/legacy/helper/schema/field_writer_map.go, internal/legacy/helper/schema/provider.go, internal/legacy/helper/schema/provisioner.go, internal/legacy/helper/schema/resource.go, internal/legacy/helper/schema/resource_diff.go, internal/legacy/helper/schema/resource_timeout.go, internal/legacy/helper/schema/schema.go, internal/legacy/opentf/resource_address.go, internal/legacy/opentf/schemas.go, internal/legacy/opentf/state.go, internal/legacy/opentf/state_filter.go, internal/legacy/opentf/state_upgrade_v1_to_v2.go
This wraps the errors in `internal/legacy` using the %w directive instead of %v or %s. I left the tests alone.
part of #395
=> internal/legacy: wrap formatted errors

internal/builtin/provisioners/file/resource_provisioner.go, internal/builtin/provisioners/remote-exec/resource_provisioner.go, internal/cloud/backend.go, internal/cloud/backend_common.go, internal/cloud/backend_plan.go, internal/cloud/backend_taskStages.go, internal/cloud/state.go, internal/command/apply.go, internal/command/cliconfig/cliconfig.go, internal/command/cliconfig/credentials.go, internal/command/clistate/local_state.go, internal/command/command.go, internal/command/fmt.go, internal/command/init.go, internal/command/jsonplan/plan.go, internal/command/login.go, internal/command/meta.go, internal/command/meta_backend.go, internal/command/meta_backend_migrate.go, internal/command/meta_config.go, internal/command/meta_providers.go
This wraps formatted errors in internal/builtin, internal/cloud, and internal/command using the %w directive instead of %v or %s. I left the tests alone.
part of #395
=> internal/builtin internal/cloud internal/command Wrap Errors

internal/backend/remote-state/azure/backend_state.go, internal/backend/remote-state/consul/backend_state.go, internal/backend/remote-state/cos/backend_state.go, internal/backend/remote-state/gcs/backend_state.go, internal/backend/remote-state/oss/backend_state.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote/backend_state.go, internal/cloud/backend_taskStages.go, internal/states/statemgr/filesystem.go
This wraps some errors that I missed on my first pass through these packages.
`internal/backend`
`internal/cloud`
`internal/states/statemgr`
There are no user-facing changes here that warrant a CHANGELOG entry.
part of #395
=> Missed Wrapped Errors

website/docs/intro/index.mdx
Resolves #447 
1.6.0
-  Fix broken 404 links in the [website](https://opentofu.org/docs/intro/#community)
=> fix: broken links in website

docs/README.md
This PR fixes the HTML link in the documentation.
Part of [issue 443](https://github.com/opentffoundation/opentf/issues/443).
Resolves [issue 443](https://github.com/opentffoundation/opentf/issues/443).
N/A
This is a change to the documentation and no binary needs to be build.
- Fix HTML link in the documentation.
=> Fix HTML link in contribution guide

internal/lang/funcs/cidr.go, internal/lang/funcs/collection.go, internal/lang/funcs/crypto.go, internal/lang/funcs/datetime.go
This wraps the errors in `internal/lang` using the `%w` directive instead of `%v` or `%s`. I left the tests alone. 
I took extra care in this PR to use `opentf cnnsole` to verify that there were no visible changes to the error messages from the changed functions.
part of #395
=> internal/lang: wrap formatted errors

internal/getproviders/errors.go, internal/getproviders/hash.go, internal/getproviders/package_authentication.go, internal/getproviders/registry_source_test.go
=> Rename internal/getproviders from opentf to opentofu

internal/getproviders/errors.go, internal/getproviders/hash.go, internal/getproviders/package_authentication.go, internal/getproviders/registry_source_test.go
=> rename opentf to opentofu - internal/getproviders

website/docs/language/providers/index.mdx
This PR removes ProviderTable component from docs and preceding description for it. The description was redundant as there hasn't been ProviderTable rendered at all. More info [here](https://github.com/opentofu/opentofu.org/issues/111)
Resolves issue created for opentofu.org website https://github.com/opentofu/opentofu.org/issues/111
1.6.0
- removes "The provider listings use the following badges to indicate who develops and maintains a given provider." from docs about Providers which was missleading
=> remove ProviderTable component from docs

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/rfc.yml, .github/pull_request_template.md, .github/scripts/e2e_test_linux_darwin.sh, .github/scripts/equivalence-test.sh, .github/scripts/get_product_version.sh, .github/workflows/build-Dockerfile, .github/workflows/build-opentf-oss.yml, .github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/compare-snapshots.yml, .github/workflows/pr-lint.yml
I saw this was one of the things not yet in any scope of the rename. I thought I'd throw together a PR and help. But(!): I fully understand that you might have your own order or steps/progress and maybe updating .github settings is planned for later or you want to do it in a different way. I fully understand, please just close this PR, this is totally okay! :-)
Updated links to the new repository (Repo and API links respectively), renamed OpenTF to OpenTofu and 'opentf' to 'tofu'.
I searched for all references, so I am sure that all of them under .github are updated. Hopefully to the right thing.
This also renames the github actions jobs which will cause a discontinuation of log history in the runs It also updates the packages names in the build scripts. I have not yet tested if this …
=> Rename GitHub settings to OpenTofu

internal/command/meta.go, internal/command/meta_config.go, internal/command/output.go, internal/command/plan.go, internal/command/refresh.go, internal/command/show.go, internal/command/validate.go
This wraps the errors in internal/lang using the `%w` directive instead of `%v` or `%s`. I left the tests alone.
Part of #395 
=> internal/command: wrap formatted errors

.github/workflows/build.yml
Retags the docker image built under the `package-docker` job in the build pipeline, as the image was previously being tagged under the `hashicorp` namespace.
part of #451 
1.6.0
- No user facing changes, as the packaged docker image is not available for external users.
=> Retag package docker image

.github/pull_request_template.md
This PR removes a reference in Github's PR template to backport bot, which comes from Hashicorp and won't be used anymore
Resolves #514 
N/A
=> Removing backport bot reference from PR template. No longer needed

internal/plans/dynamic_value.go
=> Fix typo in dynamic_value.go

internal/backend/remote-state/azure/helpers_test.go, internal/backend/remote-state/gcs/backend_test.go
This wraps the test errors in `internal/backend` using the `%w` directive instead of `%v` or `%`s.
Part of #395
=> internal/backend: wrap formatted test errors

internal/states/statefile/read_test.go
This adds `TestReadErrNoState()` to exercise the places where `Read()` can return an `ErrNoState` error.
Fixes #594
=> internal/states/statefile: TestReadErrNoState()

internal/command/command_test.go, internal/command/testing/test_provider.go, internal/command/webbrowser/mock.go
This wraps the test errors in `internal/command` using the `%w` directive instead of `%v` or `%s`.
Part of #395
=> internal/command: wrap formatted test errors

.github/workflows/release.yml
Fixes #591 
It seems like snapcraft complains about `snapcraft login` if `SNAPCRAFT_STORE_CREDENTIALS` is set.
Thus, I've removed snapcraft login and just moved the env var to be available to the whole goreleaser invocation.
Example workflow: https://github.com/opentofu/opentofu/actions/runs/6313959167/job/17173820994
cc @jnsgruk
=> Snapcraft login shouldn't be called when credentials are set via env var.

internal/legacy/tofu/util.go, internal/legacy/tofu/util_test.go, internal/tofu/util.go, internal/tofu/util_test.go
This prunes unused string functions (and their tests) from `internal/tofu` and `internal/legacy/tofu`.
Fixes #610
=> Prune Unused String Functions

internal/communicator/ssh/communicator_test.go, internal/getproviders/mock_source.go, internal/initwd/module_install_test.go
This wraps the test errors in the following packages using the `%w` directive instead of `%v` or `%s`:
`internal/communicator/ssh`
`internal/getproviders`
`internal/initwd`
Fixes #395
=> More Wrapped Tests

.github/scripts/e2e_test_linux_darwin.sh, .github/workflows/build-opentofu-oss.yml, .github/workflows/build.yml
part of #605
fix #609
https://github.com/opentofu/opentofu/actions/runs/6331460912 works
Seems like `hashicorp/actions-go-build@v0.1.7` docs are wrong, they say the `BIN_PATH` is concatenation with `package_name` input but it seems not to change
so using `bin_name`
1.6.0
-
=> Fix build workflow is failing

internal/command/autocomplete.go, internal/command/command.go, internal/command/console.go, internal/command/get.go, internal/command/graph.go, internal/command/init.go, internal/command/providers.go, internal/command/unlock.go, internal/command/workspace_delete.go, internal/command/workspace_list.go, internal/command/workspace_new.go, internal/command/workspace_select.go
Demote the function `ModulePath()` that is exported but used by no other packages.
Fixes #616
=> internal/command: demote modulePath() export

internal/command/get.go, internal/command/init.go, internal/command/providers.go, internal/command/test.go, internal/command/validate.go
This change adds additional information to the help message of `tofu test -test-directory` command (the help message is invoked by `tofu test --help`) to let the user know the command will search for test files both in the local folder and the one specified with the `-test-directory` flag.
Resolves https://github.com/opentofu/opentofu/issues/181
1.6.0
-  `tofu test --help`: description of the `-test-directory` flag includes expected behaviour
=> Alter the help message for test command to print the expected behaviour

website/docs/language/expressions/version-constraints.mdx, website/docs/language/settings/backends/configuration.mdx, website/docs/language/settings/index.mdx
=> Correct docs for `terraform` block

Makefile, website/README.md
The unused website targets in Makefile are removed. They are left over artifacts from terraform repository.
Validating Content part of the website README.md is also removed. content-check script doesn't exist in website/package.json. Moreover, it's a hashicorp related script.
fixes #634.
Resolves #
1.6.0
-
=> Enhance the documentation to show how to run the docs website locally

internal/backend/remote-state/kubernetes/backend.go, internal/backend/remote-state/kubernetes/backend_state.go, internal/backend/remote-state/kubernetes/backend_test.go
internal/backend/remote-state/kubernetes: demote KubernetesSecretClient()
internal/backend/remote-state/kubernetes: prune unused error
internal/backend/remote-state/kubernetes: demote KubernetesLeaseClient()
This demotes two needlessly exported functions and prunes the unused `noConfigError`.
Fixes #620
=> internal/backend/remote-state/kubernetes: Demote Exported Functions

CHANGELOG.md, internal/tofu/eval_import.go, internal/tofu/eval_import_test.go
- Update `evaluateImportIdExpression` to append diagnostics for sensitive import IDs.
- Create `eval_import_test.go` with unit tests to cover various cases for import ID evaluation, including `nil`, `null`, `unknown`, `sensitive`, and valid values.
- Fixes an edge case where a nil expression passed to the ID parser would panic
These changes ensure that the function correctly handles various edge cases and reports appropriate errors.
Resolves #664 
1.6.0
Fixed panic when using sensitive inputs for the ID field of an import configuration block
-
=> Add sensitivity check for import configuration block IDs and comprehensive test coverage

CODE_OF_CONDUCT.md, Dockerfile
Found two places where OpenTF was still being used
1.6.0
- Now both CODE_OF_CONDUCT and Dockerfile state OpenTofu instead of OpenTF
=> chore: moving from opentf to opentofu in CODE_OF_CONDUCT and Dockerfile

CHANGELOG.md
I found a typo in CHANGELOG.md where OPENTF was still used.
1.6.0
- The CHANGELOG.md now correctly calls the OPENTOFU_ENFORCE_GPG_VALIDATION env variable
=> docs: fixing OPENTOFU_ENFORCE_GPG_VALIDATION

website/docs/language/attr-as-blocks.mdx
As a native English speaker, I find the expression "recommend to use" very awkward.  I propose we eradicate it from the documentation.
=> Fix wording in documentation

CHANGELOG.md, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go
Release 1.6.0 broke the ability to use s3 key aliases in the s3 backend. This change adjusts the tests, and validation of kms key arn's to look for aliases
Resolves #669
1.6.0
-  Fixes the ability to use KMS key aliases in the S3 backend
=> fix(s3): allow aliases for kms key

CHANGELOG.md, internal/cloud/state.go, internal/cloud/state_test.go, internal/cloud/testing.go
Resolves #687 
Ported MPL code from https://github.com/hashicorp/terraform/pull/33834 - Seems like we ported some of it already
1.6.0
-
=> Consider missing `x-terraform-snapshot-interval` for State Snapshot

internal/cloud/backend.go, internal/cloud/backend_apply.go, internal/cloud/backend_apply_test.go, internal/cloud/backend_plan.go, internal/cloud/backend_plan_test.go, internal/command/cloud.go, internal/command/helper.go, internal/command/init.go, internal/command/init_test.go, internal/command/jsonformat/README.md, internal/command/login.go, internal/command/login_test.go, internal/command/meta_backend.go, internal/command/meta_backend_migrate.go, internal/command/testdata/login-tfe-server/tfeserver.go, internal/configs/module.go, internal/configs/module_test.go
As part of https://github.com/opentofu/opentofu/issues/702
Removes all mentions of `Terraform Cloud`, in favor of `cloud backend`, in the codebase.
Specifically for user-facing outputs of the OpenTofu CLI
1.6.0
-
=> Remove all Terraform Cloud mentions in STDOUTs in the codebase

internal/backend/remote/backend_context.go, internal/builtin/providers/tf/data_source_state.go, internal/configs/module.go, internal/configs/provisioner.go, internal/lang/funcs/descriptions.go, internal/legacy/tofu/state.go, internal/logging/panic.go, internal/repl/session.go
As part of https://github.com/opentofu/opentofu/issues/702
Removes all leftover mentions of Terraform in the codebase, specifically for user-facing outputs of the OpenTofu CLI
1.6.0
-
=> Remove all Terraform mentions in STDOUTs in the codebase

.github/scripts/compare-release-versions.sh, .github/workflows/release.yml
I'm adding a check to the release deployment workflow that will compare the triggering tag against the contents of the version/VERSION file.
Read the tag being passed in by GITHUB_REF context and compare it the version file. People rely on these versions being identical and since the update of the file is manual it could be missed.
I've tested this process in another repo. Keep in mind that if you modify default behaviour like continue-on-error in this repo, this may behave differently.
```bash
./.github/scripts/compare-release-version.sh
shell: /usr/bin/bash -e {0}
The VERSION file could not be found. Please create a VERSION file in the version/ directory. The contents of version should match the tag without the v prefix.
Error: Process completed with exit code 1.
```
```bash
Run …
```
=> Add compare versions script

cmd/tofu/commands.go, cmd/tofu/experiments.go, cmd/tofu/help.go, cmd/tofu/main.go, cmd/tofu/main_test.go, cmd/tofu/working_dir.go
This demotes the exported functions `ExperimentsAllowed()` and `WorkingDir()`. This also demotes several exported variables relating to commands.
Fixes #657
=> cmd: Demote Exported Functions and Variables

.github/workflows/build-Dockerfile
Resolves #721
1.6.0
-  Removes reference to HashiCorp managed docker mirror in github workflows. No user facing change.
=> (#721) remove reference to Hashicorp docker mirror in workflow

.github/scripts/compare-release-versions.sh
This change adds a license I missed when writing the compare-release-versions script for the release workflow version comparison.
Relates to #720 
N/A This can go in anytime, asap ideally since it's a license.
ENHANCEMENTS
-  Update license for compare-release-versions script. Not user facing.
=> Add the license to compare-release-versions.sh

internal/plugin/grpc_provider.go, internal/plugin/grpc_provider_test.go, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go, internal/providers/mock_schema_cache.go
Fixes https://github.com/opentofu/opentofu/issues/688
The global provider cache was never used, as the cache was queried only if `ServerCapabilities.GetProviderSchemaOptional` was true, even though the `GetSchema` request didn't yet happen, so this data was always `false`
I changed to logic to only **put** the schema in the cache if the `GetProviderSchemaOptional` capability is on, and always fetch the schema if it's in the cache
Also added unit tests for the bug (had to deal with the fact that currently the SchemaCache leaks between tests, and "luckily" it didn't yet affect the results of the unit tests)
1.6.0
-
=> Fix: Global provider schema cache is never used

Dockerfile
OpenTofu is unable to fetch modules from Git repository without `git` binary in PATH.
Resolves #750
1.6.0
- Fix module installation when OpenTofu runs in container.
=> Provide git for module installation

website/docs/intro/vs/index.mdx
Update https://opentofu.org/docs/intro/vs/ to help readers compare OpenTofu to Terraform.
Resolves #736
=> Add comparison to Terraform link

README.md, SECURITY.md
=> Added Security disclousure policy

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go, website/docs/language/settings/backends/s3.mdx
This adds support for both assume_role configurations:
```hcl
terraform {
backend "s3" {
bucket = "opentofu-state-prod"
key    = "network/opentofu.tfstate"
region = "us-east-1"
assume_role = {
role_arn = "arn:aws:iam::ACCOUNT-ID:role/Opentofu"
}
}
}
```
```hcl
terraform {
backend "s3" {
bucket = "opentofu-state-prod"
key    = "network/opentofu.tfstate"
region = "us-east-1"
role_arn = "arn:aws:iam::ACCOUNT-ID:role/Opentofu"
}
}
```
Resolves https://github.com/opentofu/opentofu/issues/747
1.6.0
-
=> Backend/S3: Extract `assume_role` as a separate block

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, website/docs/language/settings/backends/s3.mdx
Resolves https://github.com/opentofu/opentofu/issues/699
Added support for `forbidden_account_ids` and `allowed_account_ids` arguments.
1.6.0
-
=> S3 backend add account ID whitelisting arguments

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/tofu/context_plugins.go
Right now there's no way to know if the cache was hit, which makes debugging harder.
=> Improve logging of global provider schema cache hits.

internal/backend/backend.go, internal/backend/local/backend.go, internal/backend/local/backend_local_test.go, internal/backend/remote-state/pg/backend_test.go, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote/backend.go, internal/backend/testing.go, internal/builtin/providers/tf/data_source_state.go, internal/builtin/providers/tf/data_source_state_test.go, internal/cloud/backend.go, internal/command/command_test.go, internal/command/init.go, internal/command/meta_backend.go, internal/command/plan_test.go, internal/legacy/helper/schema/backend.go
Given that many state backend methods use contexts in their calls, we will make the related interfaces accept context as an input to all methods. Since it's a ton of work, we will go one by one, starting with a method where the context is not yet used (ConfigSchema) in any of the implementations.
related to #753
1.6.0
n/a, it's a purely internal change
=> Make backend.ConfigSchema accept a context

internal/backend/backend.go, internal/backend/init/deprecate_test.go, internal/backend/init/init.go, internal/backend/local/backend.go, internal/backend/local/backend_local_test.go, internal/backend/remote-state/oss/backend_test.go, internal/backend/remote-state/pg/backend_test.go, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote/backend.go, internal/backend/remote/backend_test.go, internal/backend/remote/testing.go, internal/backend/testing.go, internal/builtin/providers/tf/data_source_state.go, internal/builtin/providers/tf/data_source_state_test.go, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/testing.go, internal/command/meta_backend.go, internal/legacy/helper/schema/backend.go, internal/legacy/helper/schema/backend_test.go
Given that many state backend methods use contexts in their calls, we will make the related interfaces accept context as an input to all methods. Since it's a ton of work, we go one by one. This time it's a method (PrepareConfig) where the context is not yet used in any of the implementations.
related to https://github.com/opentofu/opentofu/issues/753
1.6.0
n/a, it's a purely internal change
=> Make backend.PrepareConfig accept a context

internal/backend/remote-state/s3/backend.go
When both allowed and forbidden account lists are empty, we can skip the account verification.
Relates to #699 
1.6.0
-
=> backend/s3: skip account verification when no constraints given

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, website/docs/language/settings/backends/s3.mdx
Improving feature parity with the AWS provider by adding support for custom CA bundle.
Resolves #692
1.6.0
-
=> Backend/S3: Add support for custom CA bundle

internal/backend/backend.go, internal/backend/local/backend.go, internal/backend/local/backend_local_test.go, internal/backend/remote-state/pg/backend_test.go, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote/backend.go, internal/backend/remote/backend_test.go, internal/backend/remote/testing.go, internal/backend/testing.go, internal/builtin/providers/tf/data_source_state.go, internal/builtin/providers/tf/data_source_state_test.go, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/testing.go, internal/command/meta_backend.go, internal/legacy/helper/schema/backend.go, internal/legacy/helper/schema/backend_test.go
Given that many state backend methods use contexts in their calls, we will make the related interfaces accept context as an input to all methods. Since it's a ton of work, we go one by one. This time it's a method (Configure) where the context is used in some of the implementations.
related to #753
1.6.0
n/a, it's a purely internal change
=> Make backend.Configure accept a context

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/validate.go, website/docs/language/settings/backends/s3.mdx
Adds support for `assume_role_with_web_identity` block.
```
terraform {
backend "s3" {
bucket = "mybucket"
key    = "my/key.tfstate"
region = "us-east-1"
assume_role_with_web_identity = {
role_arn           = "arn:aws:iam::ACCOUNT-ID:role/Opentofu"
web_identity_token = "<token value>"
}
}
}
```
Resolves #689 
1.6.0
-
=> Backend/s3: Add support for `assume_role_with_web_identity` block

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, website/docs/language/settings/backends/s3.mdx
Adds the `sts_region` argument.
Resolves #695 
1.6.0
-
=> Backend/S3: Allow use of an alternative region for STS operations

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, website/docs/language/settings/backends/s3.mdx
Adding `ec2_metadata_service_endpoint` and `ec2_metadata_service_endpoint_mode` to support overriding the EC2  Metadata Service endpoint.
Resolves #693 
1.6.0
-
=> Backend/S3: Add support for overriding EC2 Metadata Service endpoint

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, website/docs/language/settings/backends/s3.mdx
Adds `retry_mode` attribute.
Resolves #698 
1.6.0
-
=> Backend/S3: Allow specifying retry mode for AWS API requests

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, website/docs/language/settings/backends/s3.mdx
Adds HTTP parameters.
Resolves #694 
1.6.0
-
=> Backend/S3: Add HTTP parameters for parity with AWS Provider

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, website/docs/language/settings/backends/s3.mdx
- Adds support for the `use_path_style` argument.
- Deprecates the `force_path_style` argument.
Resolves #783 
1.6.0
-
=> Backend/S3: Add support for `use_path_style`

CHANGELOG.md, internal/backend/local/backend_local.go, internal/command/init.go, internal/tofumigrate/testdata/mention/main.tf, internal/tofumigrate/testdata/nomention/main.tf, internal/tofumigrate/tofumigrate.go, internal/tofumigrate/tofumigrate_test.go
If you're migrating from Terraform to OpenTofu and run `tofu init` on a codebase and statefile which references providers like `hashicorp/aws` then the code will be interpreted as `registry.opentofu.org/hashicorp/aws` while in the statefile you'll still have `registry.terraform.org/hashicorp/aws`. In this case, `tofu init` will fetch both copies, one from each of the registries.
That is not intuitive and not what the user would expect, so this code makes it so that if a provider in the old registry is addressed in the statefile but not in the code, then we assume there was no intention to fetch from the HashiCorp registry, and translate the providers in-memory. You can still specify the full path in the code to override this behavior.
The statefile will be updated on the first `tofu …
=> Stop reading providers from the HashiCorp registry based on the statefile if not specified in code.

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go, website/docs/language/settings/backends/s3.mdx
Adds support for customizing the AWS API endpoints.
Resolves #775 
1.6.0
-
=> Backend/S3: Custom Service Endpoint Configuration

internal/backend/remote/backend.go, internal/cloud/backend.go, internal/command/login.go
Updates  user-agent to use opentofu if go-tfe library is used (login, remote and cloud backends)
Resolves #806
1.6.0
-
=> Update user-agent from go-tfe to opentofu where go-tfe is used

internal/checks/state_report.go, internal/tofu/graph_builder_eval.go, internal/tofu/graph_builder_plan.go, internal/tofu/node_module_variable.go, internal/tofu/node_module_variable_test.go, internal/tofu/node_root_variable.go, internal/tofu/node_root_variable_test.go, internal/tofu/transform_module_variable.go, internal/tofu/transform_variable.go
The original functionality of not validating during "apply" was added in c9bc7e8.  This unfortunately caused destroy to break as the validation checks were not pre-populated.
The change adopted by Terraform was to only run the validations if the action is not destroy: https://github.com/hashicorp/terraform/pull/34101
I decided to take a different approach and instead remove the special case around validating only during planning (and partially during apply. Additional calls into validation are cached during the plan -> apply cycle and don't incur a dramatic performance penalty.  I also believe the approach is simpler and easier to understand.
Resolves #817 
1.6.0
* Addresses crash during tofu destroy inside module with variable validation.
=> Fix crash during destroy planning due to validation

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client.go
This PR started out addressing #821, but ended up being an investigation of the workflow itself instead of the not-adopted validation changes.
* Add in the relevant context hooks for aws-go-sdk-base logging.  This is required to easily debug the rest of the changes.
* Missing proto:// backwards compatibility
- BaseEndpoint -> EndpointResolver fixed many of the issues related to non-proto endpoints.
- Unfortunately it did not cover all cases, the main one I identified was in the aws-go-sdk-base middleware.
- A workaround was added such that any non-proto endpoints would automatically have the https:// prefix added.
- This is hopefully a sane default, and comes with a debug message that should help track down if it ever causes issues.
* PutObject checksum calculation
- `skip_s3_checksum` …
=> Address s3 compatible remote state issues + logging

.github/workflows/release.yml
Succeeded (with some tag hackery 20d8fec51670aff84419005d32a9190b4759aef6 due to permissions) in https://github.com/opentofu/opentofu/actions/runs/6819063138
This broke in alpha3 -> alpha4 with https://github.com/opentofu/opentofu/pull/751.  Before we were just setting up the files for a building a docker container and not actually executing any commands within.  Unfortunately, this PR now causes docker to actually have to use qemu to cross-execute code inside the container, a understandable miss at the time.
The fix is to make sure the cross quemu tools are properly installed in the github runners, as referenced at the bottom of https://goreleaser.com/cookbooks/multi-platform-docker-images/#other-things-to-pay-attention-to
The `0.252 exec /bin/sh: exec format error` is cryptic and not …
=> Pull in docker cross buildx tooling

CHANGELOG.md, go.mod, go.sum, internal/configs/configschema/decoder_spec_test.go
- HCL version was updated to the latest release
- To add possibility of additional hooks when running `for_each`(see [details](https://github.com/hashicorp/hcl/pull/634)) 
Resolves #820, #819
1.6.0-alpha5
- Updated hcl from 2.18.0 to 2.19.1. Find the details changes [here](https://github.com/hashicorp/hcl/compare/v2.18.1...v2.19.1).
- `tofu init`: Fixed subsequent runs for s3 backend ([#820](https://github.com/opentofu/opentofu/issues/820))
=> Update hcl version to v2.19.1

internal/getproviders/package_authentication.go, internal/getproviders/package_authentication_test.go, internal/getproviders/registry_client.go, internal/getproviders/registry_source_test.go
Example:
```
- Installing hashicorp/tfcoremock v0.2.0...
[WARN] Provider hashicorp/tfcoremock (registry.opentofu.org) gpg key expired, this will fail in future versions of OpenTofu: 'https://github.com/opentofu/terraform-provider-tfcoremock/releases/download/v0.2.0/terraform-provider-tfcoremock_0.2.0_linux_amd64.zip'
```
Resolves #822
1.6.0
* Allow providers with expired gpg keys (with a warning)
=> Allow expired provider pgp keys, with warning

internal/command/init.go, internal/command/init_test.go
=> keep init wording consistent in internal/command/init.go

.github/pull_request_template.md
This primarily caused confusion of where the CHANGELOG was supposed to be updated.  The current bot that requests the actual CHANGELOG.md file be updated is a much better reminder.
=> Remove draft CHANGELOG section of PR template

CHANGELOG.md
This is a followup to https://github.com/opentofu/opentofu/pull/840 to move the relevant changelog items to the correct location, something I missed in the initial PR.
=> Move S3 CHANGELOG entries I added to S3 upgrade section

internal/backend/remote-state/s3/client.go
Matching GetObject, though we can't re-use the code since it's a distinct struct.
Broken in #840
Resolves #863
@Yantrio suggests that since this bug was not released in a stable release, it does not need to go in the CHANGELOG.md
1.6.0
=> S3 Client HeadObject requires SSE parameters

.github/workflows/release.yml, website/docs/intro/install.mdx
Debian based instructions:
```bash
curl -s https://packagecloud.io/install/repositories/opentofu/tofu/script.deb.sh -o /tmp/tofu-repository-setup.sh
sudo bash /tmp/tofu-repository-setup.sh
sudo apt install tofu
```
RedHat based instructions:
```bash
curl -s https://packagecloud.io/install/repositories/opentofu/tofu/script.rpm.sh -o /tmp/tofu-repository-setup.sh
sudo bash /tmp/tofu-repository-setup.sh
sudo yum install tofu
```
Resolves #567 
This won't be able to be tested until the next alpha / rc release.  I have run the package_cloud commands locally to test the workflow and to backfill alpha4
TODO:
=> Upload packages to PackageCloud during release action

website/docs/intro/install.mdx
I missed an argument when copying to the docs.  I have copied and pasted the instructions verbatum to double check it on debian and fedora.
Part of #860 
1.6.0
=> Add missing argument to PackageCloud install instructions

internal/backend/remote-state/s3/backend_test.go, scripts/test/state_backends/s3.sh
Changes:
* Fixes assume_role config in specific tests that check tfdiag
* Renames `tf -> tofu` and `terraform -> opentofu` in bucket/config names
* Adds helper script for #745
Part of #745
1.6.0
=> Update s3 remote state tests

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/configs/configschema/coerce_value.go
This is the first part of #875 and fixes the main issue reported.  The schema validation for backends has two paths, one from data blocks, the other from backend blocks.  At the moment, backend blocks pre-populates empty maps as shown in the issue.  This will be fixed in a followup PR.
This PR fixes the schema optional fields, adds a test for the minimum set of fields required, and also improves the user facing errors when they are missing multiple fields (stable key sort).
Resolves #875
1.6.0
=> Fix S3 Remote State Backend Validation

.goreleaser.yaml
=> Use correct location for LICENSE file during installation (opentofu instead of nfpm)

CHANGELOG.md, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/errors.go, website/docs/cli/cloud/settings.mdx
Resolves #814 
1.6.0-alpha6
- Fixes cloud backend configuration order: `TF_WORKSPACE` overwrites `workspaces` attributes
- Removed deadcode `WithEnvVars`
- Enhanced tests for the cloud backend method `setConfigurationFields` and `PrepareConfig`
- To follow expected `tofu init` behaviour
=> Fix workspace name overwrite with env var TF_WORKSPACE

internal/configs/configschema/internal_validate.go, internal/configs/configschema/internal_validate_test.go
Resolves #539
Note: the target file seems to be not gofmt'd. I left it as-is for now.
1.6.0
=> Fixes #539: Setting both "Type" and "NestedType" removes other validation error messages

internal/registry/client.go, internal/registry/client_test.go, internal/registry/response/module_download.go, internal/registry/test/mock_registry.go, website/docs/internals/module-registry-protocol.mdx
Resolves #900 
1.6.0
- Added handling of the registry response in line with the server's [contract](https://github.com/opentofu/registry-stable/blob/c54f44a6b912bcb134c9727ab594af0be0e2e5bd/src/internal/v1api/responses.go#L5-L9).
- The http response status codes 200 and 204 are treated separately now: 200 - read location from the body, 204 - read location from the header.
For the OpenTofu CLI to be compliant with the OpenTofu registry "v1" protocol.
=> Align CLI logic to be compliant with the stable registry module protocol

CODEOWNERS, MAINTAINERS
Resolves #918 
- Added the core team as the code owners
- Added the core team as the maintainers
- Clarity
- CNCF application
=> Add codeowners and maintainers

website/docs/intro/install/deb-convenience.sh, website/docs/intro/install/deb-step1.sh, website/docs/intro/install/deb-step2.sh, website/docs/intro/install/deb-step3.sh, website/docs/intro/install/deb-step4.sh, website/docs/intro/install/deb.mdx, website/docs/intro/install/deb.sh, website/docs/intro/install/docker-compose.yaml, website/docs/intro/install/install-yum.sh, website/docs/intro/install/install-zypper.sh, website/docs/intro/install/repo-yum.sh, website/docs/intro/install/repo-zypper.sh, website/docs/intro/install/rpm-convenience-yum.sh, website/docs/intro/install/rpm-convenience-zypper.sh, website/docs/intro/install/rpm.mdx, website/docs/intro/install/rpm.sh, website/docs/intro/install/test-install-instructions.sh
Currently, the installation instructions for RPM-based distributions are incorrect since we are not GPG-signing the packages. This change turns off GPG verification for those packages. This is preferable to disabling the GPG check on the command line because the GPG key will likely change anyway when we enable package signing.
The change also contains a fix in the convenience script instructions for openSUSE LEAP users, offering instructions for Zypper instead of Yum.
As an additional change, this commit also includes testing scripts for the installation instructions on various distributions to avoid such errors in the future. The test script can be invoked on a Linux distribution with Docker/Podman installed using
`test-install-instructions.sh`:
```
$ ./test-install-instructions.sh
[+] …
```
=> Fixes #913: Incorrect installation instructions for RPM

internal/command/e2etest/automation_test.go, internal/command/e2etest/init_test.go, internal/command/e2etest/primary_test.go, internal/command/e2etest/providers_mirror_test.go, internal/command/e2etest/providers_tamper_test.go, internal/command/e2etest/provisioner_plugin_test.go, internal/command/e2etest/provisioner_test.go, internal/command/e2etest/version_test.go, internal/configs/test_file.go, website/docs/internals/module-registry-protocol.mdx, website/docs/internals/provider-registry-protocol.mdx
Resolves #891 by updating references from hashicorp.com to opentofu.org, where appropriate.
During the process, I noticed the test in
`package_authentication_test.go`
uses [accounts from
hashicorp.com](https://github.com/opentofu/opentofu/blob/70dd385136bb4d1fa2875672a06905b864ecb41b/internal/getproviders/package_authentication_test.go#L682C2-L682C2), which probably should be updated.
Resolves 891
1.6.0
=> Change hashicorp.com to opentofu.org where appropriate

Makefile, internal/backend/remote-state/azure/README.md, internal/backend/remote-state/azure/backend_test.go
Part of #745
Due to the number of steps involved and what they do behind the scenes, the guide is in form of a runbook. We may want to fully automate it eventually.
One test is removed with a relevant commit message. I don't think it's worth spending more time on it.
=> Add Azure integration test runbook.

Makefile, internal/backend/remote-state/consul/Dockerfile, internal/backend/remote-state/consul/backend_test.go, internal/backend/remote-state/consul/client_test.go
Resolves #911 
1.6.0
- Added the makefile rule to trigger the integration test with Consul
- Added dockerfile with deps definition to provision local env
- Fixed tests definition: a Consul server provisioned by every test is being stopped to cleanup and free the ports
- To ensure the OpenTofu stability with various backends
=> Add dependencies for integration tests with Consul as backend

.goreleaser.yaml
=> Make goreleaser create draft releases instead of full releases, so that we can customize the description.

.github/workflows/website.yml, website/Dockerfile, website/README.md, website/docker-compose.build.yml, website/docker-compose.yml
This PR adds a dev server that's runnable directly from the main repository. It also adds a GitHub workflow that checks if the website build passes.
1.6.0
=> website: Dev server

website/docs/intro/install/deb-convenience.sh, website/docs/intro/install/deb-step2.sh, website/docs/intro/install/deb-step3.sh, website/docs/intro/install/repo-yum.sh, website/docs/intro/install/rpm-convenience-yum.sh, website/docs/intro/install/rpm-convenience-zypper.sh
This PR updates the installation instructions to `packages.opentofu.org`. However, the convenience script will need rewriting as the script still loads from packagecloud.io (see [this issue](https://github.com/opentofu/opentofu/issues/979)).
1.6.0
=> Updated installation instructions to packages.opentofu.org

internal/command/e2etest/init_test.go, internal/command/init.go, internal/initwd/module_install.go
Added a helpful message to point people at the correct location to submit modules/providers.
```hcl
terraform {
required_providers {
foo = {
source = "invalid"
}
}
}
```
```
$ ~/go/bin/tofu init
Initializing the backend...
Initializing provider plugins...
- Finding latest version of hashicorp/invalid...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/invalid: provider registry registry.opentofu.org does not have a provider named registry.opentofu.org/hashicorp/invalid
│ 
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are currently depending on hashicorp/invalid, run the following command:
│     tofu …
```
=> 904 missing provider module message

internal/cloud/backend_plan_test.go, internal/cloud/backend_show_test.go, internal/cloud/backend_test.go, internal/cloud/testing.go
We don't want opentofu to connect to app.terraform.io during testing, unless explicitly specified.
Validation was performed by unplugging my network cable and adding the skipIfTFENotEnabled(t) where nessesary.
Related to https://github.com/opentofu/opentofu/issues/898
1.6.0
=> Add gate for TFE tests that use the network

internal/command/e2etest/provider_dev_test.go, internal/command/init.go, internal/command/init_test.go, internal/providercache/installer.go
This both improves the error message display in tfdiags and lists the available versions in TF_LOG=debug to help trace down issues.
IMO "can't resolve" is clearer than "can't list" for any generic provider error.  Can't resolve makes you read the rest of the error message instead of assuming it's a registry issue
Result from the example in the issue:
```
╷
│ Error: Failed to resolve provider packages
│ 
│ Could resolve provider cloudflare/cloudflare: no available releases match the given constraints 4.14.0, 4.19.0
```
With TF_LOG=debug
```
- Finding cloudflare/cloudflare versions matching "4.14.0, 4.19.0"...
2023-12-12T12:14:24.716-0500 [DEBUG] Service discovery for registry.opentofu.org at https://registry.opentofu.org/.well-known/terraform.json
2023-12-12T12:14:25.061-0500 [DEBUG] GET …
```
=> Improve unclear provider resolver error messages

internal/backend/remote/backend.go, internal/cloud/e2e/main_test.go, internal/command/apply_test.go, internal/command/e2etest/automation_test.go, internal/command/e2etest/init_test.go, internal/command/e2etest/main_test.go, internal/command/e2etest/make-archive.sh, internal/command/e2etest/module_archive_test.go, internal/command/e2etest/primary_test.go, internal/command/e2etest/provider_dev_test.go, internal/command/e2etest/provider_plugin_test.go, internal/command/e2etest/providers_mirror_test.go, internal/command/e2etest/providers_tamper_test.go, internal/command/e2etest/provisioner_plugin_test.go, internal/command/e2etest/provisioner_test.go, internal/command/e2etest/remote_state_test.go, internal/command/e2etest/test_test.go, internal/command/e2etest/tf_provider_data_test.go, internal/command/e2etest/unmanaged_test.go, internal/command/e2etest/version_test.go, internal/command/jsonprovider/doc.go, internal/getproviders/mock_source.go, internal/getproviders/registry_client.go, internal/initwd/doc.go, internal/lang/references.go, internal/plugin/discovery/requirements.go, internal/plugin/grpc_provider.go, internal/plugin6/doc.go, internal/plugin6/grpc_provider.go
Hopefully the last search of the codebase for replacing terraform with tofu/opentofu
Relates to #898
1.6.0
=> Find additional places where terraform should be replaced with tofu

.github/workflows/release.yml, .goreleaser.yaml
This PR adds GPG signing for Debian and RPM packages so they can be verified when downloaded from the package repository.
Resolves #915
1.6.0
=> Fixes #915: GPG signing of Debian and RPM packages

website/docs/cli/commands/output.mdx, website/docs/cli/commands/state/list.mdx, website/docs/cli/commands/state/pull.mdx, website/docs/cli/commands/state/push.mdx, website/docs/cli/commands/state/show.mdx, website/docs/cli/commands/workspace/new.mdx, website/docs/language/modules/sources.mdx
Resolves https://github.com/opentofu/opentofu/issues/530
As part of the renaming process to opentofu, several discrepancies have surfaced in our documentation.
To fix them we:
1. Renamed `X-OpenTofu-Get` to `X-Terraform-Get`.
2. Renamed `tofu.tfstate` to `terraform.tfstate`.
Items in the issue that weren't addressed:
1. `tofu.rc` - it's supported in opentofu.
2. `tofu {` is not found.
1.6.0
=> Fix renaming mistakes in docs

CHANGELOG.md, internal/command/init.go, internal/command/init_test.go, internal/command/testdata/init-get-provider-detected-duplicate/child/main.tf, internal/command/testdata/init-get-provider-detected-duplicate/main.tf
When we attempted to change the default namespace from "hashicorp" to "opentofu" we realized that there are no guardrails for when multiple potential duplicates of a provider are specified.
Example:
main.tf requires company/bar with configuration A
module/child.tf requires company/bar with configuration B tofu init finds a single provider company/bar is represented with configuration A + B
company/bar is forked into alt/bar with some additional fixes
main.tf is updated to alt/bar, and module/child.tf is forgotten. tofu init finds two providers, alt/bar with configuration A and company/bar with configuration B
This can cause all sorts of havoc depending on what provider configuration lives where.  It is also nearly invisible to the end user, which is why we added a warning message.
It is …
=> Add a warning when multiple likely forks of a provider are detected

CHANGELOG.md
=> Update changelog for hashicorp / opentofu only warning

.github/scripts/compare-release-version.sh, .github/workflows/release.yml
This PR fixes the tag gating for releases broken in 1022.
1.6.0
=> Fixing release tag gating

Dockerfile
It was removed in
https://github.com/opentofu/opentofu/pull/173/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L16 with no associated comment.
As was was reported in #1031, ssh is required for certain functionality. I've also re-added bash in case it was required for other examples.
Resolves #1031
1.6.0
=> Re-add ssh and bash to Dockerfile

website/docs/intro/install/deb-step2.sh, website/docs/intro/install/deb-step3.sh, website/docs/intro/install/deb.mdx, website/docs/intro/install/repo-yum.sh, website/docs/intro/install/repo-zypper.sh, website/docs/intro/install/rpm.mdx, website/docs/intro/install/test-install-instructions.sh
This PR removes the Packagecloud instructions.
**Note 1:** Special consideration is given to Deb, where we still need to include the Packagecloud GPG key in order to make the repository signed. This is less than ideal, but works for now.
**Note 2:** The instructions need to be re-tested before merging this.
Resolves #980
1.6.0
=> Fixes #980: Remove Packagecloud instructions

website/docs/cli/commands/providers/index.mdx, website/docs/cli/import/importability.mdx, website/docs/cli/plugins/signing.mdx, website/docs/internals/credentials-helpers.mdx, website/docs/internals/module-registry-protocol.mdx, website/docs/intro/index.mdx, website/docs/intro/use-cases.mdx, website/docs/language/data-sources/index.mdx, website/docs/language/files/dependency-lock.mdx, website/docs/language/functions/cidrsubnets.mdx, website/docs/language/import/index.mdx, website/docs/language/modules/develop/publish.mdx, website/docs/language/modules/develop/structure.mdx, website/docs/language/modules/index.mdx, website/docs/language/modules/sources.mdx, website/docs/language/providers/index.mdx, website/docs/language/providers/requirements.mdx
I went through and found a few more references to terraform that should be removed in the docs.  Also fixes some broken links
=> Docs update, remove additional terraform references

internal/lang/funcs/descriptions.go, internal/lang/funcs/encoding.go, internal/lang/funcs/encoding_test.go, internal/lang/functions.go, internal/lang/functions_test.go, website/data/language-nav-data.json, website/docs/language/functions/gunzipbase64.mdx
add terraform function gunzipbase64 as opposite of base64gzip similar to
- base64decode opposite of base64encode
- textdecodebase64 opposite of textencodebase64
- jsondecode opposite of jsonencode
- yamldecode opposite of yamlencode
Resolves #800
1.6.0
terraform function gunzipbase64 can be used as opposite of base64gzip, e.g.
- write base64gzip content to any storage, read it and decode it with gunzipbase64
=> implement gunzipbase64

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, website/docs/language/settings/backends/s3.mdx
The `use_legacy_workflow` S3 backend option uses the legacy authentication workflow, preferring environment variables over backend configuration.
We'd want to stop supporting it gradually, as it'll probably eventually be removed from https://github.com/hashicorp/aws-sdk-go-base.
In this PR, we are:
1. Setting the default to `false`.
2. Adding a deprecation warning.
Resolves https://github.com/opentofu/opentofu/issues/1014
1.7.0
=> Backend/S3: Change default of `use_legacy_workflow` to false and deprecate

CHANGELOG.md, internal/lang/funcs/sensitive.go, internal/lang/funcs/sensitive_test.go, website/docs/language/functions/nonsensitive.mdx
Fixes #394
This is has also been posted to hashicorp/terraform, under PR 33856. Evidence of number of users affected is mentioned there.
The behaviour of nonsensitive in 1.5.x causes an error if nonsensitive is called on a value that is not marked as "sensitive".
The documentation at https://developer.hashicorp.com/terraform/language/functions/nonsensitive offers a rationale
> nonsensitive will return an error if you pass a value that isn't marked as sensitive, because such a call would be redundant and potentially confusing or misleading to a future maintainer of your module.
Other issues describe a set of situations where users are effectively locked into a situation where they can't use derivations of collections of objects where some fields are marked as sensitive into for_each, and …
=> nonsensitive no longer produces error when applied to values that are not sensitive

website/docs/intro/install/homebrew.mdx
Adding missing import statement on `homebrew` installation documentation.
Resolves #1056
=> doc(website): Adding missing import statement on homebrew installation documentation

go.mod, go.sum, internal/command/webbrowser/native.go
Module github.com/cli/browser is a drop-in replacement of github.com/pkg/browser including better WSL and Windows support.
Closes https://github.com/opentofu/opentofu/issues/603
=> Use github.com/cli/browser

go.mod, go.sum, internal/logging/logging.go
Dependency on github.com/coreos/pkg was introduced in commit c047958 as a workaround of a `etcd` bug that was solved in 3.5.
As support for `etcd` was deprecated in 5225565 this workaround is not required anymore.
Resolves #628
=> Drop dep on github.com/coreos/pkg

CHANGELOG.md, internal/lang/funcs/descriptions.go, internal/lang/funcs/encoding.go, internal/lang/funcs/encoding_test.go, internal/lang/functions.go, internal/lang/functions_test.go, website/data/language-nav-data.json, website/docs/language/functions/base64gunzip.mdx
Change the name of the gunzipbase64 function to base64gunzip, so it's more in line with the others.
Adds changelog entry.
Improves #800.
1.7.0
=> Refactor base64gunzip function to be more in line with other functions.

CONTRIBUTING.md
It's referenced in the docs in a few places, but never explicitly explained
=> Add description of Core Team to CONTRIBUTING.md

internal/backend/local/testing.go
`assertBackendStateLocked` was always returning true. It has been updated to return false when it fails. The comments for it and `assertBackendStateUnlocked` have also been updated for clarity.
1.7.0
=> Return false when assertBackendStateLocked fails and update comments for it and assertBackendStateUnlocked

website/docs/cli/commands/test/index.mdx
This fixes [MDX compilation error](https://github.com/opentofu/opentofu.org/actions/runs/7500877361/job/20420431095?pr=99) that popped up after trying to upgrade all deps in the docs:
1.7.0
=> Escape wildcard signs in docs/cli/commands/test/index.mdx

CHANGELOG.md, internal/tofu/context_plan2_test.go, internal/tofu/eval_import.go, internal/tofu/node_resource_abstract.go, internal/tofu/testdata/import-id-reference/main.tf, internal/tofu/testdata/import-id-reference/mod/mod.tf, internal/tofu/transform_reference.go
Imports are attached to their respective modules, but must execute expressions in the root module context.  This PR fixes that and makes sure that refererences to the root module are properly described via the graph.
It is recommended to review this with hide-whitespace (?w=true) turned on as it makes the diff easier to read.
Resolves #1084 
1.7.0, 1.6.1
=> Allow known references in import blocks

internal/tofu/context_plan_test.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go
Currently, if a resource is planned to be destroyed, but the resource has `lifecycle.prevent_destroy = true`, then tofu would show you the error without the plan part for the resource. That means that you wouldn't be able to tell why the resource was about to be destroyed, for example if there was a change in some field that forces recreation
So, we make sure to `writeChanges` in the plan nodes **before** the `prevent_destroy` check. This makes sure the plan changes are saved before it fails
Example:
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
OpenTofu planned the following actions, but then encountered a problem:
-/+ resource "random_integer" "int" {
~ …
```
=> Show resource plan even if it failed plan due to `prevent_destroy`

CHANGELOG.md
Adds CHANGELOG entry for https://github.com/opentofu/opentofu/pull/1060
1.7.0
=> Add CHANGELOG entry for `prevent_destroy` plan fix

website/docs/intro/install/deb-step2.sh, website/docs/intro/install/deb-step3.sh
When facing a hardened umask (e.g. `0027`) the current installation steps aren't sufficient on a Debian family OS.
This PR adds the missing steps.
=> docs(install): add missing steps in Debian family when facing hardened umask

CHANGELOG.md, internal/command/meta_providers.go
A backport of the Global Schema Cache fix in provider acceptance tests - https://github.com/opentofu/opentofu/pull/1054
Related to https://github.com/opentofu/opentofu/issues/1044
1.6.1
=> Fix Global Schema Cache not working in provider acceptance tests - 1.6 backport

internal/command/meta_vars.go, internal/command/test.go, internal/command/test_test.go, internal/command/testdata/test/variables_reference/main.tftest.hcl, internal/command/testdata/test/variables_reference/setup/main.tf
Builds an EvalContext which represents the output state of previously run steps to be used when evaluating variable expressions.
Resolves #1045
1.7.0, 1.6.1
=> Run block variable references

website/docs/language/settings/backends/remote.mdx, website/docs/language/settings/tf-cloud.mdx, website/docs/language/state/remote-state-data.mdx, website/docs/language/values/variables.mdx
1. We had a few broken links in our docs. I fixed them.
2. Added some clarifications in documentation related to `remote` and `cloud` backends.
Resolves https://github.com/opentofu/opentofu/issues/1100
1.7.0
=> Fix broken links and add clarifications in documentation

CONTRIBUTING.md
Now that OpenTofu has reached GA, we need to focus on making the Core Team's process transparent and try to streamline the contribution flow.
=> Add description of issue flow to CONTRIBUTING

TSC_SUMMARY.md
This information has been referenced in a few places, but it is good to have a clear description in the repo to help explain the issue flow and governance.
Also fixed the spelling of Omry Hay's name.
=> Add details on who/what/why the TSC is and list of current members

CHANGELOG.md, internal/legacy/helper/hashcode/hashcode.go, internal/legacy/helper/schema/field_reader_config_test.go, internal/legacy/helper/schema/resource_data_test.go, internal/legacy/helper/schema/resource_diff_test.go, internal/legacy/tofu/state_upgrade_v2_to_v3.go
This PR attempts to fix the failing 32 bit unit tests throughout the codebase. 
It makes the following changes:
This type is only really used in the remote backend packages lately, but nonetheless we should be fixing this.
This fix ensures that we squash the value to 32 bits (signed) and embrace the overflow to introduce consistency between 32 and 64 bit systems.
The previous function used in the test was causing issues with clashing IDs. This commit attempts to fix this by re-working how the unit test generates IDs for the set elements in a way that's both friendly to 32 bit and 64 bit systems
This fixes an issue where we were using strconv.Atoi, and instead we should be enforcing 64-bit conversions here.
We had a bug in the s3 backend role assumption logic that caused an overflow if …
=> Improve stability on 32-bit architectures

website/docs/intro/install/standalone-install.sh
Fixes what I believe is a typo in the standalone install instructions. Should be "grant", not "grand".
Resolves #
1.7.0
=> Fix typo in standalone-install.sh

website/docs/intro/install/standalone-install.sh
=> Backport: Fix typo in standalone-install.sh (#1186)

internal/command/views/validate.go
Remove extra newline in validate output.
before:
```bash
% tofu validate                             
Success! The configuration is valid.
%
```
after:
```bash
% tofu validate                             
Success! The configuration is valid.
%
```
Fixes #765
1.6.1
-  Remove extra newline from validate output
=> command/views: Remove extra newline in validate output

CHANGELOG.md, cmd/tofu/main.go, cmd/tofu/plugins.go, cmd/tofu/provider_source.go, internal/command/cliconfig/cliconfig.go, internal/command/cliconfig/config_unix.go, internal/command/cliconfig/config_unix_test.go, internal/command/cliconfig/config_windows.go, website/docs/cli/config/config-file.mdx, website/docs/language/resources/provisioners/syntax.mdx
This PR introduces support for XDG environment variables. `XDG_CONFIG_HOME` for config and `XDG_DATA_HOME` for plugins.
If `XDG_CONFIG_HOME` is set and `~/.tofurc` or `~/.terraformrc` don't exist, `XDG_CONFIG_HOME/opentofu/tofurc` will be used as config file.
If `XDG_DATA_HOME` is set, plugins will be searched in `XDG_DATA_HOME/opentofu` as well as the default `~/.terraform.d`.
This ensures that existing config and plugins will still get used, but allow users to gradually migrate to the new structure, with and without setting `XDG_*` environment variables.
The CLI ensures that the intermediate config directory exists, so if `XDG_CONFIG_HOME` is set and the default `~/.terraform.d` directory doesn't exist `XDG_CONFIG_HOME/opentofu` is created.
Only affects unix* platforms.
Resolves #303 …
=> Support the XDG Base Directory Specification

CHANGELOG.md, cmd/tofu/commands.go, cmd/tofu/main.go, internal/command/alias.go, internal/command/state_list.go, internal/command/state_mv.go, internal/command/state_rm.go
Adds alias commands for `state list`, `state mv`, and `state rm`. Aliases don't show when listing `state`'s subcommands, and are denoted in each subcommand's help text.
Resolves #1136 
1.7.0
=> Added aliases for `state list`, `state mv`, and `state rm`

internal/backend/remote-state/s3/backend.go, internal/command/jsonplan/plan_test.go
This issue fixes the 2 failing tests in 386 and arm based systems in the alpine build pipelines.
- Resolves issue with integer overflow when constructing the s3 assume role timeout in the backend logic
- Resolves issue where TestEncodePaths was comparing the order of slices, when the order returned from go-cty is non-deterministic (Due to hashing on 32 bit systems dropping half the data).
Resolves #1069 
1.7.0, 1.6.1
=> Resolve more inconsistencies in 32-bit systems

website/docs/cli/config/config-file.mdx
The docs says "The following are the two supported installation method types" and then list three installation methods - fix it.
Resolves #1240 
1.7.0
=> Docs: there're more than two installation methods

internal/command/import.go, internal/configs/import.go, internal/tofu/context_import.go, internal/tofu/context_import_test.go, internal/tofu/context_plan.go, internal/tofu/context_plan2_test.go, internal/tofu/context_walk.go, internal/tofu/eval_context.go, internal/tofu/eval_context_builtin.go, internal/tofu/eval_context_mock.go, internal/tofu/graph_builder_plan.go, internal/tofu/graph_walk_context.go, internal/tofu/node_resource_abstract.go, internal/tofu/node_resource_plan.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/transform_config.go
Related to https://github.com/opentofu/opentofu/issues/1033
Current plan for implementing `for_each` for the `import` block:
1. Prepare `ImportTarget` types and codebase for more dynamic addresses (addresses that are not fully known from the get-go) **<--- You are here**
2. Allow for having a more dynamic address in the `to` field of an `import` block
3. Add `for_each` field for `import` block, and adapt the code for resolving multiple import targets from the same import configuration
Once we implement `for_each` for `import`, there are a couple of things that will not be the same for `ImportTarget`, as they are today:
- The address of the import target is not necessarily fully known from the get go (as it could rely on data that would only be evaluated later on)
- A single import block …
=> Import ForEach: Prerequisite - Prepare codebase for dynamic addresses for `ImportTarget`s

website/docs/intro/install/standalone.mdx
Please add a link to the Linux install docs pointing to the binary hosted at OSU OSL for ppc64le. Newer binaries for ppc64le will be uploaded to this [2] location once a Release is added to the OpenTofu repo. This is in reply to the RFC discussion started here [3]. Thank you :) 
[1] https://osuosl.org/services/powerdev/
[2] https://ftp2.osuosl.org/pub/ppc64el/opentofu/
[3] https://github.com/opentofu/opentofu/issues/1130
=> docs: Add Community Supported Architectures Section to Install Docs - ppc64le

.goreleaser.yaml
**Addition of Tar.gz Archive Format:** The proposal suggests shipping .tar.gz archives alongside the existing .zip archives. This change aims to provide users with an alternative archive format for downloading and using the project.
When introducing multiple archive formats, such as .zip and .tar.gz, it's crucial to provide identifiers(id) for each format to distinguish between them. This ensures clarity and prevents errors when generating archives.
To check if the files are being generated as desired, try running "goreleaser release --snapshot" in terminal. 
Resolves #1097 
1.7.0
=> Enhancement: Introduce .tar.gz Archive Format for Additional Download Option

CHANGELOG.md, internal/command/state_mv.go, internal/command/state_rm.go
This change introduced 2 things
- Improved changelog entry to make it clear what we're adding
- Improved help text to be consistent in ordering (full|alias).
related to: #1220
1.7.0
=> Introduced consistent ordering of aliases in help text

internal/tofu/context_import.go, internal/tofu/context_plan.go, internal/tofu/context_walk.go, internal/tofu/eval_context.go, internal/tofu/eval_context_builtin.go, internal/tofu/eval_context_mock.go, internal/tofu/graph_walk_context.go, internal/tofu/node_resource_plan.go
Fix a race introduced in https://github.com/opentofu/opentofu/pull/1207 (example run [here](https://github.com/opentofu/opentofu/actions/runs/7950028478/job/21701859808?pr=1158))
Access to `imports` of `ResolvedImports` was not _technically_ safe, causing failures in the race tests (A race here shouldn't really have affected the code much for now, as the `ResolvedImports` was only used for validation that all import actions have been satisfied)
Here I fix the race by:
- Introducing a lock for accessing the `imports`
- Changed `ResolvedImports` to be `ImportResolver`, which has its own access functions for reading and writing the resolved imports (in preparation for https://github.com/opentofu/opentofu/pull/1270)
1.7.0
=> Fix race when using `ResolvedImports`

website/docs/intro/install/fedora.mdx, website/docs/intro/install/index.mdx, website/docs/intro/install/rpm.mdx
Since last week OpenTofu is available to be installed in Fedora directly. It took a few more days than I said at FOSDEM ;)
I'm creating this PR with updated doc adding a new section and modifying the rpm doc a bit. I can create an issue if we want to discuss if this is the correct approach.
=> Docs: add Fedora section and minor changes in rpm doc

website/docs/intro/install/docker-pull.sh, website/docs/intro/install/docker-run.sh, website/docs/intro/install/docker.mdx, website/docs/intro/install/index.mdx
Documentation website was lacking a mention of official OpenTofu Docker image.
So I've added it.
See https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1708027559842219
=> Add page about official OpenTofu Docker image

internal/configs/config_build_test.go, internal/configs/config_test.go, internal/configs/experiments_test.go, internal/configs/module_call_test.go, internal/configs/module_merge_test.go
In windows machine, some filepaths filled by OpenTofu have windows style slash
Fix the expected data in unit test to pass in different OS.
Part of https://github.com/opentofu/opentofu/issues/1201
=> fix: internal/config unit test for windows

website/docs/language/settings/tf-cloud.mdx
On the [Cloud Configuration](https://opentofu.org/docs/language/settings/tf-cloud/) page, the "CLI-driven run workflow" text contains a broken link to <https://opentofu.org/docs/cloud-docs/run/cli>.
I assume that it's meant to link to [Using the Cloud Backend with OpenTofu CLI](https://opentofu.org/docs/cli/cloud/) page instead.
Resolves #1285
1.6.0
=> fix broken link

.github/workflows/release.yml, .goreleaser.yaml
Objective: 
The stable release flow should only be runnable from v1.x branches and should be the one we have today.
The pre-release flow (for alphas, betas, and release candidates) should be runnable from main and v1.x branches, and should not push linux archives (neither packagecloud nor snapcraft). Snapcraft does support separate edge/beta/candidate/stable channels, so eventually we could support that too.
Changes:
- Added new input variable `prerelease` in `workflow_dispatch` 
- Updated an existing variable in `workflow_dispatch` from `tag` to `ref` based on it's use case and for better code readability.
- Added a new variable `TRIGGER_PRERELEASE_FLOW`  and a conditional statement that stable release should be runnable for `v1.x` branch and pre-release flow should be runnable for …
=> 1078 prerelease vs release

internal/encryption/base.go, internal/encryption/encryption.go, internal/encryption/example_test.go, internal/encryption/plan.go, internal/encryption/state.go
A lot of the call sites seen in #1288 and #1292 only deal with errors, especially deep in the state serialization package.  By returning hcl.Diagnostics, we complicate each of those call sites, and the entire call tree thereof.  Although technically hcl.Diagnostics implements the error interface, it must be used carefuly.  In the case of `var err error; err = hcl.Diagnostics(nil)`, `err != nil` is a false statement as the type information does not match.
hcl.Diagnostics is primarily useful when decoding configuration or evaluating expressions.  We want to preserve the ability to return those from the encryption library where it makes sense, but simplify all other call sites as much as possible to the standard error interface.
Other than errors in the metadata, all of the hcl.Diagnostics …
=> State Encryption Error Handling / Diagnostics

internal/configs/hcl2shim/merge_body.go, internal/configs/hcl2shim/synth_body.go, internal/configs/hcl2shim/synth_body_test.go, internal/configs/hcl2shim/util.go, internal/configs/module.go, internal/configs/parser_config.go, internal/configs/shim.go, internal/encryption/config/config.go, internal/encryption/config/config_load.go, internal/encryption/config/config_merge.go, internal/encryption/config/config_merge_test.go, internal/encryption/config/config_parse.go, internal/encryption/encryption.go, internal/encryption/targets.go
Due to cyclic dependencies, part of the configs package needed to be moved into hcl2shim.  After this change, the root module will contain a single Encryption config.  That will need to be merged with the environment in the command package and used to build an encryption.Encryption with a configured registry.
Part of #1030 
1.7.0
=> Integrate encryption config into configs package

CHANGELOG.md, website/docs/language/resources/behavior.mdx, website/docs/language/resources/syntax.mdx
Adding the documentation for the `removed` block introduced in https://github.com/opentofu/opentofu/pull/1158
**Possible sections to add explanations about the `removed` block:**
1. [Language -> Resources -> Resource Blocks](https://opentofu.org/docs/language/resources/syntax/) - added here the main explanation. 
2. [Language -> Resources -> Resource Behavior](https://opentofu.org/docs/language/resources/behavior/) - added an explanation about the new `forget` action.
3. [Language -> Modules -> Refactoring](https://opentofu.org/docs/language/modules/develop/refactoring/) - I initially considered putting the main explanation here, as this section mainly discusses the `moved` block. But the `removed` block forgets resources and doesn't specifically belong to modules. So, I decided not to …
=> Adding `removed` block docs

internal/encryption/base.go
This fixes a bug where a null method was not correctly detected in the fallback logic
Related to  #1030 
1.7.0
=> Encryption should require an explicit fallback

.github/workflows/compare-snapshots.yml, CHANGELOG.md, internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go, internal/lang/funcs/render_template.go, internal/lang/funcs/render_template_test.go, internal/lang/funcs/string.go, internal/lang/funcs/testdata/recursive.tmpl, website/docs/language/functions/templatefile.mdx
This changes templatefile to track call depth when building templatefile functions.  It works fine, even when nested inside other function calls.
As mentioned in #402, due to the lack of tail recursion it can be memory intensive during evaluation.  In my opinion this is a reasonable trade off and the default max depth should prevent most OOM crashes during reasonable use.
Example:
```hcl
main.tf 
locals {
x = templatefile("rec.tmpl", {})
}
rec.tmpl 
${ base64encode(templatefile("other.tmpl", {})) }
other.tmpl 
${ templatefile("rec.tmpl", {}) }
```
With `TF_LOG=debug`
TODO:
* Documentation changes to templatefile
* Changelog entry
Resolves #402
1.7.0
=> Allow for templatefile recursion (up to 1024 depth default)

CHANGELOG.md, internal/lang/funcs/descriptions.go, internal/lang/funcs/sensitive.go, internal/lang/funcs/sensitive_test.go, internal/lang/functions.go, internal/lang/functions_test.go, website/data/language-nav-data.json, website/docs/language/functions/issensitive.mdx
This PR implements a `issensitive` function that returns whether or not a value is sensitive as described in #1370.
Resolves #1370
1.7.0
=> feat: implement issensitive function

internal/encryption/keyprovider/output.go, internal/encryption/keyprovider/output_test.go
This commit fixes a crash when using encryption resulting in the following error message:
must not call ListVal with empty slice
1.7.0
=> Fixed crash on encryption use

CHANGELOG.md
We want to make sure our changelog is on point, and an item about the `removed` block documentation is redundant. We already have an item about adding the `removed` block feature so we don't need them both.
1.7.0
=> Delete item about `removed` block documentation from the changelog

internal/builtin/provisioners/file/resource_provisioner.go, internal/builtin/provisioners/file/resource_provisioner_test.go
If file provisioner using dynamic value(such as vars) as source, we can not validate if it is empty in walkValidate operation 
Then the source will be null when apply the provisioner and make OpenTofu crash.
So we should not panic when both source and content of provisioner are empty
Resolves #1360
1.7.0
=> Fix: don't panic when both source and content of file provisioner are null

.github/ISSUE_TEMPLATE/1_7_0_alpha1_feedback.yml
This PR adds a new issue template for use with 1.7.0-alpha1 feedback issues. It will be removed when the next alpha/beta launches.
1.7.0
=> Adding temporary feedback template for 1.7.0-alpha1 issues

internal/encryption/keyprovider/aws_kms/compliance_test.go, internal/encryption/keyprovider/aws_kms/config.go, internal/encryption/keyprovider/aws_kms/config_test.go, internal/encryption/keyprovider/aws_kms/mock_test.go, internal/encryption/keyprovider/aws_kms/provider.go, internal/encryption/keyprovider/aws_kms/provider_test.go, internal/encryption/keyprovider/compliancetest/compliance.go
This PR adds compliance tests for the aws_kms key provider. This needs some love and polishing before merging. 
The compliance and acceptance tests must be run with:
`TF_ACC=1 AWS_REGION=us-east-1 TF_AWS_KMS_KEY_ID=alias/mykey go test `
1.7.0
=> Added aws_kms key provider compliance tests

go.mod, internal/backend/backend.go, internal/encryption/default_registry.go, internal/encryption/keyprovider/gcp_kms/compliance_test.go, internal/encryption/keyprovider/gcp_kms/config.go, internal/encryption/keyprovider/gcp_kms/descriptor.go, internal/encryption/keyprovider/gcp_kms/mock_test.go, internal/encryption/keyprovider/gcp_kms/provider.go
Initial manual testing performed, unit tests required, potential storage of AAD in metadata.
Resolves #1173 
Example:
```hcl
terraform {
encryption {
key_provider "gcp_kms" "basic" {
kms_encryption_key = "projects/local-vehicle-redacted/locations/global/keyRings/opentofu-test/cryptoKeys/opentofu-keytest"
credentials = "/path/to/creds.json"
key_size = 32
}
method "aes_gcm" "example" {
keys = key_provider.gcp_kms.basic
}
state {
method = method.aes_gcm.example
}
}
}
resource "tfcoremock_simple_resource" "simple" {
string = "helloworld changes! 5"
}
```
1.7.0
=> GCP KMS for Key Provider for Encryption

internal/backend/remote/backend.go, internal/backend/remote/backend_state.go, internal/cloud/backend.go
Resolves #1426 issue.
~~This PR fixes the panic described in #1426, but doesn't entirely resolve the issue. There is still a problem with the disabled encryption configuration for remoteClient ([code reference](https://github.com/opentofu/opentofu/blame/main/internal/backend/remote/backend_state.go#L100)).~~
This PR adds the needed encryption configuration for cases when remote backend is used. Also, it adds encryption to `remoteClient` to properly read the encrypted state file to pass metadata to the remote API.
Note: I didn't test the fix for cloud backend, but I believe there was a panic as well. 
1.7.0
=> fix panic when encryption enabled for remote and cloud backends

CHANGELOG.md, internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/string.go, internal/command/jsonformat/differ/differ_test.go, internal/command/jsonformat/jsondiff/types.go, internal/command/jsonformat/structured/change.go
Resolves #1361 
Large number will be truncated because the default number type in `json.Unmarshal` is float64.
Change it to use `json.Number` 
1.7.0
=> fix: large number are truncated in plan

internal/backend/local/backend.go, internal/backend/local/backend_apply.go, internal/backend/local/backend_plan.go, internal/backend/local/backend_refresh.go, internal/backend/remote/backend.go, internal/backend/remote/backend_common.go, internal/backend/remote/backend_plan.go, internal/command/login.go, internal/command/test.go, internal/logging/panic.go, internal/tofu/context.go, internal/tofu/graph.go
I've introduced a new panic handler which captures the calling stack trace.  It is a fairly small modification to the codebase which provides a much better view into the stack during a panic.  It does make a additional call to debug.Stack() before go-routines are spawned, but this is not deeply nested in any loops and should not incur any significant performance penalty.
This only is a partial solution to the problem of panics within deeply nested go-routines.  It only works between the go-routine being called and the calling go-routine.  If you have multiple nested go-rotuines, it will only preserve the
calling stack and the called panic stack.  Idealy we would be able to use context or a similar construct to build a more comprehensive panic handler, but this is a significant step in the …
=> Improve panic handling within go-routines

internal/encryption/base.go, internal/encryption/example_test.go, internal/encryption/plan.go, internal/encryption/state.go
Some backends require certain fields like "serial" in order to function. It is relatively safe to keep some of these metadata fields in the encrypted state json payload.
Long term, we should remove this metadata, but this provides a better user experience for the initial migration to encrypted state as different backends take time to adjust their expectations.
Currently only "serial" and "linage" are passed through.
Resolves #1407 
1.7.0
=> Fix #1407: Pass through metadata fields in state encryption

CHANGELOG.md, internal/tofu/context_import_test.go, internal/tofu/context_plan2_test.go, internal/tofu/context_test.go, internal/tofu/marks.go, internal/tofu/node_resource_import.go, internal/tofu/node_resource_plan.go, internal/tofu/node_resource_plan_instance.go
For resource import scenario, the instance refresh state should contains all the marks(include marks form configuration ) to avoid a update action caused by difference marks between planned value and refresh state(for example: write or delete sensitive paths is an update action).
Resolves #1231
1.7.0
=> Insert configuration marks to state value when import

website/docs/language/functions/filemd5.mdx, website/docs/language/functions/filesha1.mdx, website/docs/language/functions/md5.mdx
Just a simple doc update to add/improve security notices for `filemd5`, `md5`, and `filesha1` functions.
=> doc: Add and Improve Security Notices for `filemd5`, `md5`, and `filesha1` functions

internal/builtin/providers/tf/provider.go, internal/legacy/tofu/provider_mock.go, internal/plugin/convert/function.go, internal/plugin/grpc_provider.go, internal/plugin/grpc_provider_test.go, internal/plugin6/convert/function.go, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go, internal/provider-simple-v6/provider.go, internal/provider-simple/provider.go, internal/providers/provider.go, internal/tofu/provider_mock.go
This PR takes another step closer to supporting provider functions.  This initial implementation is based on lessons learned from https://github.com/opentofu/opentofu/pull/1334.
All panics introduced are either only hit during test code or are invalid code paths that should never be hit.
Part of #1326 
1.7.0
=> Add provider functions to provider.Interface with GRPC implementation

go.mod, internal/backend/remote-state/s3/backend_state.go
Resolves #1357.
Before the https://github.com/opentofu/opentofu/pull/701 PR, all the errors were ignored, except `ErrCodeNoSuchBucket`.
Ideally, we would want to ignore `AccessDenied` when (a) `default` workspace is used and (b) no other workspaces exist. But to assert (a) and (b), we still need to fetch workspaces regardless of their prefix. So it's ignored with no further conditions.
1.7.0
=> ignore AccessDenied error on listing workspaces in S3

internal/tofu/eval_context_builtin.go, internal/tofu/graph_walk_context.go
In working on #1439, I discovered a few areas where old provider schema caches were no longer referenced or used.
Related to #1326 
1.7.0
=> Remove some unused provider schema abstractions

CHANGELOG.md, internal/command/meta_vars.go, internal/command/test_test.go, internal/command/testdata/test/override_with_tests_dir_variables/main.tf, internal/command/testdata/test/override_with_tests_dir_variables/terraform.tfvars, internal/command/testdata/test/override_with_tests_dir_variables/tests/main.tftest.hcl, internal/command/testdata/test/override_with_tests_dir_variables/tests/terraform.tfvars, internal/command/testdata/test/pass_with_tests_dir_variables/main.tf, internal/command/testdata/test/pass_with_tests_dir_variables/tests/main.tftest.hcl, internal/command/testdata/test/pass_with_tests_dir_variables/tests/terraform.tfvars, website/docs/cli/commands/test/index.mdx
To enhance the functionality of tofu tests by extending support for `.tfvars` files located in the tests folder. Currently, tofu tests only pick up variables from `.tfvars` files in the root configuration folder. By implementing this, users will have the flexibility to use variables from `.tfvars` files in the tests folder as well. Also, if a variable appears both in a `.tfvars` file in the root configuration and in the tests folder, the one in the tests folder will take precedence. 
- Modified `meta_vars.go` file to incorporate the logic for including `.tfvars` files from the tests folder.
- Created two new folders, `override_with_tests_dir_variables` and `pass_with_tests_dir_variables`, to contain `.tf` test files and modified `test_test.go` for testing the changes.
- Added a …
=> Added support to use .tfvars files from tests folder

website/docs/language/functions/nonsensitive.mdx
=> Backport: update nonsensitive docs to not show error

docs/architecture.md
Just a minor fix for documentation: `commands.go` is in `cmd/tofu` directory and not in the root.
1.7.0
=> fix: commands.go location in architecture docs

internal/command/testdata/backend-unchanged/.terraform/terraform.tfstate, internal/encryption/keyprovider/gcp_kms/compliance_test.go
As a part of #1202  @cam72cam and I are working to get tests run on multiple OS environments like i386, AMD64 etc.
While running dry runs of tests in one of these environments, a number not supported by the 32 bit architecture was identified and fixed.
=> Change numbers to make tests work in i386

CHANGELOG.md, go.mod, go.sum, internal/command/e2etest/init_test.go, internal/command/get.go, internal/command/init.go, internal/command/meta.go, internal/command/meta_ui.go, internal/command/views/json_view.go, internal/command/views/json_view_test.go
Resolves #1373
In init or get package, lots of output is calling method on `cli.UI` interface
If you want to output in JSON, you should call method on views.JSONView.
I tried to draw a figure to explain the logical here. (the green color is some logical I added in this PR.)
I create a `wrappedUI` and implement the `cli.UI` interface. It contains jsonView and cli.UI in it. 
If `-json` is given, `wrappedUI` will call the method on `jsonView`. If not, `wrappedUI` will call the method on `cli.Ui`, be consistent with current logical.
At present, the logic of -json is simply implemented. If you look carefully, there are actually a lot of details that could be better.
For example, in output like the following, characters like `\n` should not appear in theory. 
But in order to ensure that the …
=> feat: init and get command support json format output

CHANGELOG.md
Related to #1380 and #1357.
This PR adds missing changelog entries for these issues:
* [Crash when using a conditional with Twingate resource](https://github.com/opentofu/opentofu/issues/1380)
* [Backend/S3: Regression in workspace-prefix - must have permission to default env: workspace prefix](https://github.com/opentofu/opentofu/issues/1357)
1.7.0
=> add changelog entries for s3 and twingate bugs

website/docs/language/state/encryption.mdx, website/docs/language/state/examples/encryption/gcp_kms.tf
This PR adds website documentation for GCP KMS key provider.
Part of #1172
1.7.0
=> add website docs for GCP KMS key provider

website/docs/language/state/examples/encryption/configuration.sh
When using the shell built in read, as in the previous example, the exit code would always return `1`.
This can be really inconvenient on a CI, where every command is expected to exit with `0`, otherwise it shows the build as broken.
Resorted to using `cat(1)`, to work around this issue.
Because of this issue: https://github.com/opentofu/opentofu/issues/1462
Resolves #1462
This issue: https://github.com/opentofu/opentofu/issues/1462
Technically: 1.7.0
But really, it's more of a documentation fix.
=> Fix for setting the env variable on Unix/Linux

internal/command/e2etest/init_test.go
Part of #1373.
This PR adds a tiny bug fix for windows e2e test.
We need to escape `\` in windows directory path before comparing it to json output.
https://github.com/opentofu/opentofu/actions/runs/8554520116
1.7.0
=> fix e2e init test for windows

website/docs/language/modules/develop/publish.mdx
I noticed that the link to private module registry docs from the publishing modules page was hard coded to localhost.
Resolves #1465
1.7.0
=> Fixing link that was pointing to localhost in docs

.devcontainer.json
Resolves N/A
No active issue is open regarding this change; it is a simple version bump to match the container version with the required version of Go.
1.7.0
=> Update devcontainer image to Go 1.21

.github/workflows/release.yml, .gitignore, .goreleaser.yaml
Set snapcraft channel and grade based on pre-release release or stable release.
Changes
- Updated release workflow action to support release flags (prerelease and latest)
- Updated goreleaser to construct grade and channels based on workflow release flags enabled.
Resolves #1403 
1.7.0
=> Bug Fix #1403 - Set grade and channel correctly

CHANGELOG.md, website/docs/language/state/encryption.mdx
Part of https://github.com/opentofu/opentofu/issues/1173
Part of https://github.com/opentofu/opentofu/issues/1174
This PR adds missing changelog entry for GCP KMS and OpenBao key providers. Also, this PR updates the URL for OpenBao documentation website.
1.7.0
=> add changelog entry for GCP KMS and OpenBao; update bao doc domain

.github/scripts/update_top_issues_ranking/go.mod, .github/scripts/update_top_issues_ranking/main.go, .github/scripts/update_top_issues_ranking/ranking.tmpl, .github/workflows/update-top-issues-ranking.yml
Introduces a Go script that:
- Fetches all open issues
- Renders an issue based on them
- Updates the ranking issue with the result - https://github.com/opentofu/opentofu/issues/1496
Here's how it looks in practice:
I've tested this end2end in a private repo and verified it works.
Inspired by https://github.com/zed-industries/zed/issues/5393
=> Add top issues ranking as a scheduled GitHub Action.

CHANGELOG.md, internal/backend/remote-state/http/backend.go, internal/backend/remote-state/http/backend_test.go, internal/backend/remote-state/http/client.go, internal/backend/remote-state/http/client_test.go, internal/command/apply_test.go
Enables users to define headers on the HTTP backend configuration, when supplied the headers are attached to all HTTP requests to the HTTP remote backend.
Changes
- Added headers as a configuration item when creating the HTTP backend
- Added attaching user-defined headers to requests sent to the HTTP backend
Resolves #1427 
1.7.0
=> HTTP backend user-defined headers

internal/tofu/hook_mock.go
=> Introduce locking on the hook mocks to avoid data race failures

website/docs/language/state/encryption.mdx, website/docs/language/state/examples/encryption/fallback_from_unencrypted.tf, website/docs/language/state/examples/encryption/fallback_to_unencrypted.tf, website/docs/language/state/examples/encryption/openbao.tf, website/docs/language/state/examples/encryption/sample.tf
This PR cleans up various small bits of the encryption documentation for better readability.
1.7.0-beta1
=> Cleaning up encryption docs for 1.7.0-beta1

.goreleaser.yaml
Stop building images with just x as the label from the x.y.z full version.
Only push :x.y labeled images on non-prerelease.
In other words, prereleases will only push docker images with the full version label.
=> Fix docker building in goreleaser (by prerelease).

internal/backend/remote-state/http/client.go
1. Don't need to close response body twice
2. Pass data as `[]byte`, no need to wrap in a reader
This is a copy of https://github.com/hashicorp/terraform/pull/24639.
1.7.0
=> HTTP backend client cleanup

internal/tofu/testdata/transform-attach-config/child/main.tf, internal/tofu/testdata/transform-attach-config/main.tf, internal/tofu/transform_attach_config_resource_test.go
This simulates loading a module with resource and data blocks, and a child with the same, and ensures that the correct config is applied to the corresponding nodes.
Related to #1558 
1.8.0
=> Add tests for AttachResourceConfigTransformer

internal/tofu/transform_attach_config_resource.go
The current implementation of `AttachResourceConfigTransformer` has performance of `O(N^2)` to the number of vertices in the graph, and this leads to significant performance degradation on huge graphs.
The given implementation decreases the complexity to `O(N)` by performing direct lookup of a resource in the `ManagedResources` or `DataResources` depending on the object type.
Resolves #1559
1.8.0
=> Improve performance of `AttachResourceConfigTransformer` on big graphs

website/docs/language/expressions/function-calls.mdx
During I working on #1485, I tried a lot function calls to reproduce the conservative behavior described in doc but failed, the example mayab outdated, and I tend to remove it.
```
locals {
baz = {
"a" = sensitive("cat")
"b" = "dog"
}
}
```
```
> local.baz
{
"a" = (sensitive value)
"b" = "dog"
}
> keys(local.baz)
[
"a",
"b",
]
>
```
related to #1485 
1.7.0
=> Rewrite outdated doc of function call with sensitive data

.github/workflows/update-top-issues-ranking.yml
This workflow is exclusively used in the OpenTofu repository. Disabled for all forks and avoid the daily failure notifications.
Fix #1602
=> Do not run top issues workflow on forks

CHANGELOG.md, internal/command/autocomplete.go, internal/command/providers_schema.go, internal/command/unlock.go, internal/command/workspace_list.go
The GCS backend is more eager than other backends we tested during the state encryption work. Some of the more peripheral commands were assumed to not need state encryption (incorrectly) and were passed nil.
That nil was an explicit choice to pass an invalid value if accessed in case our assumptions around that code were wrong.  We decided early on that we would rather panic than incorrectly disable encryption.
The fix here is fairly straightforward, I've added the same encryption logic used by other commands into the commands I thought did not require explicit encryption configuration.
Resolves #1617 
1.7.1, 1.8.0
=> Fix GCS backend crash from encryption changes

CHANGELOG.md, internal/backend/remote-state/inmem/backend.go
This was the last remaining location outside of tests which used the struct initializer for remote.State instead of the constructor.  The constructor was refactored to include the state encryption parameter recently, which I had incorrectly assumed was used in all required locations.
Resolves #1613
1.7.1, 1.8.0
=> Fix inmem backend crash due to missing struct field

CHANGELOG.md, internal/tofu/context_functions.go, internal/tofu/context_functions_test.go, internal/tofu/eval_context_builtin.go, internal/tofu/test_context.go
When implementing provider functions, I failed to consider how functions would be used in test checks.  This spins up a provider instance for evaluating functions within a test context.  It does not have access to configuration and will only support unconfigured (not dynamic) functions.
Resolves #1600
1.7.1, 1.8.0
=> Allow unconfigured provider functions in test context

CHANGELOG.md, internal/tofu/context_functions.go, internal/tofu/context_functions_test.go, internal/tofu/eval_context_builtin.go, internal/tofu/test_context.go
=> Backport: Allow unconfigured provider functions in test context to 1.7.1

internal/e2e/e2e.go
Example usage:
`TF_ACC=1 GOCOVERDIR=$PWD/covdir go test -count=1 -run TestEncryptionFlow ./internal/command/e2etest/`
Part of  #1536
1.8.0
=> Add support for GOCOVERDIR to e2e tests

CHANGELOG.md, internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
Resolves #1371
This PR makes `tofu plan` with `generate-config-out` flag check for JSON strings and, if possible, replace them with `jsonencode` function call.
1.7.2
=> wrap JSON strings as jsonencode calls on generate-config-out

CHANGELOG.md, internal/tofu/eval_for_each.go, internal/tofu/eval_for_each_test.go
The diags of eval_for_each  will also show type info if the input value is sensitive
But just the type info, diags will not expose the value itself, such as empty or null.
Resolves #1434
1.7.0
=> Better wording on for_each block with unsuitable type value

.golangci.yml
This PR lowers golangci-lint requirements for code:
* increases complexity limit (cyclop linter)
* removes issues reported by some linters for `_test.go` files
See rule violation examples in https://github.com/opentofu/opentofu/pull/1499
=> lower golangci-lint requirements

CHANGELOG.md, internal/backend/remote-state/gcs/client.go, internal/states/statemgr/locker.go
- handles situation when Lock() fails because lock file exists, and then lockInfo() fails because file was deleted by concurrent process
- try to fix #1341
Details: 
- when [Lock](https://github.com/opentofu/opentofu/blob/36eb93f95862c9f1e8a270f6a6e31f8818b0bfa5/internal/backend/remote-state/gcs/client.go#L91) can't  [write lock file](https://github.com/opentofu/opentofu/blob/36eb93f95862c9f1e8a270f6a6e31f8818b0bfa5/internal/backend/remote-state/gcs/client.go#L104) it tries to [read exists lock file](https://github.com/opentofu/opentofu/blob/36eb93f95862c9f1e8a270f6a6e31f8818b0bfa5/internal/backend/remote-state/gcs/client.go#L149) via [lockError()](https://github.com/opentofu/opentofu/blob/36eb93f95862c9f1e8a270f6a6e31f8818b0bfa5/internal/backend/remote-state/gcs/client.go#L111) and …
=> gcs backend: fix race condition on locking

internal/configs/hcl2shim/util.go, internal/configs/hcl2shim/util_test.go, internal/configs/import.go, internal/configs/parser_config.go, internal/configs/resource.go, internal/tofu/context_plan2_test.go
When we introduced the `import for_each` feature in 1.7.0, we accidentally broke the parsing of `to` addresses in `import` blocks when using JSON configuration. This PR should fix this issue:
1. Now, if the `to` expression originates from a JSON configuration, it'll first be parsed to a regular HCL expression. I used an existing logic from `replace_trigger_by` decoding and extracted it to a shared function in `parser_config.go`.
2. Added tests for JSON configurations for `import` block and `replace_trigger_by` attribute.
Resolves #1652
1.8.0 (and will be backported to 1.7.2)
=> Fix bug in import 'to' parsing in json configurations

testing/equivalence-tests/tests/basic_json_string_update/.terraform.lock.hcl, testing/equivalence-tests/tests/basic_multiline_string_update/.terraform.lock.hcl, testing/equivalence-tests/tests/drift_refresh_only/.terraform.lock.hcl, testing/equivalence-tests/tests/drift_relevant_attributes/.terraform.lock.hcl, testing/equivalence-tests/tests/drift_simple/.terraform.lock.hcl, testing/equivalence-tests/tests/fully_populated_complex_destroy/.terraform.lock.hcl, testing/equivalence-tests/tests/fully_populated_complex_update/.terraform.lock.hcl, testing/equivalence-tests/tests/local_provider_delete/.terraform.lock.hcl, testing/equivalence-tests/tests/local_provider_update/.terraform.lock.hcl, testing/equivalence-tests/tests/moved_simple/.terraform.lock.hcl, testing/equivalence-tests/tests/moved_with_drift/.terraform.lock.hcl, testing/equivalence-tests/tests/moved_with_refresh_only/.terraform.lock.hcl, testing/equivalence-tests/tests/moved_with_update/.terraform.lock.hcl, testing/equivalence-tests/tests/null_provider_delete/.terraform.lock.hcl, testing/equivalence-tests/tests/replace_within_list/.terraform.lock.hcl, testing/equivalence-tests/tests/replace_within_map/.terraform.lock.hcl, testing/equivalence-tests/tests/replace_within_object/.terraform.lock.hcl, testing/equivalence-tests/tests/replace_within_set/.terraform.lock.hcl, website/docs/cli/commands/test/examples/expect_failures_resources/main.tftest.hcl, website/docs/cli/commands/test/examples/expect_failures_variables/main.tftest.hcl, website/docs/cli/commands/test/examples/module/main.tftest.hcl, website/docs/cli/commands/test/examples/nested-layout/main.tftest.hcl, website/docs/cli/commands/test/examples/nested-layout/module/tests/main.tftest.hcl, website/docs/cli/commands/test/examples/offline/main.tftest.hcl, website/docs/cli/commands/test/examples/plan/Dockerfile, website/docs/cli/commands/test/examples/plan/main.tftest.hcl, website/docs/cli/commands/test/examples/provider_alias/Dockerfile, website/docs/cli/commands/test/examples/provider_alias/main.tftest.hcl, website/docs/cli/commands/test/examples/simple/main.tftest.hcl, website/docs/cli/commands/test/examples/variables/main.tftest.hcl
These copyright headers was mistakenly added in the following PR: https://github.com/opentofu/opentofu/pull/1232.
Part of https://github.com/opentofu/opentofu/issues/454 (original issue).
1.8.0
=> remove copyright headers from website examples and lock files

CHANGELOG.md, internal/backend/local/backend_apply.go, website/docs/cli/commands/apply.mdx, website/docs/cli/config/environment-variables.mdx
By default, the remote state backend persists state to the remote storage every 20 seconds—this value is hardcoded. But when the state is big (> 100Mb), this operation takes a long time and consumes a significant portion of these 20 seconds. This PR allows to make the persist interval configurable via the `TF_STATE_PERSIST_INTERVAL` environment variable, which allows to specify how often persistence should happen.
Please guide what part of documentation needs to be updated to document it...
P.S. I thought about adding the ability to completely disable this persist interval like it's done when the remote execution backend is used - but this could be a topic for discussion.
Resolves #1568
1.8.0
=> Make persist interval for remote state backend configurable

website/docs/intro/install/buildkite.jsx, website/docs/intro/migration/terraform-1.5-or-lower.mdx, website/docs/intro/migration/terraform-1.6.mdx, website/docs/intro/migration/terraform-1.7.mdx, website/docs/intro/migration/terraform-1.8.mdx, website/docs/intro/upgrading.mdx
=> [backport 1.7] fix: slack link and `BuildKite` component (#1681)

website/docs/intro/install/buildkite.jsx, website/docs/intro/migration/terraform-1.5-or-lower.mdx, website/docs/intro/migration/terraform-1.6.mdx
Backport of https://github.com/opentofu/opentofu/pull/1681
=> [backport 1.6] fix: slack link and `BuildKite` component (#1681)

.github/workflows/checks.yml, website/docs/intro/install/alpine-convenience.sh, website/docs/intro/install/deb-convenience.sh, website/docs/intro/install/rpm-convenience.sh, website/docs/intro/install/standalone-install.sh, website/docs/intro/install/test-install-instructions.sh
This PR fixes tests for installation scripts.
1. `test-install-instructions.sh` reports success status for test group even if there are fails. Syntax error in bash script.
2. Tests randomly fail due to non-OK exit code from `rm`, when there is no `install-opentofu.sh`. Due to the parent folder being shared and concurrent execution, it's possible for other tests to remove this script. Fixed by adding `-f` to `rm` in examples. 
PS I didn't check the brew test due to mismatched supported processors. Running docker with ubuntu image on Apple M2 chip (ARM) produces the following error: `Homebrew on Linux is not supported on ARM processors`.
1.8.0
=> fix tofu installation tests

.github/ISSUE_TEMPLATE/bug_report.yml
Adding a warning to the issue template that people shouldn't post TRACE leve logs:
**⚠ Warning!** Do not post `TRACE` level OpenTofu logs! They may contain sensitive credentials!
=> Adding warnings about TRACE logs

internal/command/e2etest/init_test.go, internal/command/init.go, internal/initwd/module_install.go
When running `tofu init` with a missing provider/module, the error message links to publish a new provider or module with the `https://github.com/opentofu/registry/issues` link. This link just goes to the list of issues
I changed the link to be `https://github.com/opentofu/registry/issues/new/choose`, letting you pick what kind of issue you'd like to open
1.8.0
=> Change link for missing module or missing provider

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, website/docs/intro/upgrading.mdx, website/docs/language/settings/backends/s3.mdx
Resolves https://github.com/opentofu/opentofu/issues/1368
Remove the `use_legacy_workflow` field, which has been deprecated already in version 1.7.0, from the S3 backend configuration.
1.8.0
=> Remove `use_legacy_workflow` from the S3 backend configuration

internal/configs/config_build.go, internal/initwd/from_module_test.go, internal/initwd/module_install_test.go, internal/modsdir/manifest.go
1.8.0
Related to #1201 
This PR helps resolves the initwd package tests failing on Windows. The errors included Windows filepath errors and a Tempdir Cleanup RemoveAll error. The solution for TempDir RemoveAll Cleanup error was to do `runtime.GC()` which runs a garbage collection and blocks other processes. This worked because it most likely released the open file handles that were not needed anymore. In the `WriteSnapshotToDir` function I also closed the file after creating it.
Another test was failing which was `TestModuleInstaller_symlink` and I was getting this error:
```
--- FAIL: TestModuleInstaller_symlink (0.01s)
module_install_test.go:377: failed to copy fixture to temporary directory: symlink ..\child_a\ C:\Users\ED\AppData\Local\Temp\terraform-configload2464638177\modules\child_ …
```
=> initwd Windows tests fixes

website/docs/internals/debugging.mdx
This PR adds a warning to docs to clearly state that `TRACE` log level can produce sensitive output.
1.8.0
=> add trace log level warning to docs

CHANGELOG.md, internal/backend/remote-state/s3/backend.go
This is a lightweight fix for #1594 which now supports the `http_proxy` and `https_proxy` (lowercase) environment variables. The tests will likely be retrofitted later due to their complexity in the original PR (#1676).
1.8.0
=> Fixes #1594: Support lower-case http/https_proxy env variables in S3 backend

CHANGELOG.md, internal/backend/remote-state/s3/backend.go
This is a backport of #1736 which fixes the http_proxy / https_proxy environment variable support in the S3 backend.
1.6.0
=> [Backports/1.6] Support lower-case http/https_proxy env variables in S3 backend 

.github/workflows/checks.yml, internal/configs/static_evaluator_test.go, internal/tofu/eval_for_each_test.go
The "new issue" detection was no longer working on main.  This approach simply tells golang-ci-lint what change revision to start at.  It also includes some fixes to the main branch.
1.8.0
=> Hardcode golangci-lint revision to fix build on main

.copywrite.hcl
When testing different configurations locally, I usually have git ignored dirs with lock files. It is annoying to see errors from the license checker when running locally in that setup.
So I believe any lock file should be ignored.
1.8.0
=> ignore any lock file on license header check

internal/backend/local/backend_local.go, internal/command/e2etest/static_plan_test.go, internal/command/e2etest/testdata/static_plan_variables/main.tf, internal/command/e2etest/testdata/static_plan_variables/mod/mod.tf, internal/command/meta_config.go, internal/command/meta_encryption.go, internal/command/show.go, internal/configs/module.go, internal/configs/parser_config_dir.go, internal/configs/parser_test.go, internal/configs/static_evaluator.go, internal/configs/static_evaluator_test.go
Fixes scenarios where static variables are stored in a plan (show/apply).  It also addresses encryption loading for those scenarios by only loading the required configuration data at that point in time (the cause of the reported issue).
Resolves #1768
1.8.0
=> Fix plan static variable injection

CHANGELOG.md, internal/command/e2etest/test_test.go, internal/command/e2etest/testdata/overrides-in-tests/main.tf, internal/command/e2etest/testdata/overrides-in-tests/main.tftest.hcl, internal/configs/config.go, internal/configs/hcl2shim/mock_value_composer.go, internal/configs/hcl2shim/mock_value_composer_test.go, internal/configs/module.go, internal/configs/provider.go, internal/configs/test_file.go, internal/tofu/eval_context_builtin.go, internal/tofu/graph_walk_context.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/provider_for_test_framework.go, website/docs/cli/commands/test/examples/mock_provider/main.tf, website/docs/cli/commands/test/examples/mock_provider/main.tftest.hcl, website/docs/cli/commands/test/index.mdx
Resolves #1155.
This PR adds support for `mock_provider` block. It reuses a mock value generation from the previous override implementation. As a part of this PR, I changed mock values composition to be stable (i.e. produce the same result for the same input) so `providerForTest` doesn't need to cache planned values.
TODO:
1.8.0
=> add mock providers for testing framework

internal/command/e2etest/test_test.go, internal/command/e2etest/testdata/overrides-in-tests/main.tf, internal/command/e2etest/testdata/overrides-in-tests/main.tftest.hcl, internal/configs/config.go
Part of #1155.
This PR makes `providers` block ignore any non-referenced `mock_provider` definitions. The same way it behaves with other `provider` definitions in a test file.
1.8.0
=> fix: providers block shouldn't be merged with file mocks in tofu test

internal/builtin/provisioners/remote-exec/resource_provisioner_test.go, internal/cloud/e2e/main_test.go, internal/command/views/json/diagnostic_test.go, internal/command/views/test_test.go, internal/configs/configload/loader_snapshot_test.go, internal/plans/planfile/planfile_test.go, internal/refactoring/move_statement_test.go, internal/refactoring/move_validate_test.go, internal/tofu/context_plan_test.go
1.8.0
Related to #1201 
In this PR I have included the small changes which fix tests for Windows across many packages. Most of the issues were to do with filepaths and 1 issue was a TempDir one.
See the tests output below:
<details>
<summary>Windows tests output</summary>
gotestsum ./...
✓  internal/backend/init (258ms)
✓  cmd/tofu (489ms)
✓  internal/addrs (603ms)
✖  internal/backend (924ms)
✖  internal/backend/remote (13.836s)
✓  internal/backend/remote-state/consul (249ms)
✓  internal/backend/remote-state/azure (281ms)
✓  internal/backend/remote-state/cos (305ms)
✓  internal/backend/remote-state/gcs (137ms)
✓  internal/backend/remote-state/oss (255ms)
✓  internal/backend/remote-state/kubernetes (280ms)
✓  internal/backend/remote-state/inmem (313ms)
✓  internal/backend/remote-state/pg …
=> Fix more tests on Windows

internal/backend/local/backend_local.go, internal/command/e2etest/static_plan_test.go, internal/command/e2etest/testdata/static_plan_typed_variables/main.tf, internal/command/e2etest/testdata/static_plan_typed_variables/mod/mod.tf, internal/command/show.go
This PR solves an issue where when we were showing a planfile, we were attempting to be too strict with typing. The typing of the variables is stored as dynamic and so we should use that instead of the type of the variable in the config.
Resolves #1825
1.8.0
=> use dynamic types when handling variables during plan and show static evaluation

website/docs/cli/commands/index.mdx, website/docs/cli/commands/plan.mdx, website/docs/cli/commands/test/index.mdx, website/docs/cli/config/config-file.mdx, website/docs/language/files/dependency-lock.mdx, website/docs/language/files/index.mdx, website/docs/language/files/override.mdx, website/docs/language/modules/develop/index.mdx, website/docs/language/modules/index.mdx, website/docs/language/modules/syntax.mdx, website/docs/language/syntax/json.mdx
This is a backport of https://github.com/opentofu/opentofu/pull/1841.
=> Backport[V1.8] #1841: Add documentation about the new .tofu extension

CHANGELOG.md, internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go
=> Ensure that using a sensitive path for templatefile that it doesnt panic

CHANGELOG.md, internal/tofu/graph_builder.go, internal/tofu/transform.go
As it turns out StringWithNodeTypes is a fairly expensive call that happens quite a bit. Unless TF_LOG=TRACE, the result of that call is immediately discarded. This adds a check to avoid computing this at all if the current log level is not TRACE.
For a particularly large graph that I only interact with because someone is paying me to, this saves me about 7s on every invocation of `tofu`.
1.8.0
=> Only call StringWithNodeTypes for TRACE logs

.github/workflows/release.yml
This pulls in changes that @cube2222 made on the 1.7 branch.
=> Always use large instance for release

CHANGELOG.md, internal/tofu/transform_module_expansion.go, internal/tofu/transform_module_expansion_test.go
The existing implementation took a very long time given a large number of Vertices or Modules in a graph.
This constructs a tree that can quickly return the set of vertices in a given module rather than iterating over every Vertex for every Module.
We have a fairly unusual graph with an obscene number of modules and vertices, so this change makes a fairly substantial impact on our performance.
Before: https://share.firefox.dev/3Y0qu9h
After: https://share.firefox.dev/4bHYBGd
Time spent in ModuleExpansionTransformer drops from ~27s to ~1s.
I haven't added any new tests because (in theory) this should not affect any functionality, just performance, but let me know if I should add some.
This `pathTree` implementation is not exposed to anything because I didn't want to change any interfaces, …
=> Improve ModuleExpansionTransformer performance

internal/command/format/diagnostic.go, internal/command/format/diagnostic_test.go, internal/command/meta_config.go, internal/command/views/json/diagnostic.go, internal/command/views/json/diagnostic_test.go, internal/command/views/view.go, internal/configs/configload/loader.go, internal/configs/configload/loader_snapshot.go, internal/configs/parser.go
This is passing around a `map[string][]byte`, which is fine, but the underlying [implementation](https://github.com/hashicorp/hcl/blob/360ae579460fab69e9939599af85c8f255a59007/hclparse/parser.go#L117-L128) makes a copy every time it's called, and it doesn't appropriately pre-allocate the size of the map to make that more efficient. This generates a lot of garbage, especially given that nothing modifies what is returned by Sources().
Instead, we can call the `Files()` method, which returns a `map[string]*hcl.File`, which still gives us access to the underlying `[]byte` via the `Bytes` field, but doesn't require making a copy of the map (or modifying upstream to fix this).
For my project, this drops the time spent in [`loadModule()`](https://github.com/opentofu/opentofu/blob/f668c48ffd57d1f5 …
=> Avoid copies on calls to parser.Sources()

internal/addrs/parse_ref.go, internal/addrs/parse_ref_test.go, internal/addrs/tf_attr.go, internal/command/apply_test.go, internal/command/testdata/apply-tf-workspace/main.tf, internal/command/testdata/apply-tofu-workspace/main.tf, internal/configs/provisioner.go, internal/configs/provisioner_test.go, internal/configs/static_scope.go, internal/lang/eval.go, internal/lang/eval_test.go, internal/tfdiags/diagnostics.go, internal/tofu/context_apply_test.go, internal/tofu/evaluate.go, internal/tofu/evaluate_test.go, internal/tofu/testdata/apply-tf-workspace/main.tf, internal/tofu/testdata/apply-tofu-workspace/main.tf
Resolves #1156 
This PR reuse the `TerraformAttr` struct, and add a `alias` property in it. 
Also, adding the logic for parsing `tofu.workspace` on ParseRef and evalContext function.
Here are the details on how `tofu.workspace` or `terraform.workspace` be evaluated.
I don't have a lot of background on tf syntax parsing.
But it seems that a graph will be built and walk validate in every tofu operation (like `plan`,`apply`,`validate` etc.)
So I checked the trace log and found `(*BuiltinEvalContext)EvaluateExpr` will be called when tofu want to evaluate the value of `terraform.workspace`.
Therefore, I implemented the parsing logic of `tofu.workspace` by referring to the parsing logic of `terraform.workspace`.
I noticed some unit test about `terraform.workspace` is named with tofu.
I do some …
=> feat: Add support for `tofu.workspace` which will be resolved in the same way as `terraform.workspace`

internal/command/command.go, internal/command/meta_vars.go, internal/command/meta_vars_test.go
With special cases (like shell redirects), we currently default to hcl when no file type is detected.  This PR changes that logic slightly to try to detect json vs hcl *only if* the file extension is unknown.
Resolves #1872
1.9.0
=> Better var file type detection

internal/command/show_test.go
https://github.com/opentofu/opentofu/pull/1554/files#diff-b93fa3444a62d34548671197812ac5b0111974901a88f2610f5420d1139daf3dR1003
That writes a statefile to the current test directory of ./internal/command/
1.9.0
=> Fix extra file generated in tests of #1554

website/docs/intro/tacos.mdx, website/docs/language/expressions/references.mdx, website/docs/language/providers/requirements.mdx, website/docs/language/settings/backends/oss.mdx, website/docs/language/settings/index.mdx
Works towards a fix to https://github.com/opentofu/opentofu/issues/1863, by partially fixing blockers for https://github.com/opentofu/opentofu.org/issues/85
1.9.0 (website)
=> Fix Docusaurus "broken link" warnings on main branch of docs

CHANGELOG.md, internal/configs/config_build.go
Crash should instead be a diags error
Resolves #1887 
1.9.0, 1.8.1
=> Fix missing module source panic

website/docs/language/expressions/references.mdx, website/docs/language/providers/requirements.mdx, website/docs/language/settings/backends/oss.mdx, website/docs/language/settings/index.mdx
=> Fix Docusaurus "broken link" warnings on v1.7 branch of docs (#1884)

internal/configs/config.go, internal/configs/module.go, internal/configs/module_call.go, internal/configs/provider_validation.go, internal/configs/resource.go
Part of #300 
This PR is not meant to be merged to main directly. There is also lots of TODOs left.
Main purpose of the PR is to allow using square brackets with `each.value` / `each.key` when referencing providers:
```hcl
provider random {
alias = "a"
}
provider random {
alias = "b"
}
provider random {
alias = "c"
}
module "mod" {
for_each = toset(["a", "b", "c"])
source = "./mod"
providers = {
random.moda = random[each.value]
random.modb = random[each.value]
}
}
resource "random_id" "all" {
byte_length = 10
for_each = toset(["a", "b", "c"])
provider = random[each.value]
}
```
With such configuration, proper list of `PassedProviderConfig` with `ProviderConfigRefMapping` will be passed to graph transformers. Also, `ProviderConfigRefMapping` will be passed for configuration of `data` and …
=> #300: allow square brackets syntax and pass aliases map to graph

internal/encryption/keyprovider.go, internal/encryption/targets_test.go
Fixes detection of key_provider vs variable/local and adds guard-rails around bad key_provider formats
Resolves #1918  
1.9.0, 1.8.x
=> Better handling of key_provider references

internal/command/init.go, internal/command/init_test.go, internal/command/testdata/init-syntax-invalid-extra-label/main.tf, internal/tfdiags/diagnostic.go, internal/tfdiags/diagnostics.go, internal/tfdiags/source_range.go
In the issue #1812 it was explained and demonstrated clearly that init response was outputting duplicate diagnosis error. I have added `Merge` method to diagnostics to not add exact equal diagnostics to prevent duplicates.
Resolves #1812 
1.9.0
=> Fix repetitive diagnosis output in init response

internal/addrs/move_endpoint.go, internal/communicator/ssh/communicator_test.go, internal/configs/module_test.go
=> chore: fix some function names

internal/command/jsonformat/computed/renderers/block.go, internal/command/jsonformat/computed/renderers/renderer_test.go
While implementing https://github.com/opentofu/opentofu/pull/1948 I have realized that `setOpts` is defined but is not used. I think this was a mistake and opened a PR for this. 
1.9.0
=> Fix setops not used in block set renderer

internal/command/jsonformat/differ/block.go, internal/command/jsonformat/differ/differ_test.go, internal/command/jsonformat/differ/unknown.go
Resolves #1805 
Plan diff needs to show nested unknown blocks but it does not. Thus, this PR implements required change for it
1.9.0
=> Fix all unknown block not outputted 

CHANGELOG.md, internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
Resolves #1984
This PR fixes configuration generation on import when an empty string value is marked as sensitive.
1.9.0
=> fix config generation with optional empty sensitive string

internal/configs/provider_validation.go
=> Fix inverted entries in provider error message

CONTRIBUTING.md
The current Docker example in CONTRIBUTING.md fails with the following error:
```
docker run   --rm   -v "$PWD":/usr/src/opentofu  -w /usr/src/opentofu golang:1.21.3  GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o tofu -v -buildvcs=false ./cmd/tofu; echo $?
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "GOOS=linux": executable file not found in $PATH: unknown.
127
```
This PR updates the example `docker run` command to pass the GO variables in as environment variables:
```
docker run   --rm   -v "$PWD":/usr/src/opentofu  -w /usr/src/opentofu  -e GOOS=linux  -e GOARCH=amd64  -e CGO_ENABLED=0  golang:1.21.3  go build -o tofu -v -buildvcs=false …
```
=> Update CONTRIBUTING.md: Update 'docker run' example

internal/command/e2etest/providers_mirror_test.go, internal/command/e2etest/testdata/tofu-providers-mirror-with-bad-lock-file/.terraform.lock.hcl, internal/command/e2etest/testdata/tofu-providers-mirror-with-bad-lock-file/main.tf, internal/command/providers_mirror.go
Resolves https://github.com/opentofu/opentofu/issues/1800
Prevents bad lock file from causing tofu to panic
1.9.0
=> Prevents providers mirror from crashing with bad lock file

internal/command/views/hook_ui_test.go
Resolve flaky test by using regex for expected value of `TestUiHookPreApply_periodicTimer`. Match any single digit for the number of seconds vs. hard-coding. This seems less fragile to me.
I could look into separately asserting on the total elapsed time, and / or use a smaller range of numbers in the regex if there's concern about this starting to take unexpectedly more time, but I'm assuming that's not mostly what this test is trying to check.
Example failure:
https://github.com/opentofu/opentofu/actions/runs/11072397888/job/30766524726
Note: I do get one golangci-lint failure within that specific function, but as best I can tell, it's not related to my changes.
1.9.0
=> test: use regex for expected value in `TestUiHookPreApply_periodicTimer`

go.mod, go.sum
Resolves #1228
Bumped go-cty-yaml to v1.1.0. Yaml number parsing is now fully according to [YAML spec](https://yaml.org/spec/1.2-old/spec.html#id2805071). See [go-cty-yaml v1.1.0 CHANGELOG](https://github.com/zclconf/go-cty-yaml/blob/master/CHANGELOG.md#110-october-2-2024) for details.
Note: [Similar PR](https://github.com/hashicorp/terraform/pull/35805) created for Terraform. I believe this does not constitute 'have looked at Terraform source code'. Real work is in library go-cty-yaml.
1.9.0
=> Bumped go-cty-yaml to v1.1.0

internal/states/module_test.go, internal/states/resource_test.go, internal/states/statefile/version4_test.go, internal/tofu/context_apply.go, internal/tofu/context_plan.go, internal/tofu/node_resource_abstract_instance_test.go, internal/tofu/node_resource_abstract_test.go, internal/tofu/node_resource_validate_test.go, internal/tofu/transform_destroy_edge.go, internal/tofu/transform_provider_test.go
Addind UT for https://github.com/opentofu/opentofu/pull/1963
Based of https://github.com/opentofu/opentofu/pull/2030
We still have a single failing test that we need to fix `TestContext2Plan_destroyWithResourceConfiguredProvider`.
1.9.0
=> #300 - Support in graph for each on providers in resources and modules: Add UT

internal/command/meta_backend.go, internal/command/meta_backend_test.go, internal/command/testdata/backend-unchanged-vars/.terraform/terraform.tfstate, internal/command/testdata/backend-unchanged-vars/local-state.tfstate, internal/command/testdata/backend-unchanged-vars/main.tf
The `backendConfigNeedsMigration` helper evaluates the backend configuration inline to compare it with the object previously saved in the `.terraform/terraform.tfstate` file.
However, this wasn't updated to use the new "static eval" functionality and so was treating any references to variables or function calls as invalid, causing a spurious "backend configuration changed" error when re-initializing the working directory with identical backend configuration settings.
The structure of this code, with a hidden special re-eval of the configuration, is highly unfortunate. However, for this PR I've intentionally focused only on fixing the problem as reported, to minimize the risk of the change. We could choose to try to improve the structure of the backend init/migration codepaths at a later …
=> command/init: Support static eval for backend config migration check

CHANGELOG.md, internal/command/meta_backend.go, internal/command/meta_backend_test.go, internal/command/testdata/backend-unchanged-vars/.terraform/terraform.tfstate, internal/command/testdata/backend-unchanged-vars/local-state.tfstate, internal/command/testdata/backend-unchanged-vars/main.tf
This is a direct backport of https://github.com/opentofu/opentofu/pull/2055 to the v1.8 branch, for inclusion in a forthcoming patch release.
Resolves #2024
1.8.x
=> command/init: Support static eval for backend config migration check [v1.8 backport]

internal/tofu/node_resource_abstract.go, internal/tofu/node_resource_abstract_test.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_import.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/transform_destroy_edge.go, internal/tofu/transform_provider.go
Precursor to #300
When digging in to the `ProviderTransformer` and the `ProviderFunctionTransformer` (https://github.com/opentofu/opentofu/issues/2051), I found a mixture of dead an non-functional code.  That has been removed in this PR and the "quirks" around ignoring local provider names during `ProviderTransformer` have been made more explicit.
This has also been structured in a way that will make it easier to review and adopt #300
1.9.0
=> Cleanup and encode existing "bugs" in ProviderTransformer

.golangci.yml, internal/tofu/context_validate_test.go, internal/tofu/node_module_variable.go
The nodeModuleVariable.References() function is not called within the function transformer as it is on an expanded object.  Instead these references are determined pre-expansion and provided to the provider function transformer
I still need to try to find a test case that explicitly triggers this, instead of the race condition in the issue.
Resolves #2051
1.9.0,1.8.4,1.7.4
=> Fix function refs in variable validation

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
=> Ensure config generation does not crash when importing sensitive values

internal/registry/client.go
Resolves #2078 
Right now the `tofu` command will attempt to read the json body of a module registry response if the http statuscode is 200, and read the header if it returns a 201. 
This code introduces a change to fall back to checking the header. This means the module registry can return either json body or a http header to point to the location of the module.
1.9.0
=> Fallback to reading the x-terraform-get header if the module registry returns an empty json body

rfc/20240513-static-evaluation-providers.md
This updates the previously-accepted "Static Evaluation of Provider Iteration" to include some of the syntax ideas from #2088. This is the initial approved RFC that was written for #300.
The main goal here is to reduce the risk that a later fully-dynamic implementation will be blocked by backward-compatibility with behavior that early-eval can support but dynamic eval cannot. Early eval is not so constrained in what order expressions need to be evaluated in since it derives everything from statically-configured variables, and so there will always be some risk of a static-eval-based implementation incorporating a capability that cannot be easily translated to a later dynamic version of the same feature.
[Rendered Version](https://github.com/opentofu/opentofu/blob/rfc-static-eval-provider-in …
=> RFC: Updated "Static Evaluation of Provider Iteration"

internal/backend/init/init.go, internal/backend/init/testing.go, internal/command/meta_backend.go, internal/command/meta_backend_test.go, internal/command/testdata/backend-unchanged-vars/.terraform/terraform.tfstate, internal/command/testdata/backend-unchanged-vars/main.tf
My earlier fix for #2024, in #2055 and #2060, inadvertently regressed support for properly detecting whether state migration is required on init when a backend has a required configuration argument.
This codepath is a little tricky compared to most of the rest of the backend handling in that it evaluates only the subset of the configuration that's specified inline in the root module's `backend` block, ignoring any additional argument overriddes from the `-backend-config` option to `tofu init`.
Therefore it must treat all arguments as optional, regardless of how they are specified in the backend schema, because a required argument must be enforced only against the final merged configuration that combines the two sources of backend configuration options.
The `NoneRequired` helper method on …
=> Fix regression of backend reinit detection when backend schema has required arguments

CHANGELOG.md, internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/providers/provider.go
Provider function arguments now respect the protocol's definition that function inputs should be checked against IsWhollyKnown in addition to the standard IsKnown.
This is different than the cty convention and has been documented as such
Resolves #2126
1.9.0, 1.8.x, 1.7.x
=> Partially unknown provider functions arguments fixed

CHANGELOG.md, internal/backend/init/init.go, internal/backend/init/testing.go, internal/command/meta_backend.go, internal/command/meta_backend_test.go, internal/command/testdata/backend-unchanged-vars/.terraform/terraform.tfstate, internal/command/testdata/backend-unchanged-vars/main.tf
Backport of https://github.com/opentofu/opentofu/pull/2119 to the v1.8 branch.
=> v1.8 Backport: Fix regression of backend reinit detection when backend schema has required arguments

internal/tofu/context_apply2_test.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_apply_instance.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_import.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go
As reported in the linked issue, the destroy path was broken in the alpha due to https://github.com/opentofu/opentofu/pull/2105.  I additionally noticed that we had some related issues with orphaned instances.
For the destroy scenario, I realized that `NodeDestroyResourceInstance`s are created without a corresponding expansion data.  In that scenario, we are unable to use the configuration to determine the correct provider instance keys and should instead rely on the state.
In the `NodePlanResourceInstanceOrphaned` scenario, only the `NodePlanResourceInstance`s have corresponding expansion data from the configuration.  If provider keys are in use and expansion data can't be determined, we should try to default to the state.
Overall this mixes in some logic from the ProviderTransformer …
=> Fix destroy/orphan path with provider instances

.github/workflows/checks.yml, internal/encryption/keyprovider.go, internal/tofu/provider_for_test_framework.go
This PR fixes phantom errcheck warning as described in https://github.com/golangci/golangci-lint/issues/4733. For example, see https://github.com/opentofu/opentofu/pull/2090.
1.9.0
=> upgrade golangci-lint to v1.62

CHANGELOG.md, internal/command/test_test.go, internal/command/testdata/test/mock_provider_validation/main.tf, internal/command/testdata/test/mock_provider_validation/main.tftest.hcl, internal/tofu/provider_for_test_framework.go
Resolves #2139
Resolves #2038 
In the initial implementation of mock providers, I missed that the validation of the provider block must also be skipped. In this PR I disable `ValidateProviderConfig` calls and remove provider-related schemas from `GetProviderSchema` call for any mocked provider.
1.9.0
=> fix mock provider validation

CHANGELOG.md, internal/configs/hcl2shim/mock_value_composer.go, internal/configs/hcl2shim/mock_value_composer_test.go
Resolves https://github.com/opentofu/opentofu/issues/2008
Resolves https://github.com/opentofu/opentofu/issues/1837
Part of https://github.com/opentofu/opentofu/issues/2139
1.9.0
=> fix mock type conversion in tofu test

CHANGELOG.md
This PR adds missing changelog entry from https://github.com/opentofu/opentofu/pull/2120.
Part of #2003
TODO: backport it to 1.7 and 1.8
1.9.0
=> add missing changelog entry for http backend logging

CHANGELOG.md, internal/tofu/context_plan2_test.go, internal/tofu/node_resource_plan.go
As [suggested](https://github.com/opentofu/opentofu/issues/1803#issuecomment-2460965264) by @apparentlymart, the `tofu destroy` command should ignore import blocks. So, this solution skips resolving and expanding import targets when we are running as part of the "preDestroyRefresh" mode.
Resolves #1803 
1.9.0
=> Skip imports on `tofu destroy`

CHANGELOG.md, internal/configs/hcl2shim/mock_value_composer.go, internal/configs/hcl2shim/mock_value_composer_test.go
Resolves https://github.com/opentofu/opentofu/issues/1839 and continues work started in https://github.com/opentofu/opentofu/pull/1903 by @pooriaghaedi 
1.9.0
=> Fix: Change warning to error when incorrect type is used for mocking a resource

internal/tofu/context_functions_test.go, internal/tofu/graph_builder_plan_test.go, internal/tofu/node_module_variable.go, internal/tofu/node_root_variable.go, internal/tofu/node_root_variable_test.go, internal/tofu/node_variable_reference.go, internal/tofu/transform_module_variable.go, internal/tofu/transform_module_variable_test.go, internal/tofu/transform_provider.go, internal/tofu/transform_variable.go
Currently, GraphNodeReferenceOutside is used to make sure that variables are evaluated in the correct scope.  However, with the addition of function providers and "bugfixes" introduced in provider iteration, variables now require two completely distinct scopes.
One scope is used for variable evaluation from module call inputs, the other for the validation scope.  These two scopes are now represented by the original struct in charge of the variable, and an new one which only contains the validation logic.
Only the new "validation scope" node provides the reference and will be depended on, other nodes may use the value post-validation.
Additionally ProviderFunctionTransformer now understands GraphNodeReferenceOutside, which fixes a few related bugs.  Idealy, we could get rid of that …
=> Split variable evaluation / validation scope

CHANGELOG.md, internal/tofu/eval_variable.go, internal/tofu/eval_variable_test.go
This is a v1.8 branch backport of https://github.com/opentofu/opentofu/pull/2233.
As discussed there, this includes the changelog message because this will be perceived as being fixed in v1.8.7 and then carried forward to v1.9.0, even though that's not actually how it played out in practice.
Closes https://github.com/opentofu/opentofu/issues/2219.
=> [v1.8 Backport] tofu: Variable validation diagnostics must mark sensitive values

CHANGELOG.md, internal/encryption/base.go, internal/encryption/dual_custody_test.go, internal/encryption/example_test.go, internal/encryption/keyprovider_meta_change_test.go, internal/encryption/plan.go, internal/encryption/state.go, internal/plans/planfile/planfile_test.go, internal/states/remote/state.go, internal/states/statefile/file.go, internal/states/statefile/read.go, internal/states/statefile/roundtrip_test.go
Currently when using a remote state storage configuration, if the encryption method is changed a null_resource, output or similar state change is required to apply the encryption change.  This has caused significant confusion for end users migrating to opentofu's state encryption solution, most recently https://gitlab.com/gitlab-org/gitlab/-/issues/450816#note_2215987832.
This change tracks the if a fallback was used to decrypt the state and forces a persist in the remote state storage client.  The local backend already writes the state regardless of if a migration is needed or not and does not require a change.
* Should this be backported? Yes
* ~Does any documentation need to be updated?~
Resolves #1606 
1.9.0
=> Force state change if encryption used fallback

CHANGELOG.md, internal/command/test.go, internal/command/testdata/test/default_variables/main.tf, internal/command/testdata/test/default_variables/main.tftest.hcl
=> fix: type defaults for variables in tests

website/docs/language/meta-arguments/examples/resource-provider-dynamic-instances.tf, website/docs/language/meta-arguments/module-providers.mdx, website/docs/language/meta-arguments/resource-provider.mdx, website/docs/language/modules/develop/providers.mdx, website/docs/language/providers/configuration.mdx, website/docs/language/providers/index.mdx
This is an initial round of documentation updates for the new feature that allows an alternate provider configuration to declare multiple dynamic instances, using the `for_each` argument in a `provider` block.
This initial work is intended to provide a starting point to support those who wish to experiment with this feature during the v1.9.0 prerelease period. We will continue iterating on this documentation throughout the prerelease period, especially if prerelease feedback suggests that any part of the feature is difficult to understand.
Along with directly documenting the new features, this also includes some general adjustments of terminology to try to draw a distinction between provider _configurations_ (`provider` blocks) and provider _instances_, since this new feature means that …
=> website: Initial documentation updates for dynamic provider instances

.github/workflows/release.yml
Anything that's released under a "v" tag and is not a pre-release, we should push to packagecloud.  The v check is probably not needed, but I wanted to minimize the changes to this pipeline.
branch | tag | prerelease | packagecloud
--- | --- | --- | ---
main | v1.9.0-alpha1 | yes | no
main | v1.9.0-beta1 | yes | no
v1.9 | v1.9.0-rc1 | yes | no
v1.9 | v1.9.0 | no | yes
v1.8 | v1.8.8 | no | yes
=> Fix packagecloud push skip for alpha/beta/rc

internal/command/test.go, internal/command/test_test.go, internal/command/testdata/test/destroyed_mod_outputs/main.tf, internal/command/testdata/test/destroyed_mod_outputs/main.tftest.hcl, internal/command/testdata/test/destroyed_mod_outputs/mod/main.tf
Resolves #2260.
This PR adds a simulation of state file write between multiple tofu test runs.
The fix needs to be backported
1.9.0
=> add simulated state serialization between tofu test runs

CHANGELOG.md, internal/getproviders/filesystem_mirror_source.go, internal/getproviders/filesystem_mirror_source_test.go, internal/getproviders/testdata/filesystem-mirror-unspecified/registry.opentofu.org/testnamespace/unspecified/0.0.0/linux_amd64/unspecified-provider, internal/providercache/installer.go, internal/providercache/installer_test.go
Warn user about provider version 0.0.0
---
Version 0.0.0 is defined as the unspecified version by the versioning library we are using ([go-versions](https://github.com/apparentlymart/go-versions/blob/main/versions/version.go)).
It is used in a few places, and as Martin (@apparentlymart) suggested in the issue, in the short term, we should warn the user about such use cases and direct them toward the [dev-overrides](https://opentofu.org/docs/cli/config/config-file/#development-overrides-for-provider-developers) docs.
I've made two main changes here:
- Issue a warning for the user, when we detect provider version 0.0.0 in the file system.
- Return an error when the user tries to use a provider with the exact version 0.0.0
In both cases, I've attached the dev_overrides docs URL.
P.S. Thanks …
=> Warn user about provider version 0.0.0

CHANGELOG.md, internal/command/init.go, internal/command/init_test.go, internal/command/testdata/init-encryption-available/main.tf
With this change, `tofu init -backend=false` runs successfully without attempting to read encryption keys as suggested by @bt909  
Resolves #2217
1.10.0
=> Skip reading encryption keys on `tofu init ` with `-backend=false` flag set

CHANGELOG.md, internal/command/apply_test.go, internal/command/testdata/apply_cbd_with_refresh_false/main.tf, internal/tofu/context_apply.go, internal/tofu/context_plan.go, internal/tofu/graph_builder_apply.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/transform_destroy_cbd.go
In this PR I add an additional refresh state write on planning even when `refresh=false` is used, since this is the place where we synchronize configuration `create_before_destroy` value with the state itself. As discussed in the issue, we only write to the refreshed state for this specific use case (`refresh=false` + configuration value present + state value differs).
Note: I didn't alter the logic of `create_before_destroy` itself, however I suspect there could be a problem for cases when OpenTofu needs to use state's value (inherited) when replacing a resource even if the configuration doesn't force cbd anymore. Not sure if that's a practical problem though.
Also, I removed a few unused params, which I encountered during debugging. This is irrelevant to the PR, however those are pretty …
=> fix: unused config's create_before_destroy on resource change with no refresh

CHANGELOG.md, internal/command/apply_test.go, internal/command/testdata/apply_cbd_with_refresh_false/main.tf, internal/tofu/context_apply.go, internal/tofu/context_plan.go, internal/tofu/graph_builder_apply.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/transform_destroy_cbd.go
Cherry pick of c5b43b9f1a6cfca53190fe6578f503041fd42d85 to include the fix for the upcoming 1.9 stable release.
1.9.0
=> [BACKPORT v1.9] fix: unused config's create_before_destroy on resource change with no refresh (#2248)

CHANGELOG.md, internal/command/init.go, internal/command/init_test.go, internal/command/testdata/init-encryption-available/main.tf
Cherry pick of 211ec55a30a7696a17661f5aaea0f8a5f623ee89 to include the fix for the upcoming 1.9 stable release.
1.9.0
=> [BACKPORT v1.9] Skip reading encryption keys on `tofu init ` with `-backend=false` flag set (#2293)

internal/command/testdata/test/destroyed_mod_outputs/mod/main.tf
This PR doesn't need to be released, it just fixes the flaky test for the branch. Cherry pick of be5b14625d2bcea594c22489e894b3ea4a6c8b6c
none
=> [BACKPORT v1.8] fix randomly failing destroyed_mod_outputs test (#2315)

internal/command/testdata/test/destroyed_mod_outputs/mod/main.tf
This PR doesn't need to be released, it just fixes the flaky test for the branch. Cherry pick of be5b14625d2bcea594c22489e894b3ea4a6c8b6c
none
=> [BACKPORT v1.9] fix randomly failing destroyed_mod_outputs test (#2315)

rfc/20241113-pragmatic-complexity-linting.md
We currently have a set of aspirational linting rules in the project's golangci-lint configuration, but this codebase was derived from a much older codebase that was not written under those lint rules and so we made the pragmatic decision that only code that has changed since the addition of the lint rules is subjected to those lint rules.
That approach aims to make the compromise of encouraging us to gradually improve code "while we're in the area" working on other changes, while avoiding the need for a huge retrofit of existing code.
However, that compromise seems to be less appropriate for the subset of linting rules related to code complexity in particular. That category of rules typically imposes some arbitrary limit on a qualitative metric that the linting tool can measure. These …
=> rfc: A Pragmatic Approach to Linting for Code Complexity

internal/ipaddr/ip.go, internal/ipaddr/ip_test.go, internal/ipaddr/parse.go
The code in `package ipaddr` is all snapshot from the Go codebase in older versions, inlined here to allow OpenTofu's cidr-calculation-related functions to preserve their original behavior despite upstream having changed the parsing rules in a breaking way (https://github.com/golang/go/issues/30999, and in particular https://github.com/golang/go/issues/30999#issuecomment-819696563).
This code is intentionally modified as little as possible from the upstream code it was derived from. In the rest of this codebase we are imposing on ourselves considerably stricter style conventions than the Go project follows but we need to disable various linters for `package ipaddr` package to allow this code to remain written in the Go idiomatic style, rather than in OpenTofu's stricter local style.
In …
=> ipaddr: Exempt from all lint rules

internal/legacy/helper/schema/field_reader.go, internal/legacy/helper/schema/field_reader_config.go, internal/legacy/helper/schema/resource.go, internal/legacy/helper/schema/resource_data.go, internal/legacy/helper/schema/resource_timeout.go, internal/legacy/helper/schema/schema.go, internal/legacy/helper/schema/serialize.go, internal/legacy/helper/schema/shims_test.go, internal/legacy/tofu/diff.go, internal/legacy/tofu/provider_mock.go, internal/legacy/tofu/provisioner_mock.go, internal/legacy/tofu/state.go, internal/legacy/tofu/state_filter.go, internal/legacy/tofu/upgrade_state_v2_test.go
These packages are frozen copies of old code from much older versions of the product that are preserved to keep the state storage backends working until we decide on a way to get them out of this codebase entirely.
Therefore the only potential future change to this code is to delete it once it's no longer needed. It would not be worth the risk or time investment to rework these to meet our strict complexity linting rules.
This is for https://github.com/opentofu/opentofu/issues/2325, just to get these legacy packages off our radar so we can focus on improving packages that we might actually do maintenance on in future.
=> legacy packages: Exempt from complexity linters

internal/states/statefile/version1_upgrade.go, internal/states/statefile/version2_upgrade.go, internal/states/statefile/version3_upgrade.go
The functions in these files are for handling older state snapshot formats that current OpenTofu versions never generate, and so it's highly unlikely that we'll ever make substantial changes to these functions.
Therefore it's unjustified to risk reworking it to pass linting rules, and so we'll add nolint comments instead. Our priority is to make as few changes as possible to these functions, to minimize the risk of regressing a upgrade paths that are exercised very infrequently.
(For context, state version 4 has been current ever since Terraform v0.12.0, and so the earlier versions are long obsolete.)
I worked on this today primarily to remove some functions from consideration on https://github.com/opentofu/opentofu/issues/2325, but this also opts out of the non-complexity-related linters …
=> statefile: old snapshot format version upgrades are exempt from linters

internal/repl/format.go, internal/repl/session.go
This series of commits deals with all of the current linter warnings in `package repl`.
My priority with this PR was to fix the complexity-related lint errors for https://github.com/opentofu/opentofu/issues/2325, but there were only a few other lint failures left after that so the final commit in this series just deals with the rest of them all at once so this package will now be totally lint-free.
=> repl: Fix all linter warnings

internal/lang/eval.go, internal/lang/eval_test.go, internal/lang/functions.go, internal/lang/functions_test.go
This PR includes two changes that together make `package lang` pass the code complexity linters, for https://github.com/opentofu/opentofu/issues/2325:
- Factor out the base function table construction into its own function.
This code unavoidably violates the `funlen` rule because its length scales by the number of functions available in the OpenTofu language. But by factoring it out into its own function we can at least apply the `nolint:funlen` opt-out only to the table-construction code, and `Scope.Functions` can focus only on applying the scope-specific modifications and not need its own linter opt-out.
- Split `enhanceFunctionDiags` into two functions.
This was originally failing the `nestif` lint due to having too many levels of `if` nesting.
However, regardless of that I think this …
=> lang: Reduce code complexity to pass linters

internal/command/jsonplan/values.go, internal/command/jsonplan/values_test.go
As mentioned in https://github.com/opentofu/opentofu/issues/2252, Changes.ResourceInstance() has linear complexity in the number of resources being changed. Ideally, we will eventually address the root problem here, but given that the Resources slice is exposed, it's hard to make that change without breaking all the callers.
In this change, I aim to fix only the "tofu show" path, which already is reaching into Changes.Resources to construct its own module mappings. I just take this one step further by adding an additional map to make lookups constant time. Since we're visiting every change in order to marshal them, we were calling ResourceInstance for every change, which then iterated over every change again, hence the quadratic performance.
This cuts my "tofu show" time in half. What …
=> Fix quadratic marshalPlannedValues

internal/command/apply.go, internal/command/plan.go, internal/command/refresh.go
In OpenTofu v1.8, a new option "-json" was added to the "init" command, and this option is included in the help text. However, this option "-json" is not included in the help text of "apply", "plan" or "refresh", but is included on the OpenTofu website. I believe that they should be consistent, so I raised this PR to add the option in the help text of commands "apply", "plan" and "refresh".
1.10.0
1.9.x
1.8.x
1.7.x
1.6.x
=> Add option "-json" in help text of apply command and plan command.

CHANGELOG.md, internal/tofu/context_apply2_test.go, internal/tofu/context_plan2_test.go, internal/tofu/node_data_destroy.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_apply_instance.go, internal/tofu/node_resource_deposed.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_forget.go, internal/tofu/node_resource_import.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go
Resolves #2334
This PR resolves the issue described in #2334 and a few more cases, where a provider is not resolved before its usage. Also, we improve error messages for cases, when provider configuration is changed (its instances, or the presence of for_each).
Must be backported to v1.9
1.9.0
=> fix: provider not initialized in some cases (mostly, deposed)

CHANGELOG.md, internal/configs/provider_meta.go, internal/configs/testdata/invalid-modules/provider-meta-invalid-interpolation/main.tf, internal/configs/testdata/invalid-modules/provider-meta-invalid-name/main.tf
The name of the provider in the `provider_meta` block is enforced by `addrs.MustParseProviderPart`. The caller chain of the affected function assumes that if the returned `ProviderMeta` is not `nil`, it is valid. Hence the panic later.
The fix is to return `nil` if *any* of the diagnostics in this function fail with an error.
Resolves #2345 
1.10.0
=> Catch invalid name in provider_meta before it causes a crash

internal/plans/objchange/compatible.go
This is another contribution to our complexity-lint-satisfaction project in https://github.com/opentofu/opentofu/issues/2325.
This change is focused on the unexported functions that are used to implement the exported `objchange.AssertObjectCompatible`. This logic necessarily dispatches differently depending on the schema of the objects being compared, and so there's lots of switch statements that previously had inline logic but are now changed into dispatch tables delegating to smaller functions.
The goal here is only to move code around without changing behavior, with one special exception: before I started working on this there were outstanding `go vet` warnings about how the early code in `assertObjectCompatible` was building errors about nullness inconsistencies, and so I fixed those …
=> plans/objchange: Reduce code complexity of the AssertObjectCompatible implementation details

rfc/20250108-naming-convention-for-context-vars.md
This is a lightweight RFC proposing that we adopt some cross-cutting naming conventions for variables of various different types whose names all include the noun "context", both to gradually improve existing confusion and inconsistency in the codebase and in particular to un-squat the name "ctx" that has emerged as the idiomatic name for a context.Context elsewhere in the Go ecosystem.
This proposal does not call for any immediate code changes. It is only an attempt to agree on some conventions to follow in future work on other projects.
[Rendered version](https://github.com/opentofu/opentofu/blob/rfc-context-naming-conventions/rfc/20250108-naming-convention-for-context-vars.md)
=> RFC: Naming convention for internal variables representing "contexts"

rfc/README.md
This documents the outcome of #2100 in a location that is hopefully easier to discover than that specific RFC itself.
This is a documentation-only change.
=> rfc: Update README.md to discuss RFC Tracking Issues

CHANGELOG.md, go.mod, go.sum
This includes a number of small enhancements and bug fixes compared to version v1.14.4 that we were previously using, as described in this commit's CHANGELOG update.
**Disclosure:** `go-cty` is my own project, and so this update includes several changes made by me along with changes made by external contributors. You can find more details in [the cty v1.16.1 changelog](https://github.com/zclconf/go-cty/blob/v1.16.1/CHANGELOG.md) and in [the full set of changes since v1.14.4](https://github.com/zclconf/go-cty/compare/v1.14.4..v1.16.1).
=> go.mod: Upgrade go-cty to v1.16.1

internal/backend/remote-state/s3/backend_test.go
I had assumed that these tests were run on main, will need to double check that pipeline.
This is the last place we are constructing remote.State without the constructor (requires encryption)
1.10.0
=> Fix S3 acceptance test panic, introduced in 1.7 encryption

website/docs/language/expressions/version-constraints.mdx
=> Add example on supporting both OpenTofu and Terraform versions to version-constraints.mdx

CHANGELOG.md, internal/configs/config.go, internal/configs/config_test.go, internal/configs/parser_test.go, internal/configs/testdata/provider-reqs/provider-reqs-root.tf
At some point the logic for import blocks was patched to allow the specifying of a provider: https://github.com/opentofu/opentofu/blob/972324e5ea54a7e02aebb0d0dd3020aad0be6ac8/internal/configs/module.go#L531-L543.  This was unfortunately only partially duplicated in https://github.com/opentofu/opentofu/blob/972324e5ea54a7e02aebb0d0dd3020aad0be6ac8/internal/configs/config.go#L435-L445
To fix this, we always assume that the provider known by the import block is intentional and is treated as such.
Resolves #1774
1.10.0
=> Use import provider instead of guess

go.mod, go.sum
=> [Backport v1.8] build(deps): bump github.com/hashicorp/go-slug from 0.12.2 to 0.16.3

go.mod, go.sum
=> [Backport v1.9] build(deps): bump github.com/hashicorp/go-slug from 0.12.2 to 0.16.3

go.mod, go.sum
=> [backport v1.7] build(deps): bump github.com/hashicorp/go-slug from 0.12.2 to 0.16.3

internal/providercache/installer.go
The `providercache.Installer.EnsureProviderVersions` function has grown very large as the various requirements for provider installation have evolved.
This is some initial work on breaking it into smaller parts. There is definitely more work to do here, but this kind of change (with large chunks of code moving around while being mostly-unmodified) tends to be hard to review so I'm intentionally stopping at this point with the intention of continuing this in a future PR.
These changes should not affect the observable behavior of OpenTofu in any way, which is supported by this change leaving all of the existing tests completely unchanged.
I worked on this mainly just as an example of what this sort of work might look like if we were to accept https://github.com/opentofu/opentofu/pull/2165 …
=> providercache: Decompose Installer.EnsureProviderVersions (partially)

CHANGELOG.md, internal/configs/module_test.go, internal/configs/provider_requirements.go, internal/configs/testdata/invalid-modules/multiple-required-providers-with-syntax-error/main.tf, internal/configs/testdata/invalid-modules/multiple-required-providers-with-syntax-error/other.tf
Resolves #2344
Instead of just adding a nil check, just return an empty RequiredProvider to ensure that down the line we are not getting a panic.
Checking the usage `decodeRequiredProvidersBlock` function, the changes made should have no other side-effects.
1.10.0
=> Fix: When a RequiredProvider is having syntax errors, return an empty one to allow further validations to generate their diags

CHANGELOG.md, internal/addrs/module_source_test.go, internal/getmodules/getter.go
=> [Backport 1.9] Add a new go-getter detector wrapper that can remove the query params before giving the src to the actual detector

CHANGELOG.md, internal/addrs/module_source_test.go, internal/getmodules/getter.go
=> [Backport 1.7] Add a new go-getter detector wrapper that can remove the query params before giving the src to the actual detector

.github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/compare-snapshots.yml, .github/workflows/pr-opened.yml, .github/workflows/release.yml, .github/workflows/update-top-issues-ranking.yml, .github/workflows/website.yml
This PR updates all the github actions if there are no breaking changes. Some of them didn't have a proper tag or release, however have upgraded their dependencies:
* `hashicorp/actions-set-product-version`
* `hashicorp/actions-generate-metadata`
* `hashicorp/actions-docker-build`
For those listed, we point to the latest commit, I left relevant comments.
I didn't upgrade `computology/packagecloud-github-action` since it doesn't have any relevant changes.
Also, I didn't upgrade `goreleaser/goreleaser-action` to the latest version, since it has breaking changes in there (goreleaser v2). I created a separate issue for that: https://github.com/opentofu/opentofu/issues/2477
Another note: `docker/setup-qemu-action` now requires [Actions Runner …
=> update all github actions with no breaking changes

internal/providers/provider.go
This PR explicitly groups what functions can be called on configured vs unconfigured providers.  This has been a bit of a "implied" concept for quite a while, and I figure it's time to make it explicit.
There is a lot more refactoring we could do to the codebase to clarify when a provider is configured or not, but for now splitting the interface is documentation / a starting point.
Follow up to #2370 
1.10.0
=> Clarify which functions exist on configured providers only

internal/addrs/map_test.go, internal/addrs/parse_ref.go
This is just another one for our complexity linting improvements in https://github.com/opentofu/opentofu/issues/2325.
As usual, the goal is to pass more of the complexity linting rules without changing the externally-observable behavior of OpenTofu at all.
---
Our complexity lint rules previously considered this function to have both too many statements and too many lines.
Factoring out more of the "single-attr ref" logic into the `parseSingleAttrRef` function eliminated one statement per case that was using it.
Factoring out the handling of module call references -- the most complex case this function handles -- into a separate `parseModuleCallRef` reduced it considerably more.
Removing the empty lines between the `case` statements was necessary after that just to get below the line …
=> addrs: Refactor parseRef to parse complexity linters

internal/command/views/json/diagnostic.go
This is yet another contribution to https://github.com/opentofu/opentofu/issues/2325.
The previous code structure was made more awkward by having to work around all being together in one function -- particularly the part iterating over the values used in an expression -- and so the new layout is quite different and thus the diff is hard to read. However, there are intentionally no test changes in this commit to help us be confident that this has not regressed anything, and the existing unit tests for this component seem quite comprehensive.
If the noise of the diff gets in your way, you might like to refer to [the new version of the code](https://github.com/opentofu/opentofu/blob/f-complexlint-jsonviews/internal/command/views/json/diagnostic.go#L137) directly, to see how well it now reads …
=> command/views/json: Refactor NewDiagnostic into multiple functions

.gitignore
While playing around with the codebase I noticed that coverage.html and coverage.out are not yet in the git ignore, so I decided to add them.
=> gitignore: add coverage.out and coverage.html

internal/configs/configload/testing.go, internal/tofu/bench_many_instances_test.go, internal/tofu/context_test.go, internal/tofu/opentf_test.go
Although we don't promise that OpenTofu will work well with more than a few hundred resource instances in a particular configuration, we know that some people do use it that way and they sometimes find and share opportunities for improving performance due to those opportunities being easier to spot at large scale.
These two benchmarks aim to help us measure improvements that affect the pure overhead of the core language runtime, without any real provider calls and without the CLI layer's contributions, so that we can more easily compare before and after of changes when we're either trying to understand a reported performance regression or we're trying out potential performance improvements.
As noted in the comments inline, the presence of these benchmarks is not intended to represent a …
=> tofu: Some benchmarks for situations with many instances

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
Ensure attribute names are correctly quoted in generated config when they contain characters that make them invalid identifiers (e.g., dots, double quotes).
- Use `hclsyntax.ValidIdentifier` to check if an attribute name needs quoting.
- Convert invalid identifiers to valid HCL strings using `hclwrite.TokensForValue`.
- Add test cases for attributes with dots and double quotes to verify correctness.
Resolves #2520
1.10.0
=> fix(genconfig): properly quote attribute names when necessary

CONTRIBUTING.md
1.10.0
- [ x I have added meaningful comments to all exported functions, variables, and structs.
=> fix: small typo on OpenTofu name on CONTRIBUTING guide

rfc/20241118-module-vars-and-outputs-deprecation.md
Part of https://github.com/opentofu/opentofu/issues/1005.
In this PR I summarized the discussion around variables and outputs deprecation; provided answers to some of the questions that popped up; and described how to approach this feature technically.
[Rendered version.](https://github.com/opentofu/opentofu/blob/mod-depr-rfc/rfc/20241118-module-vars-and-outputs-deprecation.md)
Not applicable
=> [RFC] Deprecation of module variables and outputs

rfc/20241113-pragmatic-complexity-linting.md, rfc/20250303-linter-policy.md
Early in the life of the OpenTofu project the team adopted a large [golangci-lint](https://golangci-lint.run/) configuration containing a rather arbitrary assortment of linter configurations inherited from another project. Because OpenTofu's predecessor project did not use these lint rules, there was an insurmountable number of lint failures on existing code and so we've been working under a compromise where the lint rules are only applied to new code added after the adoption of that linter configuration.
In the meantime we've got considerable experience working under these lint rules and have encountered some friction:
- Code maintenence work often gets bogged down in resolving previously-quieted lint failures, making that work take more time and adding risk in cases where fixing the …
=> rfc: OpenTofu Codebase Linting Policy

CHANGELOG.md, internal/lang/funcs/collection.go, internal/lang/funcs/collection_test.go
Previously the "transpose" function would panic if any of the given lists were null or if any of the strings inside the given lists were null.
Null values _are_ invalid in those positions because we can't project null values into the keys of the resulting map, but we should return explicit error messages in those cases rather than causing a Go panic.
Before this fix:
```
> transpose(null)
╷
│ Error: Invalid function argument
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ Invalid value for "values" parameter: argument must not be null.
╵
> transpose({"foo": null})
╷
│ Error: Error in function call
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ Call to function "transpose" failed: panic in function implementation: can't use ElementIterator on …
```
=> lang/funcs: transpose panics with null elements

go.mod, internal/getproviders/oci_registry_mirror_source.go, internal/getproviders/oci_registry_mirror_source_test.go, internal/getproviders/package_location_oci_blob_archive.go, internal/getproviders/package_location_oci_blob_archive_test.go
This is part of https://github.com/opentofu/opentofu/issues/2540, and implements the [OCI Mirror Provider Installation Source](https://github.com/opentofu/opentofu/blob/b47237d410bfeaa86aca84a79bde973e3d8a724e/rfc/20241206-oci-registries/9-provider-implementation-details.md#oci-mirror-provider-installation-source).
An "OCI Mirror" is essentially just like the existing idea of "network mirror" but using OCI Distribution protocol and manifest conventions instead of [OpenTofu's own Provider Mirror Protocol](https://opentofu.org/docs/internals/provider-network-mirror-protocol/).
Therefore there are some direct analogies here:
* `getproviders.OCIRegistryMirrorSource` is analogous to `getproviders.HTTPMirrorSource`, dealing with the discovery of available versions and fetching the package …
=> getproviders: New provider installation method for OCI Registries

rfc/20250314-security-patch-policy.md
OpenTofu is often used in environments that make use of software that attempts to detect whether our releases are indirectly affected by security advisories in upstream dependencies.
Unfortunately, there is a considerable variation in the accuracy of different tools in this category, and some have quite a high false-positive rate. This policy aims to find a balance where we can focus on actual vulnerabilities and minimize time spent responding to false-positive reports.
[Rendered Version](https://github.com/opentofu/opentofu/blob/rfc-security-patch-policy/rfc/20250314-security-patch-policy.md)
---
Note that accepting this proposal implies some technical implementation work, to set up scheduled runs of `govulncheck` against all non-EOL release branches and `main` in this repository.
I kept …
=> rfc: Security Advisory Policy for Upstream Dependencies

CHANGELOG.md, website/docs/cli/config/config-file.mdx, website/docs/cli/oci_registries/credentials.mdx, website/docs/cli/oci_registries/index.mdx, website/docs/cli/oci_registries/provider-mirror.mdx
This is part of https://github.com/opentofu/opentofu/issues/2540.
This is a kinda-scrappy first pass at the OCI-registry-related docs intended to be sufficient just for the forthcoming alpha release.
I expect we'll revise this before final, but this is intended just to help folks who want to try out the early form of these features during our prereleases.
I decided to group together all of the OCI-Registry-related documentation content into a new section since I expect that anyone who is invested in using these features is likely to want to use all or most of them. This also minimizes the amount of new content added to the already-very-crowded "CLI Configuration" documentation page, with it just mentioning the new headline stuff and then linking to the new documentation section for all of …
=> website: Very early docs for the new OCI Registry functionality

internal/getproviders/oci_registry_mirror_source.go, internal/getproviders/oci_registry_mirror_source_test.go, internal/getproviders/package_location_oci_blob_archive.go, internal/getproviders/package_location_oci_blob_archive_test.go, website/docs/cli/oci_registries/provider-mirror.mdx
(This is part of https://github.com/opentofu/opentofu/issues/2540.)
The initial design of this attempted to maximize our flexibility to make backward-compatible changes to the manifest structure for providers in future OpenTofu releases, by expecting the `layers` entry describing the provider package to include a specific `artifactType` and ignoring any layers with different `artifactType` values.
However, general-purpose tools for constructing image manifests don't tend to allow setting the `artifactType` in a layer descriptor, so we'll drop that requirement as a measure of pragmatism.
This implies that the only possible extension we could make for _layers in particular_ in a future release is to support an additional archive format that would presumably then be used in much the same way …
=> getproviders: Don't require artifactType on OCI layers for providers

rfc/20250327-providerinst-auth-hashes.md
A new approach to reporting provider package authentication results in the getproviders package, which unifies the authentication result with the "allowed hashes" and gives the provider installer more detail to use when making other decisions based on the authentication results.
This is primarily motivated by https://github.com/opentofu/opentofu/issues/2540, but separated out because it would also benefit the existing `network_mirror` and `filesystem_mirror` installation methods, and set us up better for various potential future extensions to our provider installation process.
[Rendered Version](https://github.com/opentofu/opentofu/blob/rfc-providerinst-auth-hashes/rfc/20250327-providerinst-auth-hashes.md)
=> rfc: Tracking Provider Authentication on a Per-hash Basis

CHANGELOG.md, internal/backend/remote-state/pg/backend.go, internal/backend/remote-state/pg/backend_state.go, internal/backend/remote-state/pg/backend_test.go, internal/backend/remote-state/pg/client.go, internal/backend/remote-state/pg/client_test.go, website/docs/language/settings/backends/pg.mdx
Make it possible to specify the table name and index name when using PG backend. 
This makes it easier to use PG backend provider for scenarios such as using Terragrunt with convention based state storage per a `terragrunt.hcl` file by providing an additional layer of grouping.
Having many tables vs many schemas could be preferred by some users and the tools they use too.
=> Make table name and index name a config value for PG backend

cmd/tofu/commands.go, cmd/tofu/main.go, cmd/tofu/module_source.go, cmd/tofu/oci_distribution.go, cmd/tofu/provider_source.go, internal/checks/state_test.go, internal/command/command_test.go, internal/command/get_test.go, internal/command/init_test.go, internal/command/meta.go, internal/command/meta_config.go, internal/getmodules/installer.go, internal/getmodules/oci_getter.go, internal/initwd/from_module.go, internal/initwd/from_module_test.go, internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testing.go, internal/lang/globalref/analyzer_test.go, internal/refactoring/move_validate_test.go, internal/tofu/opentf_test.go
This is for https://github.com/opentofu/opentofu/issues/2540, and aims to complete the work described in [OCI Client for the Module Package Installer](https://github.com/opentofu/opentofu/blob/b47237d410bfeaa86aca84a79bde973e3d8a724e/rfc/20241206-oci-registries/8-auth-implementation-details.md#oci-client-for-the-module-package-installer).
I suggest reviewing this [on a commit-by-commit basis](https://github.com/opentofu/opentofu/pull/2661/commits), since the message in each commit will hopefully give some context on what each step of the refactoring was aiming to achieve.
The overall idea here is to continue the previous work in making the module installer follow a similar dependency inversion style as the provider installer, where `package main` is responsible for configuration the …
=> Dependency inversion style for module package installer

.github/workflows/checks.yml
As discovered by @yottta and tracked on https://github.com/opentofu/opentofu/pull/2678#issuecomment-2811913812, it seems there's a mismatch of the Go architecture being used on `GOARCH` and on the Mac OS X Runner:
Relates to #2678
1.10.0
=> Change Go arch from amd64 to arm64 on macos-latest

internal/command/command_test.go, internal/command/get_test.go, internal/command/init_test.go, internal/command/testdata/init-module-early-eval/init-module-early-eval.tf, internal/command/testdata/init-registry-module/main.tf
We previously had two tests of how the module installer responds to cancellation (e.g. `SIGINT`) which were flakey because they tried to rely on the cancellation being detected at some arbitrary point before the module installer attempted to make a request, which isn't guaranteed in practice because our interrupt mechanism only aims to cause OpenTofu to exit "soon", with no guarantee about how much ongoing progress it will make before it does.
To make these tests more robust, we'll now instead tell the module installer to install from a real HTTP server that is intentionally designed to stall the client by accepting its request but then just leaving the connection open without responding.
This means that we can now test the more realistic situation of the cancel signal being triggered …
=> command: Improve reliability of module install cancel tests

cmd/tofu/oci_distribution.go, cmd/tofu/oci_distribution_test.go
This is for https://github.com/opentofu/opentofu/issues/2540.
Our OCI credentials policy layer expects to be provided with an implementation of the Docker credential helper protocol as part of its "credentials lookup environment".
Since we're already using ORAS-Go for everything else we'll just wrap their implementation of this protocol here too, and then translate the result into our own type since we've been intentionally avoiding making ORAS-Go types part of any of our exported package APIs.
There is no additional CHANGELOG entry for this because it is already covered by the broader entries about supporting OCI registries for provider/module installation.
---
Because this is the concrete implementation of an interface we introduced so that unit tests elsewhere could fake it, it's …
=> main: Docker credential helper support for OCI registry auth

website/docs/cli/oci_registries/index.mdx, website/docs/cli/oci_registries/module-package.mdx, website/docs/language/modules/sources.mdx
This is for https://github.com/opentofu/opentofu/issues/2540.
This is a first draft of documentation describing our new capability to treat artifacts in OCI Distribution repositories as a new kind of remote module package.
This documentation includes both some caller-focused documentation that extends our existing "Module Sources" page, and some documentation intended more for the author of a module package describing how they could publish their package as an OCI artifact that OpenTofu will accept.
As usual, we'll continue to refine this documentation based on feedback during the prerelease period and beyond.
=> website: Documentation for module packages in OCI repositories

internal/command/plan.go, website/docs/cli/commands/plan.mdx, website/docs/cli/state/resource-addressing.mdx
This adds documentation for the features introduced by https://github.com/opentofu/opentofu/pull/2620.
---
While updating the `tofu plan -help` output I noticed that in other recent work a variety of inconsistencies had accumulated, and so fixed them since I needed to re-wrap most of the options to accommodate the new column sizes anyway:
- The line-wrapping length was somewhat erratic. It's now restored to being a maximum of 80 columns per line.
- Options that take string arguments were all presented as `-name=placeholder`, except for `-lock-timeout` which was previously given as `-lock-timeout=0s`. Setting this to `0s` is pointless because that's the default anyway, so now includes a more realistic example.
- Boolean options that default to being on were not all consistently shown with …
=> Documentation for the new `-target-file` and `-exclude-file` planning options

internal/command/init.go, internal/providercache/installer.go, internal/providercache/installer_events.go, internal/providercache/installer_events_test.go, internal/providercache/installer_test.go
Both the OTEL and Provider Cache work both ran up against some intersting workarounds needed for this function.
This refactoring does slightly change the events emitted by the installer, but looking at the usages it should be safe.
Recommended to review with whitespace ignored.
See #1878 and #2665
1.10.0
=> Refactor the provider installer loop

CHANGELOG.md, internal/configs/test_file.go, internal/configs/test_file_test.go, website/docs/cli/commands/test/index.mdx
Resolves #2419 
Resolves #2418
By removing the restriction on remote module repositories, we're able to use everything that module sources support, like generic git URLs, bitbucket and mercurial URLs.
The original [PR (pre-fork and MPL)](https://github.com/hashicorp/terraform/pull/33456) doesn't mention why it doesn't support remote test sources, it just says that [it's not supported](https://github.com/hashicorp/terraform/pull/33456/files#diff-eb61f09ed17a251bb70a77789c6af4199be25d722c20789d245f149f573f1bbfR377). I assumed they didn't fully test and didn't want to add support and maybe add for a future iteration, but while doing the tests, all of them worked fine without adding any additional code.
Tested with:
1.10.0
=> Add remote sources to module on tofu test

docs/architecture.md
Fix a broken link on Tofu docs.
1.10.0
=> fix: point link to tofu docs

CHANGELOG.md, website/docs/internals/json-format.mdx, website/docs/language/modules/develop/refactoring.mdx, website/docs/language/values/outputs.mdx, website/docs/language/values/variables.mdx
Part of #1005 and #2555. Documentation of `deprecated` attributes for module variables and outputs.
1.10.0
=> add website docs for deprecation attrs

CHANGELOG.md, internal/configs/removed.go, internal/configs/removed_test.go, internal/configs/testdata/valid-files/refactoring.tf, internal/configs/testdata/valid-modules/removed-blocks/removed-blocks-1.tf, internal/configs/testdata/valid-modules/removed-blocks/removed-blocks-2.tf, internal/refactoring/remove_statement.go, internal/refactoring/remove_statement_test.go, internal/tofu/context_plan.go, internal/tofu/graph_builder_plan.go, internal/tofu/node_resource_abstract.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_abstract_instance_test.go, internal/tofu/node_resource_deposed.go, internal/tofu/node_resource_deposed_test.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/node_resource_plan_orphan_test.go, internal/tofu/testdata/transform-diff-creates-destroy-node/child/main.tf, internal/tofu/testdata/transform-diff-creates-destroy-node/main.tf, internal/tofu/transform_destroy_edge_test.go, internal/tofu/transform_diff.go, internal/tofu/transform_diff_test.go, website/docs/language/modules/syntax.mdx, website/docs/language/resources/syntax.mdx
Resolves #2556
_Recommended to be reviewed per commit since there are a lot of changes. Reworked the commit history and split the changes per commit and added information in each of those for easing the review a little_
This PR adds two new functionalities on the `removed` block:
* Now supports a `lifecycle` block that can have one attribute: `destroy` that can have two values `true`/`false`.
* Now supports `provisioner` blocks for the author of the `removed` block to be able to move the `provisioner` blocks from the actual removed `resource`. This is needed because `removed` and the targeted `resource` block cannot be in the same time in the configuration. Therefore, the user needs to have an option to still execute the provisioners before destroying the `resource`.
* Some additional …
=> Enhance `removed` block with `lifecycle` and `provisioner` functionalities

internal/getproviders/package_authentication.go, internal/getproviders/package_authentication_test.go
This `SigningSkipped` method is supposed to return true only in the narrow case where we have hashes that came from the provider's origin registry but we didn't have any signing keys to verify them against.
Previously it was returning true if any of the hashes came from the registry even if those hashes were also verified using a signing key, which violated the assumptions made by the `tofu init` UI and caused it to incorrectly report that the provider didn't have any signing keys even when it did.
This is a cosmetic fix only because the validation behavior was previously correct, and only this helper function for summarizing the validation result in the UI was incorrect.
These helper functions were not previously covered by any unit tests, so this change also includes new testing for all …
=> getproviders: `PackageAuthenticationResult.SigningSkipped` must return false when the package was signed

internal/command/show.go
This PR fixes failing test on main. The use case is to call `tofu show -json` with the following config (without the init call):
```hcl
terraform {
required_providers {
null = {
version = "3.1.0"
}
}
}
resource null_resource "foo" {
}
```
1.10.0
=> keep original workaround when there is no state for tofu show

internal/command/e2etest/provider_plugin_test.go, internal/command/e2etest/testdata/provider-global-cache/.terraform.lock.hcl, internal/command/e2etest/testdata/provider-global-cache/main.tf, internal/flock/filesystem_lock_unix.go, internal/flock/filesystem_lock_windows.go, internal/getproviders/package_location_local_archive.go, internal/providercache/dir.go, internal/providercache/installer.go, internal/states/statemgr/filesystem.go, website/docs/cli/config/config-file.mdx
This pr moves the standard local state file locking into a common package and refactors it for use in both package locking and local state file locking.  Additional real world testing has been performed by running the equivalence tests with the `-parallel 16` flag.
Resolves #1483
1.9.0
=> Provider plugin cache locking

internal/command/test.go, website/docs/cli/commands/test/index.mdx
Adds more information between the interaction with -test-directory and -filter:
1. A warning to tofu test docs;
2. An extra explanation on tofu test -filter CLI docs;
Resolves #182
1.10.0
=> docs: clarifying -filter and -test-directory behavior in tofu test

docs/tracing.md
> Rendered view here: https://github.com/opentofu/opentofu/blob/tracing-docs-for-contributors/docs/tracing.md
Add comprehensive documentation for OpenTofu's OpenTelemetry tracing implementation. This guide explains:
- How end users can enable and use distributed tracing to debug performance
- How to set up local tracing with Jaeger for investigation
- Guidelines for contributors adding instrumentation
- Best practices for span naming and attribute conventions
This documentation supports recent OpenTelemetry implementation work in PRs #2694 and #2665, following the design outlined in RFC 20250129-Tracing-For-Extra-Context.md.
Part of #2664
1.10.0
=> Add tracing documentation

internal/registry/client_test.go
The hard cast to mockRoundTripper caused issues as tests relied on client having full control of the transport, which is not always the case
Helps #2711
1.10.0
=> Replace custom mocks with httptest in registry client tests to improve maintainability

internal/command/providers_lock.go, internal/providercache/installer.go, internal/tracing/traceattrs/traceattrs.go
Helps give us some visibility for #2563 
Part of the OTEL Tracing implementation tracked here #2664
- ?
=> [OpenTelemetry] Add traces to `providers lock` command

internal/providercache/dir.go, internal/providercache/dir_modify.go, internal/providercache/dir_testing.go
This is in preparation for parallelizing the package installation process.  Most of the "locate package(s)" functions on the Dir struct are only currently used by tests.  The only one that is used by non-test code is Dir.ProviderVersion, which is really just a path construction and `os.Stat()` call.
On the other hand, we had the metaCache structure on Dir which needed to be wiped in preparation for a a "rescan" every time we think the dir on disk was modified.  As it's only current utility was exercised during tests, it made sense to remove the cache and do the re-scan for those cases.
As these changes also reduce the number of times we scan the filesystem looking for providers, this could have a mild performance improvement for situations with a massive cache directory or slow networked …
=> Remove providercache.Dir.metaCache

internal/command/cliconfig/ociauthconfig/docker_cli_credentials_config.go, internal/command/cliconfig/ociauthconfig/docker_cli_credentials_config_test.go
Our handling of Docker-style configuration files as an authentication source is intentionally a bit of a compromise because various other software reads and writes these files despite there being no single standard for the format, and unfortunately different software makes different tradeoffs when the configuration is ambiguous.
One oddity that we didn't notice originally is that the "login" command of some programs will respect the "credsStore" property for storing new credentials using a helper program instead of storing them in cleartext in the config file BUT will still create an empty entry in the "auths" property for whatever domain the operator logged into. Our logic wasn't built to tolerate an "auths" entry without an "auth" property inside it and so we would then fail to select …
=> ociauthconfig: Tolerate weird "auths" objects in Docker-style configs

cmd/tofu/oci_distribution.go, internal/getmodules/oci_getter.go, internal/getproviders/oci_registry_mirror_source.go, internal/getproviders/package_location_oci_blob_archive.go
Continuing our recent effort to add OpenTelemetry tracing to the various `tofu init` steps, this adds instrumentation to the following OCI Registry-related features:
- The cross-cutting authentication handling bits in `package main`.
- The "getter" we use for module installation.
- The provider mirror source and associated package location we use for provider installation.
---
While I was working on this stuff in earlier commits I noticed that the provider installation path was having to re-request authentication tokens multiple times during provider installation when interacting with `ghcr.io`, since that registry requires an initial step of trading the provided credentials for a temporary bearer token.
Adding telemetry tracing to this of course then made it clear how much time we were …
=> OpenTelemetry tracing for our OCI Registry interactions

internal/command/e2etest/provider_plugin_test.go
This test uses a temporary file as an overridden CLI configuration to force using a specific plugin cache directory, but temporary file paths contain backslashes on Windows and the CLI configuration syntax is HCL so would require backslashes to be escaped.
Since Windows will accept forward-slash paths as a supported variation, and we typically recommend that folks write paths that way in HCL for portability anyway, this uses filepath.ToSlash to force consistent use of slashes on all platforms. It would also have been reasonable to use a %q format verb to use Go's string quoting syntax, but that's not the way we typically recommend folks hand-write their CLI configurations and so this way is just-so-slightly more "realistic".
(This test has been failing in the e2etest runs on `main` since …
=> e2etest: TestProviderGlobalCache generate valid CLI config on Windows

internal/backend/local/backend_local.go, internal/providercache/dir_modify.go, internal/providercache/dir_modify_test.go, internal/providercache/installer.go
This is a similar idea as https://github.com/opentofu/opentofu/pull/2755 (with similar background info) but now deals with the parts of the non-test code that were using `context.TODO` in places where there was already a real `context.Context` somewhere close by that we can now use.
This shouldn't change the externally-observable behavior of OpenTofu, so there won't be a changelog entry for this one.
---
This commit leaves quite a few other uses of `context.TODO` in place because they are inside implementations of interfaces whose methods aren't yet updated to pass `context.Context`, and so we'll need some more invasive commits to update those interfaces and all of their implementations and callers before we'll be able to finally eradicate `context.TODO` and propagate our trace spans …
=> backend/local and providercache: Clean up some leftover `context.TODO`

internal/tfdiags/override.go, internal/tfdiags/override_test.go
This PR just cherry-picked https://github.com/opentofu/opentofu/commit/4a9f10a726ef6a925393528336db51ecf77e75f0 in order to make those changes available to #2705.
-------
This package has two different mechanisms that can cause an existing diagnostic to be replaced with a modified version:
- "Override" effectively wraps an arbitrary other diagnostic with a new severity and optional new "extra info".
- Contextual diagnostics allow a diagnostic to be created in one place with some incomplete information, and then "elaborated" in another place where more information is available.
Those two mechanisms did not previously interact well together: passing a contextual diagnostic to Override would prevent its elaboration process from taking effect.
Now the overriddenDiagnostic type -- …
=> tfdiags: Override cooperates with contextual diagnostics

CHANGELOG.md, internal/backend/remote-state/azure/backend_state.go, internal/backend/remote-state/azure/backend_test.go, internal/backend/remote-state/azure/client_test.go, internal/backend/remote-state/azure/helpers_test.go
Resolves #2700 
Adding pagination to the fetching of Azure backend workspaces.
It solves the problem when the workspace is not returned on the first page of results. The user should be mindful if you have a **Blob container** full of files, it's going to take an extra time to find the blob since it's extra requests will be done to find the workspaces.
I was able to reproduce the issue linked above by creating blobs with the following command:
```
```
The example tofu configuration was:
```
terraform {
backend "azurerm" {
resource_group_name  = "test"
storage_account_name = "opentofutest"
container_name       = "tfstate"
key                  = "prod.terraform.tfstate"
}
}
```
Acceptance Tests:
```
(base) ➜  opentofu git:(2700-az-list) ✗ go test -v ./... -run …
```
=> Adding pagination to azure backend workspaces

internal/plans/mode.go, internal/tofu/context_apply.go, internal/tofu/context_eval.go, internal/tofu/context_input.go, internal/tofu/context_plan.go, internal/tofu/context_validate.go, internal/tofu/node_provider.go, internal/tofu/node_provider_test.go, internal/tofu/node_resource_abstract.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_apply_instance.go, internal/tofu/node_resource_deposed.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/node_resource_validate.go, internal/tracing/data.go
(This is for https://github.com/opentofu/opentofu/issues/2664.)
This introduces two new levels of trace span hierarchy that belong to the core language runtime:
1. Phases: these top-level spans distinguish between the validation phase, the input phase, the planning phase, and the apply phase, mainly just as context to help group together the items at the next level.
These all intentionally include the word "phase" because I know from previous experience that newcomers often get confused between the OpenTofu CLI commands and the core runtime phases they cause. For example, `tofu apply`'s work includes all three phases, even though the command name only mentions "apply".
3. High-level operations: these roughly correspond to the operations that OpenTofu already reports in its UI, such as …
=> tofu: Plumb a reasonable amount of OpenTelemetry tracing into OpenTofu Core

cmd/tofu/main.go, internal/tracing/init.go, internal/tracing/utils.go
Updated OpenTelemetry initialization to accept and propagate the trace context, enabling trace linkage via `TRACEPARENT` and `TRACESTATE` environment variables.
Part of #2664 
1.10.0
=> Consume TRACEPARENT and TRACESTATE to construct the OTel trace context

internal/backend/remote-state/azure/backend_test.go, internal/backend/remote-state/azure/client_test.go, internal/backend/remote-state/azure/helpers_test.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client_test.go, internal/backend/remote/backend_context_test.go, internal/cloud/backend_context_test.go, internal/cloud/backend_run_warning_test.go, internal/cloud/backend_taskStages_test.go, internal/providercache/dir_modify_test.go, internal/providercache/installer_test.go
When [`context.Context`](https://pkg.go.dev/context#Context) was new, APIs using it arrived sporadically and so the Go team introduced [`context.TODO()`](https://pkg.go.dev/context#TODO) as an explicit way to say "I need a context here but I don't yet have a useful one to provide".
It took quite a while for there to be an established pattern for contexts in tests, but now there is finally [`testing.T.Context`](https://pkg.go.dev/testing#T.Context) which returns a context that gets cancelled once the test is complete, and so that's a good parent context to use for all contexts belonging to a test case.
This commit therefore mechanically replaces every use of `context.TODO` in our test cases throughout the codebase with a call to `t.Context` instead. There were a small number of tests that …
=> various: Remove context.TODO() usage from all tests

website/docs/language/state/examples/encryption/fallback_from_unencrypted.tf, website/docs/language/state/examples/encryption/sample.tf
On the `State and Plan Encryption` page, some code examples comprise an input variable for the encryption passphrase. This PR marks this input variable as sensitive.
Despite being only code examples, I believe it is important to educate about good practices, especially when it comes to security. I myself got surprised to see my passphrase displayed on screen when experimenting with the code examples.
1.10.0
=> docs(state): mark input passphrase as sensitive

internal/backend/local/backend_apply.go, internal/backend/local/backend_plan.go, internal/backend/local/backend_refresh.go, internal/command/meta.go, internal/command/providers_schema.go, internal/command/state_show.go, internal/command/test.go, internal/tofu/context.go, internal/tofu/context_input.go, internal/tofu/context_plan.go, internal/tofu/context_plugins.go, internal/tofu/eval_context_builtin.go, internal/tofu/evaluate.go, internal/tofu/evaluate_valid.go, internal/tofu/schemas.go, internal/tofu/transform_attach_schema.go
(This is for https://github.com/opentofu/opentofu/issues/2664.)
In https://github.com/opentofu/opentofu/pull/2749 I skipped adding a span for the time spent populating the schema cache because the functions involved in that were not yet updated to take `context.Context` arguments.
This PR makes a good start on addressing that by adding `context.Context` arguments as deeply as we can go without modifying any interface definitions (which would require a _lot_ of mechanical updates), with the intention of continuing this work after we've dealt with the broader (and more disruptive) concerns of adding context parameters to the methods of `tofu.EvalContext`, `tofu.GraphTransformer`, and `providers.Interface`.
In a few spots this PR uses [`context.TODO()`](https://pkg.go.dev/context#TODO) as a …
=> tofu: Some initial context.Context plumbing for the schema lookup codepaths

internal/command/init.go, internal/command/init_test.go, internal/command/providers_lock.go, internal/providercache/dir.go, internal/providercache/dir_modify.go, internal/providercache/dir_modify_test.go, internal/providercache/installer.go, internal/providercache/installer_events.go, internal/providercache/installer_events_test.go, internal/providercache/installer_test.go
This unifies a lot of the duplicate logic between the global cache install path and the normal install path. 
It is the result of a few conversations between @apparentlymart and myself.  The original approach had a much wider lock and was a bit harder to wrap your head around.  With this refactoring, it's much more simply scoped.
1.10.0
=> Alternate approach to linking and locking the global cache

cmd/tofu/main.go, cmd/tofu/module_source.go, cmd/tofu/oci_distribution.go, internal/command/command_test.go, internal/command/get_test.go, internal/command/init_test.go, internal/command/login.go, internal/command/meta_config.go, internal/command/providers_mirror.go, internal/command/webbrowser/mock.go, internal/configs/configload/loader.go, internal/configs/configload/module_mgr.go, internal/getmodules/getter.go, internal/getmodules/installer.go, internal/getproviders/didyoumean.go, internal/getproviders/http_mirror_source.go, internal/getproviders/package_location_http_archive.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go, internal/httpclient/client.go, internal/httpclient/client_test.go, internal/initwd/from_module_test.go, internal/initwd/module_install_test.go, internal/initwd/testing.go, internal/lang/globalref/analyzer_test.go, internal/refactoring/move_validate_test.go, internal/registry/client.go, internal/registry/client_test.go, internal/tofu/opentf_test.go
This is for https://github.com/opentofu/opentofu/issues/2664.
So far we've been adding direct calls to `otelhttp.NewTransport` in various localized places so that we can be selective about where we generate trace spans for HTTP requests, since generating spans without an active trace causes a new trace to be started, and that makes noise in the collector.
However, that's contrary to our existing goal of centralizing the "get me a suitably-configured HTTP client" rules in just one place, so that we can gradually change our standards over time in a central location.
As a compromise then, we'll pass `context.Context` into `httpclient.New` and use the presence of an active span in that context as a heuristic for whether it's okay to generate trace spans for any requests that are subsequently …
=> httpclient: Add OTel tracing automatically when needed

internal/command/apply.go, internal/command/arguments/apply.go, internal/command/arguments/plan.go, internal/command/arguments/view.go, internal/command/arguments/view_test.go, internal/command/plan.go, rfc/20241118-module-vars-and-outputs-deprecation.md, website/docs/cli/commands/apply.mdx, website/docs/cli/commands/plan.mdx, website/docs/language/values/outputs.mdx, website/docs/language/values/variables.mdx
Based on the agreement from the [community slack](https://opentofucommunity.slack.com/archives/C05RKE7PS72/p1746629411144469), we are renaming the cli argument that controls the deprecation warnings to accommodate more possible future functions regarding "deprecation".
Part of #2555
1.10.0
=> Rename the CLI arg for deprecation outputs/variables

internal/getproviders/mock_source.go, internal/getproviders/multi_source.go, internal/getproviders/package_authentication_test.go, internal/getproviders/registry_client_test.go
=> Fix lint issues in internal/getproviders

cmd/tofu/commands.go, cmd/tofu/main.go, cmd/tofu/provider_source.go, cmd/tofu/registries_disco.go, internal/command/command_test.go, internal/command/meta.go, internal/command/meta_config.go, internal/command/providers_lock.go, internal/command/providers_mirror.go, internal/getproviders/http_mirror_source.go, internal/getproviders/http_mirror_source_test.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go, internal/getproviders/registry_source_test.go, internal/httpclient/registry_client.go, internal/providercache/installer_test.go, internal/registry/client.go, internal/registry/client_test.go
The primary reason for this change is that `registry.NewClient` was originally imposing its own decision about service discovery request policy on every other user of the shared disco.Disco object by modifying it directly, as I discovered while investigating https://github.com/opentofu/opentofu/pull/2772#issuecomment-2867153130.
We have been moving towards using a dependency inversion style where package main is responsible for deciding how everything should be configured based on global CLI arguments, environment variables, and the CLI configuration, and so this commit moves to using that model for the HTTP clients used by the module and provider registry client code.
In particular, this makes explicit what was previously hidden away: that all service discovery requests are made using …
=> registry+getproviders: Registry client policy centralized in `package main`

CHANGELOG.md, internal/command/clistate/local_state.go
In 6162cde6ffde8436ff82aa42b50f7fe7d44fb9e1, a bug was introduced where creating a new local statefile would ignore file creation errors.
1.10.0
=> Fix potential loss of local state

go.mod, go.sum, internal/configs/configschema/coerce_value_test.go, internal/plans/objchange/compatible_test.go, internal/tofu/eval_variable_test.go
This upstream release introduces more detailed error messages for many type conversion-related errors.
`go-cty` is my personal project, but [Spacelift](https://spacelift.io/) sponsored my work on this particular upstream change as part of my work on OpenTofu.
---
This was motivated by the same feedback that motivated https://github.com/opentofu/opentofu/pull/2815. When combined with that PR, the error message given in that PR's description becomes:
```
╷
│ Error: Invalid template interpolation value
│ 
│   on diags-missing-exprvals.tf line 8, in output "example":
│    8:     for x in [1, {}] : "Hello, ${x}!"
│     ├────────────────
│     │ x is object with no attributes
│ 
│ Cannot include the given value in a string template: string required, but have object.
╵
```
With these two …
=> go.mod: go get github.com/zclconf/go-cty@v1.16.3

internal/tofu/transform_destroy_edge.go
This would have potentially caused more iterations of the loop, which is already approaching n*2 time.
Given that the loop would already run until all possible nodes would be pruned, this change just adjusts it to prune more items in the same iteration instead of breaking it into more iterations.
1.10.0
=> Fix iteration issue in transform_destroy

CHANGELOG.md, internal/command/e2etest/providers_tamper_test.go, internal/command/e2etest/testdata/predecessor-dependency-lock-file/.terraform.lock.hcl, internal/command/e2etest/testdata/predecessor-dependency-lock-file/predecessor-dependency-lock-file.tf, internal/command/meta_dependencies.go, internal/depsfile/locks.go, internal/depsfile/locks_test.go
This fixes https://github.com/opentofu/opentofu/issues/2775, implementing the idea from https://github.com/opentofu/opentofu/issues/2775#issuecomment-2867984995.
This relies on the unintended implementation detail that OpenTofu will accept a dependency lock file entry with no hashes and use it only for its version selection. Since that's just an accidental consequence of how things are implemented rather than something the system was designed to support, I reviewed the provider installer code to make sure this isn't violating any assumptions that might affect less common cases such as installing with customized provider installation method. There are more details in a comment below.
=> Automatically translate dependency lock file entries when switching from OpenTofu's predecessor

CHANGELOG.md, internal/command/views/json/diagnostic.go, internal/command/views/json/diagnostic_test.go, internal/command/views/json/testdata/diagnostic/error-with-source-code-subject-and-expression-with-local-symbol.json
This code was designed to keep trying gradually-shorter traversals until it finds something that can be evaluated, because we're probably reporting that the given expression wasn't actually valid and so it's possible that one of the references we're trying to describe was the cause of the problem in the first place.
However, there was an off-by-one error in the termination condition that prevented this from working for the top-level symbols that are typically introduced by language constructs that generate child scopes, such as a `for` expression's iteration symbols. We'll now try to find a value for even a single-step traversal, which means that we can report such things as which iteration of a for expression we were on when an error occurred.
Due to how the tests for this function are …
=> command/views/json: Diagnostic context for single-symbol traversals

.github/pull_request_template.md
This field has not been useful from the perspective of the maintainers of the project.  In the rare circumstance that it is needed, it can be added to a specific PR.
=> Remove Target Release PR template field

internal/tofu/eval_provider.go, internal/tofu/node_provider.go, internal/tofu/node_resource_abstract.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_abstract_instance_test.go, internal/tofu/node_resource_abstract_test.go, internal/tofu/node_resource_apply_instance.go, internal/tofu/node_resource_deposed.go, internal/tofu/node_resource_deposed_test.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_forget.go, internal/tofu/node_resource_import.go, internal/tofu/node_resource_plan.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/node_resource_validate.go, internal/tofu/node_resource_validate_test.go, internal/tofu/transform_attach_schema.go
The graph node types related to resources and resource instances use a bunch of helper functions in different combinations, rather than calling directly into the provider API.
This changeset plumbs `context.Context` through to the functions that _do_ call methods directly on the provider object, leaving us just one more step away from plumbing the context through to the actual gRPC calls.
The next step (in a future PR) will be to update the `providers.Interface` methods to take `context.Context` arguments and then have the gRPC-based implementations of that interface pass the context through to the gRPC client stub calls, and then we should be pretty close to being able to turn on OTel tracing instrumentation for our gRPC client requests.
=> tofu: Plumb context.Context through the resource-handling functions

internal/tracing/init.go
There are situations where the service name may want to be overwritten by the end-user. This commit allows the user to set the service name via the environment variable OTEL_SERVICE_NAME. This is useful for testing and debugging purposes, but also to help identify in what context tofu is running. For example in github actions you may want to set the service name to "github-actions-tofu" to help identify the run.
=> Allow end-users to set OTEL_SERVICE_NAME

internal/tofu/evaluate.go
When given a resource m that depends on resource n, if for_each or count were used in any significant way a massive lock contention was encountered.
In pseudocode:
```
for mi in m {
for ni in n {
lock()
for c in {m, n} {
...
}
unlock()
}
}
// Iterations: m * n * (m+n)
// Locking: m * n
```
To:
```
for mi in m {
lock()
for c in {m, n} {
...
}
unlock()
for ni in n {
...
}
for ni in n {
...
}
}
// Iterations: m * (m+n+n+n)
// Locking: m
```
Concretely, the following goes from ~40minutes down to under 5 minutes on my system:
```hcl
locals {
entities = merge([for i in range(25) : {for k, v in {for i in range(100) : "s${i}" => i } : "${i}${k}"=> v}]...)
}
resource "tfcoremock_simple_resource" "entities" {
for_each = local.entities
string = each.key
number = each.value
}
resource …
```
=> Remove m*n locking from resource evaluation and O(m * n * (m+n)) iteration

.github/scripts/govulncheck-submit-issues.sh
In order to not report the same vulnerabilities multiple times, we want to check for closed issues too. There are some issues that are well known and will not be fixed since those are not directly affecting OpenTofu and their users.
Therefore, this PR is fixing the way we are checking for the already reported and solved issues.
There is no issue linked to this, this fix is only a response to the duplicated reports from yesterday:
* #2856
* #2857
* #2858
* #2859
=> [Govulncheck] Fix the command that checks for duplicated reports

website/docs/cli/oci_registries/provider-mirror.mdx
This text was from earlier on in the development period when we hadn't yet settled on a strategy, but now we are intending to work with the ORAS team so that ORAS can construct index manifests in the form that OpenTofu expects, so we'll talk about that instead of making a comment about prereleases that will become confusing once OpenTofu v1.10.0 final is released.
This is for https://github.com/opentofu/opentofu/issues/2540.
=> website: OCI provider mirror shouldn't talk about prereleases anymore

internal/addrs/resource.go, internal/repl/session_test.go, internal/tofu/context_input.go, internal/tofu/context_input_test.go, internal/tofu/context_plan2_test.go, internal/tofu/evaluate_valid.go, internal/tofu/evaluate_valid_test.go, internal/tofu/graph_builder_plan_test.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_apply_instance.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/node_resource_plan_orphan_test.go, internal/tofu/node_resource_validate.go, internal/tofu/node_resource_validate_test.go, internal/tofu/resource_provider_mock_test.go, internal/tofu/testdata/input-provider/main.tf, internal/tofu/testdata/static-validate-refs/static-validate-refs.tf, internal/tofu/transform_attach_config_resource.go, internal/tofu/transform_config.go, internal/tofu/transform_diff_test.go, internal/tofu/transform_reference.go
Part of #2834 
More details can be found in the commit messages.
Overview:
* Collect implicit providers from ephemeral resources too. This enables prompting the user for required attributes for the provider configuration that are implicitly imported by ephemeral resources (27810db5b7ad38999e63a316c406d0cb5ad9371a)
* Add ephemeral resources into the graph. More details into the commit (3048496f65a0e8e4d045e4512fb453f7f1bd22b8)
* Ensure that a NodeDestroyResourceInstance is never going to execute on ephemeral resources since these cannot be destroyed (c9ac05058392742a6b451b2e3e81ed96ec5b2c0e)
* Ensure that a NodePlanDestroyableResourceInstance is never going to execute on ephemeral resources since these cannot be planned for destroy operations (6650f11cfcea2a15879cafd0b0fad2103c97b5fd)
* …
=> Ephemeral resources in internal/tofu

internal/configs/config.go, internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go
Part of #2834
Overview:
* Reworked the diagnostics handling in grpc provider implementation for the `Open` method
* Refactor implicit providers collection since it was duplicated 3 times
=> [Ephemeral] Apply suggestions on #2852

website/README.md
Related to #2885
I spent a couple hours trying to link a custom local version via. code because I didn't understand how the local development versioning was set up for docusaurus.
Added the extra step to the doc for the next person
=> docs: add dev version step for local docs

cmd/tofu/main.go, cmd/tofu/provider_source.go, internal/command/command_test.go, internal/command/init.go, internal/command/meta_providers.go, internal/command/providers_lock.go, internal/command/providers_mirror.go, internal/getproviders/filesystem_mirror_source.go, internal/getproviders/filesystem_mirror_source_test.go, internal/getproviders/http_mirror_source.go, internal/getproviders/oci_registry_mirror_source.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go, internal/providercache/installer_test.go
This is related to https://github.com/opentofu/opentofu/issues/2664.
This completes some of the missing connections for contexts in the provider source codepaths by introducing context.Context parameters and wiring them through so we can eliminate a few more `context.TODO()` placeholders.
For consistency's sake this adds context.Context to all four of the `getproviders.Source` implementations that directly interact with stuff outside of OpenTofu (network services or filesystem), even though not all of them currently make use of it, just because interactions with outside stuff tends to encourage the use of cross-cutting concerns like logging and tracing and so this ensures we have contexts propagated in there for such future uses.
=> getproviders: context.Context for source constructor functions

CHANGELOG.md
As we prepare for the final v1.10.0 release, this is a copy-edit of the overall changelog content to improve consistency and approximately prioritize items by expected impact.
**[Rendered Version](https://github.com/opentofu/opentofu/blob/changelog-finalize-v1.10/CHANGELOG.md)**
As always with this sort of change, I made some subjective editorial decisions here which I welcome feedback on if they seem misguided:
- Overall, the changelog items describe how OpenTofu v1.10.0 behavior differs from prior versions from the user's perspective, rather than describing actions we took to cause those differences. (The specific actions we took are already documented in the associated pull requests, should anyone want to learn about that.)
- I moved "UPGRADE NOTES" after "NEW FEATURES" because in this …
=> CHANGELOG: Copy-editing pass in preparation for v1.10.0 final

internal/tofu/context_test.go, internal/tofu/eval_context.go, internal/tofu/eval_context_builtin.go, internal/tofu/eval_context_builtin_test.go, internal/tofu/eval_context_mock.go, internal/tofu/eval_provider.go, internal/tofu/eval_provider_test.go, internal/tofu/node_provider.go, internal/tofu/node_provider_eval.go, internal/tofu/node_resource_abstract_instance.go, internal/tofu/node_resource_apply_instance.go, internal/tofu/node_resource_deposed.go, internal/tofu/node_resource_destroy.go, internal/tofu/node_resource_forget.go, internal/tofu/node_resource_import.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/transform_provider.go
Continuing the ongoing work of getting context.Context wired in everywhere we might want to generate OpenTelemetry traces, this completes all of the provider-related methods of `EvalContext`.
Unfortunately there is still one remaining path not included here: the `EvalContext.EvaluationScope` method needs to somehow arrange for contexts to reach the provider-defined functions so that we can pass the context to `providers.Interface.CallFunction`, which is tricky because that has to get through the `cty` function API that wasn't designed for functions that are backed by network calls. We'll deal with that in a subsequent commit because it's likely to be a more invasive change than the relatively-mechanical wiring updates included here.
=> tofu: EvalContext provider methods take context.Context

CODEOWNERS
CODEOWNERS is not working at the moment since we have a new governance chart and the new team is named `opentofu-maintainers`
=> update `CODEOWNERS` to match the new governance chart

CHANGELOG.md, internal/command/e2etest/providers_tamper_test.go, internal/command/e2etest/testdata/predecessor-dependency-lock-file-abs/.terraform.lock.hcl, internal/command/e2etest/testdata/predecessor-dependency-lock-file-abs/predecessor-dependency-lock-file.tf, internal/command/init.go, internal/command/meta_dependencies.go, internal/command/providers_lock.go, internal/command/providers_mirror.go
This is a backport of https://github.com/opentofu/opentofu/pull/2979 to the v1.10 branch.
=> [v1.10 BACKPORT] command: Only shim dependency lock file for installation actions

cmd/tofu/oci_distribution.go
Previously we generated some logs during the discovery process indicating which locations OpenTofu was probing for ambient credentials, but we didn't explicitly report the overall result of the discovery process.
These new log lines will now report the final effective set of credential configuration locations just before we try to use them in either the provider installation or module installation codepaths. The strings returned by `CredentialsConfigLocationForUI` are intended for just this sort of feedback: the exact format varies for each kind of location, but it's always a concise string identifying a location that OpenTofu will consider when attempting to decide credentials.
Logging this here does unfortunately mean that the log output will be repeated for each separate OCI registry …
=> main: Log the effective set of OCI credential search locations

CHANGELOG.md, internal/command/jsonformat/structured/attribute_path/matcher.go, internal/command/jsonformat/structured/attribute_path/matcher_test.go, internal/command/plan_test.go, internal/command/testdata/plan-invalid-reference-try/plan-invalid-reference-try.tf
This is a direct backport of https://github.com/opentofu/opentofu/pull/2988 to the `v1.10` branch, along with its changelog entry since we expect this change will be released for the first time in v1.10.3.
=> [v1.10 BACKPORT] jsonformat: Tolerate incorrect paths in plan relevant_attributes

internal/getproviders/package_location_http_archive.go
Resolves #2843 
Fixed an issue where temporary Terraform provider files (e.g., terraform-providerXXXXX) were not cleaned up properly on Windows systems.
Before applying the fix, temporary provider files were left behind in the %TEMP% directory after running tofu init.
After applying the fix, the provider temporary file is removed correctly upon completion.
=> fix: Temp data cleanup in windows

internal/configs/configschema/schema.go
Previously we had separate documentation for each of Required, Optional and Computed, but didn't clearly state what combinations are valid and what each of those combinations means.
Now we'll document all three of these flag fields together with a single doc comment, since we treat them essentially like a single field capturing four possible states despite the Go type implying more flexibility.
In future we might choose to _actually_ replace these three fields with a single enumeration field with four valid values, but that'd be a considerably more invasive and risky change so for now we'll just settle for documenting the assumptions the system already makes for these fields.
---
This is an attempt to summarize the main information I previously shared as …
=> configschema: Document the valid combinations of Attribute flags

CHANGELOG.md, internal/lang/funcs/sensitive.go, internal/lang/funcs/sensitive_test.go
Other parts of the language allow deciding the sensitivity of a value based on results that won't be known until the apply phase, which means that in practice we cannot predict the final sensitivity of an unknown value.
Previously this function assumed that an unknown value would always be a placeholder for a final value of the same sensitivity, which is not a valid assumption in practice and so using the results of this function could cause downstream value consistency checks to fail.
---
This does unfortunately create a situation where a new version of OpenTofu will return an unknown value in a situation that was previously always known, which could therefore begin causing a plan-time error if the result is then used to populate something that is required to be known at plan time. …
=> funcs: issensitive returns unknown when given an unknown value

CHANGELOG.md, internal/command/arguments/show.go, internal/command/arguments/show_test.go, internal/command/arguments/showtargettype_string.go, internal/command/jsonconfig/config.go, internal/command/jsonconfig/expression.go, internal/command/jsonconfig/expression_test.go, internal/command/jsonconfig/single_module.go, internal/command/show.go, internal/command/show_test.go, internal/command/testdata/show-config-single-module/main.tf, internal/command/views/show.go, website/docs/cli/commands/show.mdx
We previously added the `-config` mode for showing the entire assembled configuration tree, including the content of any descendent modules, but that mode requires first running `tofu init` to install all of the provider and module dependencies of the configuration.
This new `-module=DIR` mode returns a subset of the same JSON representation for only a single module that can be generated without first installing any dependencies, making this mode more appropriate for situations like generating documentation for a single module when importing it into the OpenTofu Registry. The registry generation process does not want to endure the overhead of installing other providers and modules when all it actually needs is metadata about the top-level declarations in the module.
As with `-config`, …
=> tofu show: -module=DIR mode, for showing just a single module

CHANGELOG.md, internal/command/jsonconfig/config.go, internal/command/jsonconfig/config_test.go, internal/command/show_test.go, internal/command/testdata/show-json/conditions/output-refresh-only.json, internal/command/testdata/show-json/conditions/output.json, testing/equivalence-tests/outputs/data_read/plan.json, testing/equivalence-tests/outputs/variables_and_outputs/plan.json, website/docs/internals/json-format.mdx
The JSON object describing an input variable can now include two additional
properties:
- `"type"` provides a JSON representation of the variable's type constraint, if one is set. Omitted if either there is no constraint declared at all or if it's set to `any`, which are equivalent and both mean that the type is completely unconstrained.
This uses the usual `cty` representation of a type constraint, which matches how OpenTofu already describes types and type constraints in the provider protocol, in state snapshots, and in saved plan files.
- `"required"` directly represents whether callers are required to provide a value for the variable. This is technically redundant since it is set to true unless `"default"` is also present, but this avoids the need for consuming software to reimplement …
=> jsonconfig: Additional details about input variables

internal/configs/hcl2shim/mock_value_composer.go, internal/configs/hcl2shim/mock_value_composer_test.go
Directly accessing the "Type" attribute of configschema.Attribute is not correct because there are actually two different "flavors" of attribute type in modern OpenTofu: "simple" attributes use the Type field, while structural-typed attributes use the NestedType field to specify a more block-like schema that can support extra detail such as having a mixture of config-specified and provider-specified values within the same attribute.
Calling the ImpliedType method instead hides this distinction by taking the implied type of the NestedType if set, but returning the simple Type if not.
This fixes https://github.com/opentofu/opentofu/issues/2993. If merged, this should be backported to the `v1.10` branch and so its changelog entry would be included in that backport.
---
Although my initial …
=> hcl2shim: MockValueComposer handles structural-typed attributes

internal/command/e2etest/primary_test.go, internal/command/e2etest/testdata/ephemeral-workflow/proto5/main.tf, internal/command/e2etest/testdata/ephemeral-workflow/proto6/main.tf, internal/provider-simple-v6/provider.go, internal/provider-simple/provider.go, internal/tofu/graph_builder_plan.go, internal/tofu/node_resource_plan_destroy.go, internal/tofu/testdata/transform-config-mode-data/main.tf, internal/tofu/transform_config.go, internal/tofu/transform_config_test.go, internal/tofu/transform_destroy_edge.go, internal/tofu/transform_destroy_edge_test.go
Part of #2834
_same comment with the one in the commit_
During testing references of an ephemeral resource in a provider block
configuration, we found out that the ephemeral resources were not
planned to be opened in order to provide the relevant information to
destroy the second provider related resources.
Consider the following config:
```
provider "testprovider" {
alias = "prov1"
}
ephemeral "testprovider_ephemeral" "res" {
provider = testprovider.prov1
...
}
provider "testprovider" {
alias = "prov2"
cfg = ephemeral.testprovider_ephemeral.res // <- HERE
}
resource "testprovider_resource" "res2" {
provider = testprovider.prov2
...
}
```
As can be seen, during destroy, in order to destroy "res2", we need to
have configured the testprovider.prov2 with the value coming from an
ephemeral …
=> Destroy nodes with dependencies on ephemeral resources

internal/lang/evalchecks/eval_for_each.go, internal/lang/evalchecks/eval_for_each_test.go
Will need to be backported to 1.10, originated in the rewrite of for_each https://github.com/opentofu/opentofu/pull/2597
Resolves #3065
=> Fix crash with sensitive for_each set elements

website/docs/language/settings/backends/s3.mdx
This PR clarifies that the OpenTofu team has no intention of deprecating the dynamodb locking mechanism. It also seperates out the dynamo-to-s3-native locking migration path into it's own section.
=> Clarify dynamodb vs s3-native locking guidance

internal/configs/config_test.go, internal/configs/resource.go
Part of #2834
Initially, the function to generate diags was using the root block `hcl.Range`. Now, it points directly to the affected sub-block.
=> Fix the ephemeral resources diagnostics block range

CHANGELOG.md, internal/tofu/context_apply2_test.go, internal/tofu/graph_builder_apply.go, internal/tofu/graph_builder_plan.go, internal/tofu/node_local.go, internal/tofu/node_module_variable.go, internal/tofu/node_output.go, internal/tofu/node_value.go, internal/tofu/node_variable_reference.go, internal/tofu/transform_destroy_edge.go, internal/tofu/transform_destroy_edge_test.go, internal/tofu/transform_targets.go
This fixes an issue I originally introduced in https://github.com/opentofu/opentofu/pull/2216.  The original PR and this PR try to modify the graph transformation process as little as possible due to it's complexity.
Unfortunately, I introduced a path in #2216 for apply that does not apply to destroy operations.  In both apply and destroy, we aggressively prune the graph to minimize what actually needs to be evaluated in order to make the necessary changes.  This work is done in the pruneUnusedNodesTransformer and relies upon some very specific interface implementation and dense logic.
For #2216, I needed to ensure that variable blocks that have validations are not pruned out from the graph between plan -> apply.  I introduced an interface implementation that allows the node to say "Hey! …
=> Validations should only be run during non-destroy operations

rfc/20250317-ephemeral-resources.md
Part of #2834 and a revisit of #2996.
After a double check of the `terraform.applying` we need to update the RFC to reflect the actual wanted behaviour of this new property.
Initially I thought that it is about the `apply` command, but this is actually about the `apply` phase so we need to update the RFC accordingly and have it implemented correctly.
=> Update the RFC related to tofu.applying/terraform.applying

.github/workflows/checks.yml
We have some logic to try to skip running the Go tests when no Go source files have changed, but that means that a commit that only changes the workflows won't run the unit tests.
To work around this, we'll also treat changes under the .github directory as if they are "Go changes", since _everything_ should run when we're changing the workflows so that we can make sure the workflows actually still all work.
This started as part of https://github.com/opentofu/opentofu/pull/3055, but it's a general rule that applies to more than just unit tests running on Windows so I've split it out here for separate review and perhaps being merged long before we're ready to enable unit tests runs on Windows.
=> .github/workflows: Treat workflow changes as Go changes

CHANGELOG.md, go.mod, go.sum
This is mainly just to have one fewer dependency lagging behind latest, but includes a change to support running the "stty" program from any directory in PATH, rather than requiring it to be at /bin/stty, which improves portability to systems with non-traditional directory layouts, such as NixOS.
=> go.mod: go get github.com/bgentry/speakeasy@v0.2.0

.github/workflows/checks.yml
In our checks workflow we try to skip running unit tests unless Go files have changed, but we didn't previously consider "go.mod" and "go.sum" as "Go files".
Changes to our dependencies can change the results of our tests, so we should run tests even if only the dependencies have changed.
=> .github/workflows: Run unit tests when go.mod/go.sum files change

CHANGELOG.md, internal/command/jsonformat/plan.go, internal/command/jsonformat/plan_test.go, internal/command/test_test.go, testing/equivalence-tests/outputs/basic_json_string_update/plan, testing/equivalence-tests/outputs/basic_list_empty/plan, testing/equivalence-tests/outputs/basic_list_null/plan, testing/equivalence-tests/outputs/basic_list_update/plan, testing/equivalence-tests/outputs/basic_map_empty/plan, testing/equivalence-tests/outputs/basic_map_null/plan, testing/equivalence-tests/outputs/basic_map_update/plan, testing/equivalence-tests/outputs/basic_multiline_string_update/plan, testing/equivalence-tests/outputs/basic_set_empty/plan, testing/equivalence-tests/outputs/basic_set_null/plan, testing/equivalence-tests/outputs/basic_set_update/plan, testing/equivalence-tests/outputs/drift_relevant_attributes/plan, testing/equivalence-tests/outputs/drift_simple/plan, testing/equivalence-tests/outputs/fully_populated_complex_update/plan, testing/equivalence-tests/outputs/moved_with_drift/plan, testing/equivalence-tests/outputs/moved_with_update/plan, testing/equivalence-tests/outputs/multiple_block_types_update/plan, testing/equivalence-tests/outputs/nested_list_update/plan, testing/equivalence-tests/outputs/nested_map_update/plan, testing/equivalence-tests/outputs/nested_objects_update/plan, testing/equivalence-tests/outputs/nested_set_update/plan, testing/equivalence-tests/outputs/simple_object_empty/plan, testing/equivalence-tests/outputs/simple_object_null/plan, testing/equivalence-tests/outputs/simple_object_update/plan
The human-oriented plan output includes a short summary of the meaning of all of the different "icons" used to describe different kinds of change, but nothing was previously describing how OpenTofu uses `->` to describe the transition between current and planned values for update in-place, `~`.
We'll now include a concise note about that as part of the icon summary, keeping things still relatively compact but nonetheless giving something to refer to if a reader is unsure about the meaning of this notation.
Closes https://github.com/opentofu/opentofu/issues/3158.
=> plan diff: summarize the current -> planned notation

CHANGELOG.md, go.mod, internal/copy/copy_dir.go
Reduces the impact of the issue reported in #1086 
More specifically: When using monorepo/centralized modules with lots of files, this starts multiple IO copies in parallel.
=> Use parallel errgroup to increase file copy speed

CHANGELOG.md, internal/command/test_test.go, internal/command/testdata/test/deprecated_outputs/main.tf, internal/command/testdata/test/deprecated_outputs/main.tftest.hcl, internal/lang/marks/marks.go
Marking a root output as deprecated has no impact. We hit this case when using the test framework on a module.
Resolves #3246
=> Fix test crash when using deprecated outputs in the root module

CHANGELOG.md, internal/configs/parser_config_test.go, internal/configs/resource.go, internal/configs/testdata/invalid-files/data-count-and-for_each-and-enabled.tf, internal/configs/testdata/invalid-files/ephemeral-count-and-for_each-and-enabled.tf, internal/configs/testdata/invalid-files/resource-count-and-for_each-and-enabled.tf, internal/instances/expander.go, internal/instances/expansion_mode.go, internal/lang/evalchecks/eval_lifecycle_enabled.go, internal/lang/evalchecks/eval_lifecycle_enabled_test.go, internal/tofu/context_apply2_test.go, internal/tofu/eval_expansion.go, internal/tofu/evaluate.go, internal/tofu/node_resource_abstract.go, internal/tofu/node_resource_plan_instance.go, internal/tofu/node_resource_plan_orphan.go, internal/tofu/testdata/apply-enabled-resource/apply-enabled-resource.tf
Relates to #3247 
Resolves #1306
Related to #3244
> I'm gonna write the user-facing documentation in another PR. This one is focused on the implementation itself. Please refer to #3247 
Implementation of the RFC #3066 focused on resources.
=> Add support for the `enabled` field in resource lifecycle

internal/command/apply_test.go
Related to #1201 
This PR fixes `TestApply_plan_backup` by triggering garbage collection to avoid `TempDir RemoveAll cleanup` errors.
```
--- FAIL: TestApply_plan_backup (1.34s)
testing.go:1369: TempDir RemoveAll cleanup: unlinkat C:\Users\RUNNER~1\AppData\Local\Temp\TestApply_plan_backup257766278\001\state.tfstate: The process cannot access the file because it is being used by another process.
2025/09/30 18:14:55 [DEBUG] GET http://127.0.0.1:53955/providers/v1/hashicorp/frob/versions
2025/09/30 18:14:55 [DEBUG] GET http://127.0.0.1:53955/providers/v1/-/frob/versions
2025/09/30 18:14:55 [DEBUG] GET http://127.0.0.1:53955/providers/v1/hashicorp/foo/versions
2025/09/30 18:14:55 [DEBUG] GET http://127.0.0.1:53955/providers/v1/hashicorp/baz/versions
2025/09/30 18:14:55 [DEBUG] GET …
```
=> fix `TestApply_plan_backup` test on Windows by using garbage collection

.github/workflows/checks.yml
Blocked by https://github.com/opentofu/opentofu/pull/3320
This resolves https://github.com/opentofu/opentofu/issues/1201.
However, I've created it today mainly just to use it to find out what's still failing when we run the tests on this platform, and it'll remain in draft until all of the tests have been made to pass by other subissues of https://github.com/opentofu/opentofu/issues/1201.
I intend to rebase this each time we merge test fixes for Windows so that we can re-run the tests and keep track of progress.
=> .github/workflows: Add windows_amd64 to unit test matrix

go.mod, go.sum, internal/builtin/providers/tf/data_source_state_test.go, internal/configs/configschema/decoder_spec_test.go, internal/configs/configschema/empty_value_test.go, internal/plans/objchange/compatible_test.go, internal/plans/objchange/normalize_obj_test.go, internal/plans/objchange/objchange_test.go, internal/plans/objchange/plan_valid_test.go
This upstream library (which I wrote a long time ago, independently of my work on OpenTofu) came about because "go-spew" tended to produce unreadable representations of certain types commonly used in OpenTofu, whereas "go-dump" is really just a pretty-printer for whatever a type might produce when formatted using the `%#v` verb in `package fmt`.
Over time the uses of this seem to have decreased only to some leftover situations where we wanted to pretty-print a `cty.Value` in a test, but we already depend on `go-cty-debug` that has a more specialized implementation of that behavior and so switching the few remaining callers over to that allows us to remove one dependency.
(And, FWIW, that upstream dependency is effectively unmaintained; I don't know of any callers of it other than OpenTofu …
=> dependencies: Stop using github.com/apparentlymart/go-dump

go.mod, go.sum
This is just a routine dependency upgrade.
We use this library only in the `tofu providers` subcommand, to produce the tree-like rendering.
=> go.mod: go get github.com/xlab/treeprint@v1.2.0

CHANGELOG.md, go.mod, go.sum
This is a routine dependency upgrade, but includes some behavior changes that fix some upstream bugs:
- https://github.com/bmatcuk/doublestar/issues/96
- https://github.com/bmatcuk/doublestar/issues/88
The first of these improves the behavior of OpenTofu's `fileset` function slightly, so I've added a changelog entry for it. The second doesn't really affect `fileset` because our function is defined as only matching actual files, whereas that fix is about matching directories.
**[Full changes since v4.6.0](https://github.com/bmatcuk/doublestar/compare/v4.6.0...v4.9.1)**
=> go.mod: go get github.com/bmatcuk/doublestar/v4@v4.9.1
